### ISSUE TITLE
[Supply Chain Security Incident]

### ISSUE THREAD

**Issue by JustinCappos** [cncf/tag-security#1000]
Comm100 was compromised.  Let's add information about this to the Supply Chain Security Doc...  https://www.securityweek.com/supply-chain-attack-targets-customer-engagement-firm-comm100?utm_medium=email&utm_source=Eloqua&ref=GBSNewsletterEmail

**Comment by Caze121** [comment]
Yes, good idea.  Will add this with another issue that I will push later today

**Comment by Caze121** [comment]
This was completed and published, can we close the issue?

[https://github.com/cncf/tag-security/blob/main/supply-chain-security/compromises/2022/Comm100-live-chat-trojan.md](url)
