### ISSUE TITLE
[Suggestion] Reported Supply Chain Security Incident

### ISSUE THREAD

**Issue by alanssitis** [cncf/tag-security#1004]
Description: New supply chain security incident that affected a media outlet.

Scope: Update the "compromises" list.

Additional info:
- https://twitter.com/threatinsight/status/1587865920130752515
- https://www.darkreading.com/application-security/supply-chain-attack-pushes-out-malware-to-more-than-250-media-websites

**Comment by szh** [comment]
Hey @alanssitis,

Thank you for the issue! Do you want to submit a PR for this?

**Comment by alanssitis** [comment]
I would love to! I will do so once my schedule begins to clear up.

**Comment by anvega** [comment]
Closing issue as action item is on @alanssitis.
