### ISSUE TITLE
[Proposal] KubeCon EU 2023 - Security Village

### ISSUE THREAD

**Issue by ragashreeshekar** [cncf/tag-security#1012]
**Description**: TAG Security fostered Cloud Native SecurityCon which was designed to create a focus space to foster collaboration, discussion, and knowledge sharing of OSS Security. With it's evolution as a standalone event, we are following a slightly different model with Security Village hosted in KubeCon as opposed to the previous KubeCon co-located event.  This issue will track activities related to TAG Security events for KubeCon EU security village.

**Scope and Responsibilities**
The responsibilities of the program committee include but are not limited to:
- Active involvement in CFP review, scoring, and schedule-building process
- PC Members should allocate 4-5 total hours to complete the CFP review during the review window
- (Where applicable) Review of Diamond sponsor talk content + BoF proposals prior to approval
- (Where applicable) Support marketing efforts to drive registration
- Attend post-event debrief meeting

**To Do**
 

- [x] STAG Rep: @mnm678 and @ragashreeshekar 
- [x] Finalize Program Committee Members
- [x] Logistics - Slack Channel: Invite only, reach out to STAG Reps
- [x] CFP preparation: [CFP open until March 10](https://docs.google.com/forms/d/1BYMFJOd2HtKRyBAhqiAi6L7TxAp6-mVNP5RJfEeCI7o/edit)
- [x] CFP Review (March 11-15): Done
- [x] Agenda: https://kccnceu2023.sched.com/type/Security+%2B+Identity/TAG+Security+Recommended
- [x] Security Day event schedule/planning: Done
- [x] Finalize "Day Of" Staff
- [ ] Retrospective: Ongoing

**Comment by szh** [comment]
I would be interested in helping out with this, although I do not plan to attend in person.

**Comment by mattj-io** [comment]
I would be happy to volunteer

**Comment by raesene** [comment]
I'd be happy to help out with this one.

**Comment by karmichand** [comment]
Same, happy to assist.

**Comment by aks-secops** [comment]
I would like to be involved.

**Comment by kevsecops** [comment]
I will be there in person and happy to support

**Comment by sublimino** [comment]
Looking forward to this! 😊

**Comment by tomergreenwald** [comment]
Happy to assist, I'll also be attending in person.

**Comment by krol3** [comment]
I would happy to be a volunteer :)

**Comment by itaysk** [comment]
@ragashreeshekar can you (or someone else) please share more info on what's different about the "village" this time from previous cloud native security day?

**Comment by mnm678** [comment]
The village will take place on the main conference days (instead of the 2 days before), and will be a space to discuss cloud native security topics through presentations and interactive events.

**Comment by anoopadvaitha** [comment]
I'd be happy to involve for this.

**Comment by gracenng** [comment]
Interested in assisting with this

**Comment by jkjell** [comment]
I'd love to help with this too!  Super excited about this idea.

**Comment by abhinavbom** [comment]
interested in getting involved.

**Comment by sergey-pronin** [comment]
count me in 🙌🏻

**Comment by ragashreeshekar** [comment]
Thank you for the overwhelming response!
More details coming real soon, stay tuned! :)

**Comment by ams0** [comment]
I'm at Kubecon and Amsterdam local, with experience organizing conferences (KCD), so HTH!

**Comment by mnm678** [comment]
Thank you all for the interest! Please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdlXYObyCo0JMV-qSJOYciU9Kt_HYgx8CUA2DWew8zuWlCPZg/viewform?usp=sf_link) to indicate what you would like to volunteer for (cfp or day-of), and provide us some contact information.

**Comment by itaysk** [comment]
> The Call For Proposal (CFP) review will take place from March 11 - March 15

is there a CFP for security village?

**Comment by mnm678** [comment]
> is there a CFP for security village?

We have some talk slots available, and will be posting a form for talk ideas in the next day or so. Due to the abbreviated timeline of this first security village we are hoping to give at least a week for folks to submit talk ideas but this will be a less formal cfp.

**Comment by tomergreenwald** [comment]
Happy to lead a discussion about authorization. Where can I submit a proposal?

**Comment by mnm678** [comment]
Here is the [form](https://docs.google.com/forms/d/e/1FAIpQLSeHn9zI0xnUOOs-ozVjHWkLFv7MkzxSxEfix6l8bGqcET3HdQ/viewform?usp=sf_link) to submit proposals for talks at the Security Village. We are accepting proposals through March 10, so please share with your networks!

**Comment by th3w4y** [comment]
I am trying to organise  a submission from my side to the open CFP form above
I would appreciate if posible some information on:

1. Nr. of people expected by the organizing commity of people attenting the Security Village
2. Will  there be Media present at Security Village beside those linked with the KubeCon event. (if yes, who?)
3. Will there be Social Media presence organized from your side,  and if yes what twitter / LinkedIn (other) handles will be posting about the KubeCon EU 2023 Security Village and within which period.

you can find me on `CNCF Slack` if you can please provide any of the details above in a DM (or here.)

Thank you.

**Comment by ragashreeshekar** [comment]
> I am trying to organise a submission from my side to the open CFP form above I would appreciate if posible some information on:
> 
> 1. Nr. of people expected by the organizing commity to attend the Security Village
> 2. Will  there be Media present at Security Village beside those linked with the KubeCon event. (if yes, who?)
> 3. Will there be Social Media presence organized from your side,  and if yes what twitter / LinkedIn (other) handles will be posting about the KubeCon EU 2023 Security Village and within which period.
> 
> you can find me on `CNCF Slack` if you can please provide any of the details above in a DM (or here.)
> 
> Thank you.

Responded to your query on Slack, hope that helps.

**Comment by th3w4y** [comment]
> > I am trying to organise a submission from my side to the open CFP form above I would appreciate if posible some information on:
> > 
> > 1. Nr. of people expected by the organizing commity to attend the Security Village
> > 2. Will  there be Media present at Security Village beside those linked with the KubeCon event. (if yes, who?)
> > 3. Will there be Social Media presence organized from your side,  and if yes what twitter / LinkedIn (other) handles will be posting about the KubeCon EU 2023 Security Village and within which period.
> > 
> > you can find me on `CNCF Slack` if you can please provide any of the details above in a DM (or here.)
> > Thank you.
> 
> Responded to your query on Slack, hope that helps.

thank you very much

**Comment by oletizi** [comment]
Is there a list of accepted talks somewhere? I'm not having much success finding one.

**Comment by ragashreeshekar** [comment]
> Is there a list of accepted talks somewhere? I'm not having much success finding one.

We proposed our recommendations to the KubeCon Co-Chairs, and the finalisation is in progress.

The speakers will be notified of the status of their shortly, and once agenda is finalized, it will be listed in schedule of events. 

I hope this helps.

**Comment by oletizi** [comment]
Thank you

**Comment by oletizi** [comment]
> > Is there a list of accepted talks somewhere? I'm not having much success finding one.
> 
> We proposed our recommendations to the KubeCon Co-Chairs, and the finalisation is in progress.
> 
> The speakers will be notified of the status of their shortly, and once agenda is finalized, it will be listed in schedule of events.
> 
> I hope this helps.

thank you

**Comment by ragashreeshekar** [comment]
Agenda is available at https://kccnceu2023.sched.com/type/Security+%2B+Identity/TAG+Security+Recommended

**Comment by jkjell** [comment]
Can we add a Task for having a "Retrospective".  For the folks who were there in person, we had lots of ideas for next time.  The sooner we capture those for planning Chicago, the better. ☺️

**Comment by lumjjb** [comment]
+1 on retro. Would be very valuable here given it’s the first!

**Comment by ragashreeshekar** [comment]
@jkjell Great idea! I have added a task for retrospective, Thanks @mlieberman85 for documenting notes. 
We can discuss this in the next TAG meeting or have a separate meeting altogether. 
What do you all prefer?

**Comment by anvega** [comment]
Past event.
