### ISSUE TITLE
Cloud Native Security Con 2023: Team Dinner in Seattle 

### ISSUE THREAD

**Issue by asadfaizi-github** [cncf/tag-security#1013]
CloudNative SecurityCon is coming to Seattle, Feb 1-2, 2023.

If you are planning to attend, let meet over dinner in Seattle while you are here.

Please add your name if you are interested...

**Comment by szh** [comment]
I'll be there. I can only come if it's at a Kosher restaurant or one that doesn't mind me bringing my own Kosher food.

**Comment by lumjjb** [comment]
I'll be there!!

**Comment by mnm678** [comment]
I'll be there!

**Comment by ragashreeshekar** [comment]
I'll be there as well :)

**Comment by adityasaky** [comment]
+1, this sounds great!

**Comment by fkautz** [comment]
I will be there.

**Comment by usarid** [comment]
I'm looking forward to being there!

**Comment by tomergreenwald** [comment]
Same here!

**Comment by sublimino** [comment]
Me too ☺️

**Comment by adityasaky** [comment]
Are we doing this on Feb 1st?

**Comment by asadfaizi-github** [comment]
We have 10 people now. @adityasaky we can plan for Feb 1st

**Comment by asadfaizi-github** [comment]
Team, we have a choice of (a) Italian - a bit formal, (b) seafood - casual, and (c) Sushi - semi-casual

What would you prefer? Let's put democracy to test to see if it really solves the problem :)

**Comment by usarid** [comment]
Present :-p

I’m good for any of these.

**Comment by asadfaizi-github** [comment]
One abstention 😀

**Comment by mlieberman85** [comment]
I will be around

**Comment by slashben** [comment]
I would like to join, with the same approach as @szh :)

**Comment by rowan-baker** [comment]
I'd like to join as well please!

**Comment by mrcdb** [comment]
me too, please!

**Comment by lumjjb** [comment]
+1 all sound good!

**Comment by morwn** [comment]
Count me In!

**Comment by itaysk** [comment]
I'll be there

**Comment by upkarlidder** [comment]
I would love to say hi if this is open to the general community.

**Comment by asadfaizi-github** [comment]
Please join us. We would love to have you

**Comment by asadfaizi-github** [comment]
There are 20 of us. I have booked a table for 20 people at Wild Ginger Restaurant on **Feb 1st @ 7:00 PM.**

Wild Ginger Restaurant
1401 3rd Ave,
Seattle WA 98101
(206) 623-4450
https://maps.app.goo.gl/526Z1fZoidbZhtk38?g_st=iw

It is 6 minutes walk from Seattle Convention Center (also 6 minutes drive, in case it rains that day).

** @szh & @slashben - they do not offer Kosher food and won't allow outside food because of health regulations

**Comment by szh** [comment]
OK. I'll likely stop in to say hi. Thanks for asking them about it!

**Comment by asadfaizi-github** [comment]
@szh please do. Even if you won't be eating with us, maybe you can have dessert and coffee with us

**Comment by magnologan** [comment]
I'll be there

**Comment by amirkCA** [comment]
I will be there

**Comment by andrewkrug** [comment]
If there's room I'd love to join.  If not can swing by and wave :)

**Comment by rowan-baker** [comment]
I can no longer make it unfortunately, stuck back in the UK with illness. Hope everyone has a great time!

**Comment by sergiopozoh** [comment]
is there room for one more? I can join, please let me know. Thanks

**Comment by ragashreeshekar** [comment]
Thank you @asadfaizi-github for initiating this thread and for managing the logistics. 
Many thanks @lumjjb for graciously hosting the event. 
I had a wonderful time; I hope the rest of the team did too. 
Closing this issue, I look forward to seeing you folks at future events.
