### ISSUE TITLE
[Proposal] Cloud Native Security White Paper Italian translation

### ISSUE THREAD

**Issue by paolomainardi** [cncf/tag-security#1014]
Description:  Cloud Native Security White Paper Spanish translation
Similar to https://github.com/cncf/tag-security/issues/470, https://github.com/cncf/tag-security/issues/509, https://github.com/cncf/tag-security/issues/576

Impact: This would help the Italian community with the understanding and adoption of best practices for Cloud Native Security. This would also help the promotion of the white paper inside governmental organizations where only Italian documents are allowed.

Scope: 2 weeks (already done)

**Comment by PushkarJ** [comment]
Discussed this in the meeting. Will try to reach out to more people with shared context on language and the cloud native security space

**Comment by anvega** [comment]
Hey, @jnardiello, @leodido and @d1gital-f. We at TAG Security are looking for reviewers within the Italian-speaking community to proofread and if need be revise the text that has been translated from English to Italian. Would be huge help if you can help us circulate and amplify amongst people you know. 

The text can be found in the commit here: 

https://github.com/paolomainardi/tag-security/commit/995d8f839b669adbdcc28dda917cdd689d60f35c

@paolomainardi Could you share the text in something other than markdown that lends itself to better readability for everyone?

**Comment by paolomainardi** [comment]
Thanks @anvega and hi to all Italian folks here, nice to meet you here as well :)

We should have a Google doc too, it diverted a bit from the markdown, mainly for the formatting and some broken links here and there.

You can access it here: https://docs.google.com/document/d/1KCN1YEOHqA7cOmsxL0YTM_0OOBjz85KzYLMIU-WZD10

**Comment by leodido** [comment]
Count me in!

**Comment by jnardiello** [comment]
Happy to help. I will run an initial review during the weekend, I am confident @paolomainardi (👋🏼👋🏼) already did an excellent job. Will report here in a couple days 😊

**Comment by mrcdb** [comment]
I've done some initial review already, but happy to take another look :+1:

**Comment by paolomainardi** [comment]
Hi everyone, just updated the google drive link (it was a wrong one), posting here as well: https://docs.google.com/document/d/1xKZtUkYHD3KDWrE2cIr2I8fVnjMePdhuH7uR3ZbfH6c

**Comment by mbuccarello** [comment]
Hi, @paolomainardi  @anvega we started an internal review of the document, we will keep you posted about our work review. We found some improvement areas and I hope soon to share some feedback.

**Comment by paolomainardi** [comment]
thanks, @mbuccarello great! As I said before remember to propose the changes on the MR instead of the google docs.
