### ISSUE TITLE
[Suggestion] New project security guide

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#1022]
Description: Creation of a simple security guide for brand new cloud native projects on contribute.cncf.io .  This guide should be pretty simple and cover reasonable security expectations, configurations, and docs a new project should have and about when they should have it.  **We've provided existing resources there on recommended templates and files, however it would be beneficial to provide a guide alongside those templates and resources.**

Impact: Security TAG has several guides and papers out that cover a variety of topics, but we don't have anything that covers a brand new project starting out. We can't reasonably hand over the cloud native security whitepaper and say "do these things" because they wont be mature enough to take them all on (and the audience is different). Creating this guide can establish achievable milestones for new projects as they grow in maturity - setting them up for success.

Scope: Things I'd like to see in a contribute.cncf.io guide like this:
- Maintainer Account security, strong passwords, 2FA/MFA
- branch protection
- PR review enforcement
- commit signing
- OpenSSF best practices badging (to include desired badging level, i.e. passing by XXX, silver before your first release (or some other timeframe or level)
- security.md
- handling security issues
- performing the self-assessment

Additional info:
- existing papers should be leveraged and explanations/ reasoning simplified
- Milestones should be achievable and build on one another.
- [existing security files from this group](https://github.com/cncf/tag-security/tree/main/project-resources) should be referenced.

Draft outline: [Security guidelines for new projects](https://docs.google.com/document/d/1opIY1ZMlf_qDx_zwt4LgbLDTMokE7H_gH1MC1Qyv3O4/edit#)

**Comment by TheFoxAtWork** [comment]
updated the issue with the intended destination.

**Comment by lumjjb** [comment]
@szh would you be interested in leading this effort?

**Comment by szh** [comment]
@lumjjb I'd be happy to but I don't have a ton of capacity right now. If someone else wants to do it and has more time I won't stop them, but if nobody else steps up I'm happy to work on it.

**Comment by ragashreeshekar** [comment]
I created a rough outline for this guide with references to the relevant material, adding here so folks can chime in. 
[Security guidelines for new projects](https://docs.google.com/document/d/1opIY1ZMlf_qDx_zwt4LgbLDTMokE7H_gH1MC1Qyv3O4/edit#)

**Comment by ragashreeshekar** [comment]
@TheFoxAtWork @lumjjb Since the base of the guide was mostly available in one form or another in the TAG publications, I have taken the liberty and completed the first draft - a light and simple guide leveraging our CNSWP, and Supply Chain guidelines. It is now open for review!

**Comment by szh** [comment]
I love this. I went and added some suggestions, mostly for grammar.

**Comment by mrcdb** [comment]
@ragashreeshekar great job, I have added a few minor suggestions

**Comment by JustinCappos** [comment]
I've had a chance to go through this, add some comments / suggestions, etc. and I have a basic observation.  This seems to be pretty duplicative with the OpenSSF Best Practices (which is obviously referenced in the document) in many ways.  

Just as a thought exercise, I'm wondering what the likely difference would be in pointing someone at the best practices process?  Where is our niche?  Would we be better off working with @david-a-wheeler to add things that we see as gaps to the OpenSSF Badging project instead?

**Comment by ragashreeshekar** [comment]
Thanks for sharing it @JustinCappos. @TheFoxAtWork could share her thoughts on the suggestion of creating this guide. 
I think OpenSSF best practice project covers several categories including but not limited to security, and newer projects would need some guidance and maturity to attain the passing state. This guide in my humble opinion, has cherry-picked some of the guidelines dedicated to securing new projects, and presented in a manner that is iteratively achievable using the work that the TAG has accomplished (whitepapers, templates etc). and acts as a precursor to the passing criteria of the OpenSSF. 

That said, working with OpenSSF to bring about such guidance for budding initiatives sounds like a good plan to me.

**Comment by TheFoxAtWork** [comment]
@ragashreeshekar I've reviewed the document and provided comments, this is a lot of great information to compliment the existing resources we have on contribute.cncf.io.  Many of my comments are about restructuring the information to conform with a guide for that site.

@JustinCappos the intent for this was to push the content to contribute.cncf.io for maintainers as that is the "front door" for new maintainers and contributors to get involved in contributing within the foundation. It should reference and compile existing resources on a variety of these topics, with some lightweight explanations to showcase why these things are recommended and the value they can provide projects.

**Comment by JustinCappos** [comment]
> @JustinCappos the intent for this was to push the content to contribute.cncf.io for maintainers as that is the "front door" for new maintainers and contributors to get involved in contributing within the foundation. It should reference and compile existing resources on a variety of these topics, with some lightweight explanations to showcase why these things are recommended and the value they can provide projects.

Okay, I think this restructuring would make sense.  I do think that right now it's a bit duplicative and this would help to correct this.

**Comment by faisalrazzak** [comment]
@ragashreeshekar I've reviewed and provided my feedback. My view is that we should be more prescriptive in the document as we're providing guidelines. Plus, we should try to be in sync with CNCF Security Tag whitepapers and OpenSSF Badge Programme.

**Comment by ragashreeshekar** [comment]
Thanks for sharing your opinion @faisalrazzak, I responded to your comments inline a couple of weeks ago. Summarizing it here - This guide is based on the TAG whitepapers with ones we think are essential to begin with and can be built upon to attain higher maturity, and you can find the prescriptions in the 1.1, 1.2 and 1.3 sections. To account for the dynamic nature of updates and avoid duplicate efforts, I have provided the links to source documentation which then provides step by step instructions. 

Regarding the comment against use of passwords, I agree with you, however, SSH, tokens etc. based logins are best suited for command-line and similar operations, however, to be inclusive of code intensive and non-code intensive projects alike (ex: TAG Security, Lexicon, end user experience, contributor experience, Docs projects) or for folks who prefer UI, the use of unique and strong credentials is suggested, along with other recommended methods. 

Unfortunately, GitHub.com only supports password-based methods primarily for browser-based logins - [https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/about-authentication-to-github], i'll include this context.

It would help if you can be specific and elaborate what are items you think are out of sync from our whitepaper so we can look to correct it.

**Comment by mlieberman85** [comment]
Linking https://github.com/kubescape/kubescape/issues/1116 here. Kubescape is starting to look at securing their supply chain and following various best practices around securing their project.

**Comment by ragashreeshekar** [comment]
PR has been raised to incorporate this work in contribute.cncf.io repo. 
Our sincere thanks for all the contributors and reviewers. 
I will update how it progresses in the next few weeks.

**Comment by ragashreeshekar** [comment]
This work is now published! Kudos to all the folks who contributed to this initiative! 
Link to the publication - https://contribute.cncf.io/maintainers/security/security-guidelines/
