### ISSUE TITLE
[Suggestion] Create a single page of the resources and publications produced by STAG

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#1026]
Description: I get asked a lot is there a single page that contains links to all the works produced by the STAG.  Every time i need to hunt through the repo to find them and each time i know i'm missing some.

Impact: significantly reduce the Level of Effort by community members in discovering cloud native security publications. It currently requires a community member that has been around through all those publications to pull them together, as we experience turnover and age-off in the knowledge of our community members, we will lose visibility into these works' existence.

Scope: medium - create a PR that captures the below links with a short description of each and take a cursory pass through closed issues with related tags and the content format links (markdown | PDF )

Additional info:

- https://github.com/cncf/tag-security/raw/main/supply-chain-security/supply-chain-security-paper/CNCF_SSCP_v1.pdf
- https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/secure-supply-chain-assessment.md
- https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/sscsp.md
- https://github.com/cncf/tag-security/raw/main/supply-chain-security/secure-software-factory/Secure_Software_Factory_Whitepaper.pdf
- https://www.cncf.io/wp-content/uploads/2022/06/CNCF_cloud-native-security-whitepaper-May2022-v2.pdf
- https://github.com/cncf/tag-security/blob/main/security-lexicon/cloud-native-security-lexicon.md
- https://github.com/cncf/tag-security/tree/main/usecase-personas
- https://github.com/cncf/tag-security/tree/main/policy
- https://github.com/cncf/tag-security/blob/main/security-whitepaper/secure-defaults-cloud-native-8.md
- https://github.com/cncf/tag-security/blob/main/cloud-native-controls/phase-one-announcement.md

**Comment by szh** [comment]
It would be really useful to have such a list for the [talk](https://cloudnativesecurityconna23.sched.com/event/1FV01/tag-security-cloud-native-security-whitepapers-overview-shlomo-zalman-heigh-cyberark?iframe=no) at the upcoming SecurityCon. I might have time to put something together while preparing that.

**Comment by ragashreeshekar** [comment]
Thanks for highlighting this, Emily.
Linking another issue https://github.com/cncf/tag-security/issues/110 I had worked on the curation. 
Contents: https://github.com/cncf/tag-security/issues/110#issuecomment-1166994426

Other relevant issues that would addressed with this https://github.com/cncf/tag-security/issues/827

@szh You can use this as the reference for building the publications page.
I would also suggest adding the following:
- CNSWP Portugese - https://github.com/cncf/tag-security/blob/main/security-whitepaper/v1/cloud-native-security-whitepaper-brazilian-portugese.md
- CNSWP Chinese - https://github.com/cncf/tag-security/blob/main/security-whitepaper/v1/cloud-native-security-whitepaper-simplified-chinese.md
- Cloud Native Security Controls Catalog - https://github.com/cncf/tag-security/blob/main/cloud-native-controls/phase-one-announcement.md
- Security assessment we have done as well. 
> - Buildpacks - https://github.com/cncf/tag-security/tree/main/assessments/projects/buildpacks
> - Cloud Custodian - https://github.com/cncf/tag-security/tree/main/assessments/projects/custodian
> - Harbor - https://github.com/cncf/tag-security/tree/main/assessments/projects/harbor
> - In-toto - https://github.com/cncf/tag-security/tree/main/assessments/projects/in-toto
> - Keycloak - https://github.com/cncf/tag-security/tree/main/assessments/projects/keycloak
> - Kyverno - https://github.com/cncf/tag-security/tree/main/assessments/projects/kyverno
> - OPA - https://github.com/cncf/tag-security/tree/main/assessments/projects/opa
> - Spiffe-Spire - https://github.com/cncf/tag-security/tree/main/assessments/projects/spiffe-spire

**Comment by TheFoxAtWork** [comment]
Yay!! Thank you @ragashreeshekar !

**Comment by ragashreeshekar** [comment]
@TheFoxAtWork Please find the Publications at https://github.com/cncf/tag-security/blob/main/PUBLICATIONS.md. 
Feel free to reopen if the issue if anything else needs to be added.

**Comment by TheFoxAtWork** [comment]
Looks great!!! Thanks so much!!
