### ISSUE TITLE
[Security Review] KEDA

### ISSUE THREAD

**Issue by tomkerkhove** [cncf/tag-security#1030]
Project Name: KEDA

Github URL: [kedacore/keda](github.com/kedaorg/keda)

CNCF project stage and issue (NA if not applicable): Incubation, with open proposal to graduate to Graduation (https://github.com/cncf/toc/pull/925)

Security Provider: no (e.g. Is the primary function of the project to support the security of an integrating system?)

- [ ] Identify team
   - [ ] Project security lead
   - [ ] Lead security reviewer
   - [ ] 1 or more additional reviewer(s)
   - [ ] Every reviewer has read [security reviewer guidelines](https://github.com/cncf/tag-security/blob/main/assessments/guide/security-reviewer.md) and stated declaration of conflict
   - [ ] Sign off by 2 chairs on reviewer conflicts
- [ ] Create slack channel (e.g. #sec-assess-projectname)
- [ ] Project lead provides draft document - see [outline](https://github.com/cncf/tag-security/blob/main/assessments/guide/joint-review.md)
- [ ] "Naive question phase" Lead Security Reviewer asks clarifying questions
- [ ] Assign issue to security reviewers
- [ ] Initial review
- [ ] Presentation & discussion
- [ ] Share draft findings with project
- [ ] Assessment summary and doc checked into /assessments/projects/project-name (require at least 1 co-chair approval)
- [ ] CNCF TOC presentation (if requested by TOC)

**Comment by TheFoxAtWork** [comment]
@tomkerkhove thank you so much for submitting this issue!  Since KEDA has applied for graduation, the project should seek a security audit through the Service Desk, as the final audit will supersede the security review. I would recommend - if the project is interested - request a security pal to assist with a lightweight threat model prior to the audit.

@lumjjb @achetal01 @sublimino  this is okay to be closed.

**Comment by tomkerkhove** [comment]
We have already requested a security audit which was completed and [published on CNCF blog](https://www.cncf.io/blog/2023/02/02/results-of-the-keda-security-engagement/) but this came up as a requirement for the proposal.

I'll circle back on the proposal and let them know; thanks.

**Comment by tomkerkhove** [comment]
No worries and thanks for following up - I was going to do the same after we complete our proposal :)
