### ISSUE TITLE
[Minor] SSF: duplication of copytext

### ISSUE THREAD

**Issue by jadeboer** [cncf/tag-security#1032]
Hey,

See the following commit and its comment which sparked this issue: https://github.com/cncf/tag-security/commit/b3d2711c6dee3959ebc7ea756fce78f5edaae4dc

There appears to be duplicated copy in the SSF publication. On page 14, stage 3: trigger pipeline, after the actors dot-point list there is a paragraph of text describing how a pipeline may be triggered to begin execution. This appears to be identical to the next stage, stage 4: ingest source for project.

This feedback was reviewed by @mlieberman85 (https://github.com/cncf/tag-security/commit/b3d2711c6dee3959ebc7ea756fce78f5edaae4dc#commitcomment-99711725) - his suggestion is that copy should be as follows:

> _After a build is triggered, the next step is ingesting the code for the project. This is usually a call to a source code control system to pull down a specific commit. It then hands the code over to downstream pipeline tasks via shared storage for things like the build stage._

I hope this helps - cheers

**Comment by lumjjb** [comment]
I will open up a ticket with the CNCF writing team to get a new copy out with this resolved.

**Comment by lumjjb** [comment]
Tracking Ticket number: CNCFSD-1619

**Comment by anvega** [comment]
pull/1082
