### ISSUE TITLE
cncf/artwork needs updating

### ISSUE THREAD

**Issue by craigbox** [cncf/tag-security#1039]
https://github.com/cncf/artwork/blob/master/examples/other.md#sig-security has artwork for "SIG", not "TAG" Security.

The v2 whitepaper has a "TAG Security" logo in the corner, so for my purpose in referring to the group today I ended up screenshotting the front page.

Does anyone have the updated artwork with the new name?  If not, and you would like, I'm happy to coordinate with CNCF service desk on getting them made and uploaded.

**Comment by ragashreeshekar** [comment]
Thanks @craigbox for notifying us. 
We have updated our branding and it’s available at https://github.com/cncf/tag-security/tree/main/design. We will need to update it at cncf/artwork. 

Thank you for offering to coordinate with CNCF service desk to get it resolved, please let us know if you need any information and I’ll be able to assist you with it.

**Comment by craigbox** [comment]
I'm assuming we want versions that say "TAG Security" instead of "Cloud Native Security". 
I've raised https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1623 and will update as it comes through.

**Comment by ragashreeshekar** [comment]
Security TAG’s branding decision is that the work of the group is identified as cloud native security, the raccoon logo identified it as a TAG product without saying Security TAG. 

So, the artifacts in this repository (https://github.com/cncf/tag-security/tree/main/design) is in fact the latest one, and we need this design to be reflected in the CNCF artwork. I hope I was able to clarify. 

CC: @TheFoxAtWork

**Comment by craigbox** [comment]
I don't follow.  Have a look at https://github.com/cncf/artwork/blob/master/examples/other.md#sig-security; start there and scroll down.  There are a bunch of logos for TAGs there.  (This came about because I wanted a way to refer to TAG Security in a presentation, not the concept of Cloud Native Security in general.)

(See also the use of a "TAG Security" logo in [the whitepaper PDF](https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/CNCF_cloud-native-security-whitepaper-May2022-v2.pdf).)

**Comment by lumjjb** [comment]
We made the decision for branding back when we had the name change to just have Cloud Native Security (see [artwork](https://github.com/cncf/tag-security/tree/main/design)). This is also the logo we use for hoodies/swag, so it seems like the following needs to happen:

- create a PR against https://github.com/cncf/artwork/blob/master/examples/other.md#sig-security to update it to the designs from https://github.com/cncf/tag-security/tree/main/design

Does this help? And would you by any chance be able to help make that PR against `cncf/artwork` repo?

**Comment by craigbox** [comment]
https://github.com/cncf/artwork/pull/401

You don't have "all black" and "all white" versions of the artwork, so I haven't added them. I opened up a Service Desk request but was told "TAG requests should work through the TAG first, the leads can file on behalf of that group."

**Comment by ragashreeshekar** [comment]
Thanks for your efforts and letting us know @craigbox. I have opened a Service Desk request update the artwork. Will keep this threat updated with the proceedings.

**Comment by ragashreeshekar** [comment]
PR opened at CNCF/artwork to address this issue
Reference - https://github.com/cncf/artwork/pull/406

**Comment by anvega** [comment]
https://github.com/cncf/artwork/pull/401 merged

**Comment by craigbox** [comment]
For the record, this is how it renders now:

https://github.com/cncf/artwork/blob/master/examples/other.md#tag-security

There's still no monochrome versions, and to be honest "Cloud Native Security" doesn't help me identify "TAG Security" in a presentation; there's no reference to the fact this is a _group_, rather than a _concept_.
