### ISSUE TITLE
[Proposal] Cloud Native Security White Paper Spanish translation - v2

### ISSUE THREAD

**Issue by krol3** [cncf/tag-security#1041]
Description: Cloud Native Security White Paper Spanish translation V2

Following the [discussion about upgrade the Spanish translation to v2](https://github.com/cncf/tag-security/pull/1040#issuecomment-1445151905), this issue wants to track the advance of this initiative. 
 
Impact: This would help the Spanish community with the understanding and adoption of best practices for Cloud Native Security. This would also help the promotion of the white paper inside governmental organizations where only Spanish documents are allowed.

Scope: White Paper [v2](https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/CNCF_cloud-native-security-whitepaper-May2022-v2.pdf)

STAG rep: @lumjjb 
Project Lead: @krol3 
This translation will be done with the support of the Kubernetes docs-es community

**Comment by anvega** [comment]
pull/1040

**Comment by krol3** [comment]
@anvega  this issue is to track the new translation v2, can you open it? , you can close the issue about v1: https://github.com/cncf/tag-security/issues/576

**Comment by anvega** [comment]
Checking in. Is translation work for v2 still happening?

**Comment by anvega** [comment]
Hey, it's been a while since this was last update. Going with the policy outlined under governance/process.md we're closing issues that haven't had meaningful activity in 90 days. If you complete the translation, please file it as a PR for merging at point.

**Comment by krol3** [comment]
Hi @anvega we will try to close this issue. Thanks for the reminder
