### ISSUE TITLE
[Presentation] Zero Trust for Cloud Native platforms

### ISSUE THREAD

**Issue by achetal01** [cncf/tag-security#1042]
Title: What is the title of your presentation?
Zero trust for Cloud Native Platforms
Speakers: Mariusz and Kishore (project Leads)

Description: Its about the work the working group is doing to explain Zero trust for Cloud Native technologies in a White paper.

Time: 30-45 mins

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page.

TO DO
- [ ] TAG Representative
- [ ] Schedule date - 8th March 2023
- [ ] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by anvega** [comment]
Paper draft: https://docs.google.com/document/d/1K_k3ddnFMIhraoqMuXQo7BUWwo8pR2UPd6ZeIJZt7R8/edit  
ZeroTrust Meeting notes:
https://docs.google.com/document/d/1ruQEbGFJDvp3AAj1U4kvp1MR2sfLnw_2JxNbwky_enA/edit?usp=sharing  
ZeroTrust Team Slack channel: https://cloud-native.slack.com/archives/C0444N0KYQJ  
CloudNative Conference - Zero Trust Panel (recording): https://youtu.be/TJbw4mgILhM  
Slides: https://drive.google.com/file/d/19KtxIb9-g__4FoBshaxZZUtgp4pfyoG2/view?usp=share_link
