### ISSUE TITLE
[Suggestion] one wrong picture in the CNCF security whitepaperV2

### ISSUE THREAD

**Issue by jhliucquZTE** [cncf/tag-security#1043]
in Page P18,  use the distribute picture of Cloudnative security whitepaper V2, which should be deploy.

**Comment by PushkarJ** [comment]
Thank for you for sharing. This has been fixed in markdown https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/cloud-native-security-whitepaper.md and will be corrected in v3 officially

**Comment by PushkarJ** [comment]
Related to #1044
