### ISSUE TITLE
Cloud Native Security Whitepaper v3

### ISSUE THREAD

**Issue by savitharaghunathan** [cncf/tag-security#1044]
**Description: what's your idea?**
---
Original security whitepaper (https://github.com/cncf/tag-security/issues/138) was published in Nov 2020, followed by version 2 (https://github.com/cncf/tag-security/issues/747) in May 2022. Since then we have received a lot of community feedback for improvements and new topic addition. So this issue is an attempt to carve out everything in one place and let a contributor take up the Project Leader role for this next version.
Impact: Describe the customer impact of the problem. Who will this help?  How will it help them?

**Scope:** 
---

- https://github.com/cncf/tag-security/issues/906
- Serverless Security White Paper - Cloud Native Security Best Practices  #546
- Retrospective for v2 (similar issue for v1 for context: https://github.com/cncf/tag-security/issues/480 )
- More details on the process of publishing TAG Security whitepapers: https://github.com/cncf/tag-security/blob/main/governance/publishing-deliverables.md

**METADATA**
---

- [ ]  Security TAG Leadership Representative: @PushkarJ
- [ ]  Project leader(s): @savitharaghunathan @aks-alokraj
- [ ]  Project Members: Please comment if you are interested to join
- [ ]  Slack Channel: #tag-security-whitepaper
- [ ]  Meeting Time & Day: TBD
- [ ]  Meeting Notes (link): https://docs.google.com/document/d/1jat4romjgusGDmcjFxauw19kcDFORLnAAMRaQ5uMshY/edit
- [ ]  Retrospective for v3

---
## Project Schedule

|  TODO      |  Milestone  |  Estimated time  | Actual date |
|---------   |   ---------- |  --------------- | ------------ |
|   | Audience, Goals, & refining scope     | 1 week	|  |
|   |     Tasking Assignment   |   1 week	   | |
|   |     Content Rough-in   |    2-3 weeks  | |
|   |   Collaborative Review     |    2 weeks  | |
|   |      Executive Summary and content wrap up  |   2 weeks	   | |
|   |    Narrative Voice    |     1-2 weeks | |
|   |      Final Group Review   |   1 week	   | |
|   |   Community Review / Public comment adjudication     |    2-3 weeks  | |
|   |   CNCF publishing engagement     |  ~2-3 weeks    | |
|   |     Addition to the repo	    |   1 week   | |
|   |   Blog post and publishing coordination     |    2-3 weeks  | |

**Comment by mnm678** [comment]
Closing this as inactive. Happy to re-open if anyone wants to take it on.
