### ISSUE TITLE
Add compliance work to Roadmap

### ISSUE THREAD

**Issue by lizrice** [cncf/tag-security#105]
We should add something about the work on compliance to the [SAFE roadmap](https://github.com/cn-security/safe/blob/master/roadmap.md).  For example, perhaps under item 4, "Identify", we could add something like "Identify how different CNCF projects can be configured and used to meet different [compliance](https://docs.google.com/document/d/1LKCy9wIi8zomH_mbIwGHTd1Xnq1zwyruG4E2L0LGzjM/edit#heading=h.bdfarsq1i7hb) objectives, highlighting any gaps". Wdyt?

**Comment by ficcaglia** [comment]
Just my .02, I actually think of regulatory compliance as a separate domain/concern apart from secure access or technical policy controls/features.  It orchestrates and considers all the human activities surrounding and interacting with a software system.

Regulatory compliance can often be accomplished with manual human and paperwork processes (for good or ill) outside the software controls, whereas security is the interaction of various attributes and decisions concretely defined and embodied in the system architecture, design, code and behavior.  

They certainly can and should reinforce each other, but I think they should be decoupled explicitly and managed separately.   Put another way, I wouldn't want to design the safety and security of software with regulatory requirements as the primary goal; nor would I want to declare regulatory compliance by only mapping a set of security features/configurations to specific regulatory requirements without considering all the human workflows surrounding the system.

A mapping between security features/intents vs specific regulatory compliance requirements is a start and a helpful roadmap. My recommendation for scope would be to provide a common vocabulary of terms across various features and intents that can be cross mapped to all the many different regulatory frameworks (most of which are not container aware today!)  That said HITRUST has mapped to CSA and I have done some work to map PCI and HIPAA.

**Comment by TheFoxAtWork** [comment]
This is reflected on the Roadmap & planning FY21-22, this issue is being closed
