### ISSUE TITLE
[Suggestion] Software Supply Chain Security Rubric

### ISSUE THREAD

**Issue by nishakm** [cncf/tag-security#1050]
This is related to https://github.com/cncf/tag-security/issues/987

The Software Supply Chain Policy working group reached consensus that there are two problems to tackle 1. Provide a general assessment of the state of software supply chain security as it pertains to cloud native development 2. Provide a rubric to score an existing software supply chain. The working group agrees that it will tackle 1. We were wondering if the CNCF controls group is the right place to tackle 2 or if it requires a new working group.

For more information about the discussion, please see [here](https://docs.google.com/document/d/1MTM782nluFl4_ybG-fXHmRT2k4bPN18ifdzpUltQQCw/edit#heading=h.rbsailrgmvyo)

cc: @lumjjb @jkjell @fkautz @mlieberman85

**Comment by lumjjb** [comment]
we are going to chat about this in the leads meeting to see if this is something that could be a next project on the horizon on the controls group, or decide where it should go in the project timeline. Hang tight for now and we'll get back on this - probably within 2 weeks.

**Comment by lumjjb** [comment]
We had a chat about this, and wanted to enquire further on what you had in mind. 

we were looking at the [spreadsheet](https://docs.google.com/spreadsheets/d/1GUohOTlLw9FKUQ3O23X7ypvJLXN-B3veJGe6YE6JYfU/edit#gid=1938257679) put out by the controls working group, and also looking at the [NIST SSDF ](https://csrc.nist.gov/Projects/ssdf)(and the soon to come OMB SSDF Attestation forms). 

Could you help give us a bit more details in the context of these to help us understand a bit better at a detailed granularity of what you're looking for? Thanks!

**Comment by jkjell** [comment]
This looks like it could also be related:
https://sot.mitre.org/framework/system_of_trust.html

**Comment by anvega** [comment]
👋 @nishakm - Is this still something you'd like to pursue or not anymore at this point? The team could use the clarification being asked above.

**Comment by anvega** [comment]
Interest in this proposal appears to have dropped as evidenced by the lack of response. Closing for now but feel free to reopen once there is renewed interest.

**Comment by nishakm** [comment]
Hi @anvega! It turns out that some OpenSSF groups are addressing this issue. So this can remain closed for now.
