### ISSUE TITLE
[Suggestion] Make UK vs US English usage consistent or i18n

### ISSUE THREAD

**Issue by mlieberman85** [cncf/tag-security#1052]
Description: There is a problem where folks are getting confused between the different ways words are spelled and unsure if for example `artefact` is the same as `artifact`. This is especially true for folks where English is not their first language. There are a couple of potential solutions to this:

- Be consistent in naming.
- Output artifacts in both UK and US English via internationalization.

I know we've had a general rule that the leads of a writing project get to choose UK vs. US English, however I think it's confusing to consumers.

Scope: I don't think this will take particularly long especially if we go for the second option. We could easily have a script that finds and replaces the common spelling differences and have two artifacts/artefacts. One in US English, the other in UK.

**Comment by anvega** [comment]
@mlieberman85 Are either of the solutions being pursued or has the usage suggestion been abandoned?

**Comment by szh** [comment]
I think it would be simplest to simply stick to US styles.

**Comment by anvega** [comment]
We can stick with a consistent style guide moving forward but looks like we wont be regenerating the two supply chain papers that make use of UK english. Should anyone choose to address this, please open a PR with those assets.
