### ISSUE TITLE
[Project] Cloud Native Security White Paper v2 Chinese Translation

### ISSUE THREAD

**Issue by rootsongjc** [cncf/tag-security#1055]
We have translated the White Paper v1 into Chinese three years ago. See https://github.com/cncf/tag-security/pull/471 I was one of the leads of that task. Now I'd like to initiate a new round of Chinese translation for v2.

If you would like to join me, please reply +1 below.

Impact: Update the white paper to the latest version.

Scope: I need some members to translate for about two weeks.

TO DO
- [x] Security TAG Leadership Representative: @PushkarJ 
- [ ] Project leader(s):
- [ ] Project Members:
- [ ] _Fill in addition TODO items here so the project team and community can see progress!_
- [ ] Scope 
- [ ] Deliverable(s)
- [ ] Project Schedule
- [ ] Slack Channel (as needed)
- [ ] Meeting Time & Day:
- [ ] Meeting Notes (link)
- [ ] Meeting Details (zoom or hangouts link)
- [ ] Retrospective

**Comment by yzyunzhang** [comment]
+1

**Comment by PushkarJ** [comment]
Great to see this. Happy to be TAG representative for this with my Tech Lead hat on

**Comment by jinjiaKarl** [comment]
+1

**Comment by york-shen** [comment]
+1

**Comment by rootsongjc** [comment]
Update: At present, the Chinese translation of the full text has been completed and is under review.

**Comment by ashutosh-narkar** [comment]
Is there an open PR folks can review?

**Comment by rootsongjc** [comment]
@ashutosh-narkar Not yet. We will review the translation internally and revise it before we summit a PR.

**Comment by rootsongjc** [comment]
We have finished the translation but need some help on reviewing. [Here](https://docs.qq.com/doc/DYWpKRnh3dkJvQ2xZ?scene=d7ff2f0d796be9dcdb22fadfiDnJq1) is the Tencent Docs we used to keep the translation. Touch me if you want to help to review the translation with [WeChat](https://jimmysong.io/contact/).

**Comment by PushkarJ** [comment]
@rootsongjc is it possible to open a PR on the TAG Security repo so it is easier to review ?

**Comment by rootsongjc** [comment]
@PushkarJ Yes, let me sort it out and submit.

**Comment by rootsongjc** [comment]
Translation draft submitted

**Comment by anvega** [comment]
Thanks for your dedication and hard work here. The translation is now merged. 

I will initiate a ticket with the CNCF Service Desk team to produce a PDF copy of the translation. Typically a short blog post is written by the translation team to be featured in the [CNCF blog](https://www.cncf.io/blog/). It would be great if you can write one or two paragraphs to announce the translation featuring it in the blog.

**Comment by rootsongjc** [comment]
We are thrilled to announce the release of the second edition of the CNCF Cloud Native Security Whitepaper's Chinese translation. As the leader of this translation initiative, alongside several dedicated friends, we embarked on this journey in April 2023, fueled by our passion for advancing cloud native security knowledge within the Chinese-speaking community. After four months of relentless efforts and collaboration, we are delighted to present the fully translated and localized version of this essential resource.

Our translation team, comprising language experts and cloud native enthusiasts, worked diligently to ensure the accuracy and clarity of every translated sentence. Throughout this journey, we were driven by the shared vision of making this invaluable resource accessible to a broader audience of Chinese-speaking developers, architects, and security professionals.

In the spirit of open collaboration, the translated whitepaper will be made available for free on the CNCF website, ensuring that knowledge about cloud native security remains accessible to all. We encourage everyone to explore this valuable resource and contribute to the continued growth and advancement of cloud native security practices.

**Comment by PushkarJ** [comment]
@rootsongjc sorry for the delayed response. CNCF suggested to convert the markdown whitepaper to a google document if possible for publishing as CNCF designed pdf. Is that something you would be able to do for us and then share a link? Note the google document should be identical in content with markdown merged paper. 

You may use markdown to docx converter to do the same. Let us know if you need help!

**Comment by rootsongjc** [comment]
No problem. Let me convert it to PDF. @PushkarJ

**Comment by rootsongjc** [comment]
@PushkarJ  Please take a look the Chinese PDF #1107

**Comment by anvega** [comment]
Merged https://github.com/cncf/tag-security/pull/1108
