### ISSUE TITLE
Graph for understanding artifact composition (GUAC) presentation

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#1057]
Title: Graph for understanding artifact composition (GUAC) presentation

Speakers: Who will be presenting this? 

@mlieberman85 @lumjjb 

Description: 

Graph for Understanding Artifact Composition (GUAC) aggregates software security metadata into a high fidelity graph database—normalizing entity identities and mapping standard relationships between them. Querying this graph can drive higher-level organizational outcomes such as audit, policy, risk management, and even developer assistance.

GUAC is looking for a potential home in a foundation and would like to gather some feedback from different groups (both in the CNCF and OpenSSF). 

Time: How long will the presentation take? 20-30 mins

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page.

NA meetings, availability is pretty open right now.

TO DO
- [ ] TAG Representative
- [ ] Schedule date
- [ ] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by anvega** [comment]
Scheduled for 7/19
