### ISSUE TITLE
Build a Guideline for LargeOrg Security Teams

### ISSUE THREAD

**Issue by andrei821** [cncf/tag-security#106]
[Some]Security teams working within large organizations have a traditional approach when designing security requirements for newly deployed cloud native environments. Usually this traditional approach is defined by creating firewalls around applications, filtering EGRESS traffic using corporate proxy, while manually managing access rules.
Having in mind that security is paramount for most organizations, security teams prefers to reduce agility by holding on legacy processes and procedures.
I feel that a clear guideline describing basic cloud native security best practices and comparing them with the traditional aproach will have a great benefit.

**Comment by izgeri** [comment]
It might be interesting to produce a whitepaper that compares the cloud-native security landscape / the best practices that it highlights with what traditional security might look like.

**Comment by pragashj** [comment]
This is an interesting idea. By traditional, do you mean standards or
implementation (architecture)?

**Comment by ultrasaurus** [comment]
I have found this to be "traditional' as well... meaning that it's common practice. Perimeter-based security is how people think about network security, and provides a somewhat false feeling of safety in our modern world (perhaps independent of cloud), but in any case, when you have physical cables and can unplug them to create a perimeter, its quite different than in cloud-native systems where its a policy and software-enforced concept.

**Comment by TheFoxAtWork** [comment]
closing - CNSWP exists and discusses modern security.  Additional books and docs exist in the community that reflect traditional v modern security.
