### ISSUE TITLE
[Security Review] Flatcar

### ISSUE THREAD

**Issue by miao0miao** [cncf/tag-security#1066]
Per discussion regarding flatcar due diligence on the 19th April 2023 with @mauilion @nikhita I opened this security review request. 

Project Name: Flatcar

Github URL: https://github.com/flatcar/Flatcar 
https://github.com/cncf/toc/pull/991 (applying for incubation)

CNCF project stage and issue (NA if not applicable):

Security Provider: no

- [x] Identify team
   - [X] Project security lead (Danielle Tal and Thilo Fromm)
   - [X] Lead security reviewer @JustinCappos 
   - [X] 1 or more additional reviewer(s) @ragashreeshekar @mnm678 @sublimino   Observers: @krishnakv, @lcostea 
   - [X] Every reviewer has read [security reviewer guidelines](https://github.com/cncf/tag-security/blob/main/assessments/guide/security-reviewer.md) and stated declaration of conflict
   - [x] Sign off by facilitator on reviewer conflicts
- [X] Slack channel: [#sec-assess-flatcar](https://cloud-native.slack.com/archives/C05DD96B3UG)
- [X] Project lead provides [draft document ](https://docs.google.com/document/d/1rj9HpBLskgc1FUt1LEeXmMGXdHVEY6qeQt1yocBLmi8/)
- [x] "Naive question phase" Lead Security Reviewer asks clarifying questions
- [x] Assign issue to security reviewers
- [x] Initial review
- [x] Presentation & discussion
- [x] Share draft findings with project
- [x] Assessment summary and doc checked into /assessments/projects/project-name (require at least 1 co-chair approval)
- [ ] CNCF TOC presentation (if requested by TOC)

**Comment by ragashreeshekar** [comment]
I'd like to join as a reviewer. 
No conflicts from my end.

**Comment by sublimino** [comment]
Thanks for the discussion today @miao0miao and team!

We look forward to your initial 30m presentation including the topics in the [meeting notes](https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/edit#heading=h.xacwkke6od4g) to feed into Q&A and find further areas for discussion.

From there we'll identify what the TOC want from an OS-level review, and find the most effective way to generate a lightweight threat model to deliver the highest impact and value for users and your team 🙏

**Comment by JustinCappos** [comment]
Looking forward to getting this started.  We need a few more folks to get this going.  We will recruit more reviewers in the TAG Security meeting.  

Do you have a self assessment document or similar for us to start on?

**Comment by JustinCappos** [comment]
There are two ways you could go here.  One would be to go through the full process which requires you to do a self assessment ( See these guides: https://github.com/cncf/tag-security/blob/main/assessments/guide/self-assessment.md and https://docs.google.com/document/d/1L6AAbzkVHkd2ODGv31Y-UJVKOjq2a0qxdZ5IIOQBcYo/edit# ).  The other would be to do the lightweight threat modeling process ( https://github.com/cncf/tag-security/issues/903 ).  

@sublimino should probably weigh in about what is more appropriate for your group.  However, if you look at the self assessment and have not already done much of this work, and your project's security is not important in the broader ecosystem, you may be able to get by with the lighter process.

**Comment by t-lo** [comment]
@JustinCappos Thank you for the pointers! Very helpful indeed. The security assessment book specifically is an awesome resource! I'll review both the self assessment and the thread modelling process in preparation to our presentation on June 14th. Let's briefly align after the presentation on how to proceed.

**Comment by t-lo** [comment]
Intermediate update: We moved the Flatcar technical overview / security presentation to the June 21st meeting as it did not fit into today's (June 14th) meeting.

**Comment by sublimino** [comment]
Thanks for adding the note to the meeting agenda, to confirm it's in the EMEA timezone on June 21st at 1pm London. Looking forward to it!

**Comment by krishnakv** [comment]
I would like to volunteer for this review, please. I have no soft or hard conflicts to report.

**Comment by t-lo** [comment]
As discussed in the TAG Security meeting, our WiP self-assessment doc is [here](https://docs.google.com/document/d/1rj9HpBLskgc1FUt1LEeXmMGXdHVEY6qeQt1yocBLmi8/edit).
It's currently in draft and we're still working on the doc.
We'll get back to you as soon as we're done to get initial feedback, and will convert it to Markdown and file a PR when it is ready.

**Comment by JustinCappos** [comment]
Adding myself as lead security reviewer.  I do not have a conflict.

**Comment by mnm678** [comment]
I would like to volunteer to participate as a reviewer. I have no hard or soft conflicts.

**Comment by sublimino** [comment]
Adding my name as a reviewer.

Soft conflicts: I know some of the team and have used the project since CoreOS in 2015, no current usage.

I have no hard conflicts.

**Comment by JustinCappos** [comment]
I'm signing off that there are no conflicts by any of the reviewers and that all have posted their statements.

**Comment by JustinCappos** [comment]
@t-lo I took a look at your assessment document and it's a good start.  Please let us know when it is done.  We have the preliminary team for this assessment all set up.  You have a little time as we work with the Pixie team on their review, but we will be blocking on this being completed in two weeks or so.

**Comment by t-lo** [comment]
Thank you for the feedback @JustinCappos ! I expect to finish the doc later this week so there will even be a little headroom for reviewers to have a first pass before the TAG Security meeting on July 5th.
I will make sure to keep you posted.

**Comment by lcostea** [comment]
is there space for an additional observer? I watched the youtube presentation of flatcar (the 21st June meeting) and I also read the security assessment book, so looking forward to observe it.

**Comment by JustinCappos** [comment]
> is there space for an additional observer? I watched the youtube presentation of flatcar (the 21st June meeting) and I also read the security assessment book, so looking forward to observe it.

Yes.  Please indicate your conflicts of interest.

**Comment by lcostea** [comment]
Sure, no conflicts on my end. Thanks

**Comment by t-lo** [comment]
Hello folks,

We've completed the self-assessment, please have a look at your convenience. Questions and feedback are very welcome!
The doc is on Google Docs for now to ease the feedback cycle. As soon as we're all happy with the doc I'll file a PR with the markdown version.

Doc: https://docs.google.com/document/d/1rj9HpBLskgc1FUt1LEeXmMGXdHVEY6qeQt1yocBLmi8/edit

We'll be at Wednesday's TAG Security meeting for Q&A re: our Flatcar presentation two weeks ago and to discuss the self-assessment.

Thank you everybody for helping with this process!

**Comment by JustinCappos** [comment]
@t-lo I've gone through the naïve questions phase and made a bunch of comments.  The document is a very good start (I like the threat model section especially), but is missing a lot of detail that will be needed by reviewers.  Can you make a pass and integrate answers to my comments in the text?  (Feel free to close the comment if you know you've addressed it, or reply in the comment to ask if you are unsure.)  

Also, please take a fresh look over the document for similar comments / issues I didn't flag.  I am sure I have missed some as I was going through (especially later in the document).

**Comment by ahrkrak** [comment]
@miao0miao I think "naive questions phase" and "assign issue to security reviewers" are complete (? please confirm) -- if so, maybe you could check off the list?

**Comment by t-lo** [comment]
@ahrkrak  We're still in the naive question phase until I've addressed at least Justin's feedback :sweat_smile: I'm about 2/3 done and am planning to wrap it up today.

**Comment by ahrkrak** [comment]
got it, thanks.

________________________________

**Comment by t-lo** [comment]
@JustinCappos I've rewritten most parts of the self assessment and extended the first sections in particular, addressing all your feedback. Could you please give the doc another go?
(Note that I'll be unavailable Mo-Wed next week; travelling / attending a conference. I'll be back to address new feedback starting Thursday).
Link to doc (unchanged): https://docs.google.com/document/d/1rj9HpBLskgc1FUt1LEeXmMGXdHVEY6qeQt1yocBLmi8/edit

**Comment by t-lo** [comment]
And thank you for the elaborate and detailed feedback! It's been extremely helpful to improve the document. Thank you for all the time and effort you're putting into this.

**Comment by JustinCappos** [comment]
Alright, we've completed the naive questions phase!  Reviewers ( @ragashreeshekar @sublimino @mnm678 ) and observers ( @krishnakv @lcostea ), it is time to take your notes about the project!

**Comment by t-lo** [comment]
Please note that I'll be off for the next 3 weeks but @miao0miao and @vbatts will stick around as points of contact for this time.

**Comment by JustinCappos** [comment]
Addressed via #1219 and #1220

**Comment by JustinCappos** [comment]
Thanks to the Flatcar team for all the hard work!  @t-lo @miao0miao
