### ISSUE TITLE
CNCF TAG Security - website provides TAG App Delivery information

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#1071]
I had an adopter reach out about the incorrect information in Security TAG’s website: https://tag-security.cncf.io/ as it contains information about TAG App Delivery. To avoid confusion, highly recommend resolving this with Security TAG's information to ensure individuals are being directed to the correct information, individuals, and resources.

**Comment by TheFoxAtWork** [comment]
https://community.cncf.io/tag-security/ this is also out of date, @lumjjb you should have access to make updates/changes (add folks to make updates/changes). I've since removed myself.

**Comment by mlieberman85** [comment]
Thanks! #1072 should fix this.

**Comment by anvega** [comment]
#1072 does fix this
