### ISSUE TITLE
Zero Trust Access Controls for Cloud Native Services - NIST 800-207A  Presentation and Discussion

### ISSUE THREAD

**Issue by achetal01** [cncf/tag-security#1073]
Title: NIST 800-207A

Speakers: Zack Butcher

Description: A Zero Trust Architecture Model for Access Control in Cloud-Native Applications in Multi-Cloud Environments

Time: 45 minutes plus 15 mins for Q and A

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page.

TO DO
- [ ] Aradhna Chetal
- [ ] 7th June 2023
- [ ] By opening this issue, I, ( achetal01) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by achetal01** [comment]
The date has to be changed for this. Zack is not available net week. He is available on 6/7/23

**Comment by anvega** [comment]
@achetal01 @zackbutcher Thanks for the presentation. Can you share a link to the slides that were presented?

**Comment by ZackButcher** [comment]
Hey folks here's the presentation, happy to field any questions here in the issue or via email (included in the presentation).
[Identity Based Segmentation for a ZTA - CNSC US 2023.pdf](https://github.com/cncf/tag-security/files/11771430/Identity.Based.Segmentation.for.a.ZTA.-.CNSC.US.2023.pdf)

[Here is a longer form version of this presentation from Cloud Native Security Con 2023, including my NIST counterpart Mouli.](https://www.youtube.com/watch?v=s2lIaFhkA8c)

I'll stress that the review period for 207A is ending imminently so if any has feedback or comments for the doc to please get them submitted in the next few days; email: sp800-207a-comments@nist.gov
