### ISSUE TITLE
[Project] Fuzzing Handbook

### ISSUE THREAD

**Issue by caniszczyk** [cncf/tag-security#1080]
Description: CNCF would like to initially commission a fuzzing handbook based on the fuzzing work that has been done in CNCF projects the last couple of years.

Impact: Make it easier for maintainers to learn about fuzzing and implement them in their projects

Scope: TBD

**Comment by DavidKorczynski** [comment]
@AdamKorcz and I are happy to carry here, and we've been involved with a lot of the fuzzing work across the CNCF.

**Comment by caniszczyk** [comment]
@DavidKorczynski I think the next is to present to a TAG Security meeting

@lumjjb or @sublimino can steer you in the right direction?

ideally I'd see this be its own resource like https://github.com/cncf/tag-security/tree/main/supply-chain-security/supply-chain-security-paper or maybe in the project resources section? https://github.com/cncf/tag-security/tree/main/project-resources

**Comment by DavidKorczynski** [comment]
> https://github.com/cncf/tag-security/tree/main/supply-chain-security/supply-chain-security-paper

I'd probably go for either having a section `application-security` similar to `supply-chain-security` at the top level and then put it in there while further down the line add other concepts, e.g. static analysis, or, add `application-fuzzing` as its own top-level similar to `supply-chain-security`.

**Comment by sublimino** [comment]
Hi @DavidKorczynski! Our calendar is in [this doc](https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/edit#heading=h.1tv8gumsrtbf), please choose a date to present  🙏 EMEA meetings are every two weeks at 1pm London, NA every week 6pm London (10:00am UTC-7).

**Comment by DavidKorczynski** [comment]
> Hi @DavidKorczynski! Our calendar is in [this doc](https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/edit#heading=h.1tv8gumsrtbf), please choose a date to present 🙏 EMEA meetings are every two weeks at 1pm London, NA every week 6pm London (10:00am UTC-7).

Thanks, scheduled it for 14th June

**Comment by DavidKorczynski** [comment]
@sublimino will it be only NA today or also EMEA? By the looks of it EMEA skipped last week as it's labelled US -- does that imply EMEA will also happen today?
![tagmeetings](https://github.com/cncf/tag-security/assets/657617/7a66a5ae-a167-4420-af0c-58e28320bdca)

**Comment by DavidKorczynski** [comment]
@sublimino it's not clear to me when the EMEA meeting is happening given the EMEA was not held on June 7th following the bi-weekly scheduling shown in the screenshot above. I tried entering the zoom chat now but it's asking me for an invite that I should've received by email, which I have not. Could you clarify?

**Comment by sublimino** [comment]
> @sublimino it's not clear to me when the EMEA meeting is happening given the EMEA was not held on June 7th following the bi-weekly scheduling shown in the screenshot above. I tried entering the zoom chat for 1pm London time, but it's asking me for an invite that I should've received by email, which I have not. Could you clarify?

We were previously alternative EMEA and NA, but NA has returned to every week scheduling. Today is just NA.

Apologies for the confusion around this one — I believe last week's EMEA went ahead at 1pm London. There's no invite required but there is a password linked on the main page https://github.com/cncf/tag-security#zoom-meeting-details

/cc @mrcdb

**Comment by DavidKorczynski** [comment]
Awesome, got it. Thanks @sublimino  -- I'll join for the NA tonight.

**Comment by sunstonesecure-robert** [comment]
just adding the ones I recall: OPA, CLoudCustodian, K8s CAPI...trying to get the K8s CSI done next!

**Comment by DavidKorczynski** [comment]
This was presented and discussed in todays meeting. Several good inputs and suggestions came and the high-level conclusion about next steps is @AdamKorcz and I will share a first-draft of the handbook with the TAG when it's completed. We estimate this will come in around 4 weeks.

**Comment by sublimino** [comment]
Thanks @DavidKorczynski!

As an aside @JustinCappos has invited any contribution you'd like to make to the [Security Assessment Book Draft](https://docs.google.com/document/d/1L6AAbzkVHkd2ODGv31Y-UJVKOjq2a0qxdZ5IIOQBcYo/edit#heading=h.n1q6sfgdaun5) — this will form the basis of STAG security assessment guidance, and while it's not necessary to add anything, we'd like to make the opportunity available if there's anything that stands out to you for suggestion/amendment or contribution. 

The tracking issue is #999 but it's not yet in publication despite the final comment, we're also [here on Slack](https://app.slack.com/client/T08PSQ7BQ/C04K8HKJN7Q) :pray:

**Comment by DavidKorczynski** [comment]
Thanks @sublimino ! I will take a look and revert back -- it makes sense there is some connection/reference between the two.

**Comment by anvega** [comment]
Hello @DavidKorczynski - Thought we'd check in to see where you are with the draft. Is it at a point where it's ready for us to review?

**Comment by DavidKorczynski** [comment]
Thanks for checking up @anvega -- We will need a bit more time. I'll look to share with you next week!

**Comment by DavidKorczynski** [comment]
> Thanks for checking up @anvega -- We will need a bit more time. I'll look to share with you next week!

@anvega we are almost there but will need a few more days. I'll like share early/mid next week :)

**Comment by DavidKorczynski** [comment]
@anvega we are ready to share the first draft!

It's in a google doc at the moment -- I think we'd prefer to keep it there for now and then convert to Markdown once we're closer to the final product. Can I share a google doc with the committee?

**Comment by PushkarJ** [comment]
Yes go for it @DavidKorczynski

**Comment by DavidKorczynski** [comment]
> Yes go for it @DavidKorczynski

Great! I shared it with you and @anvega -- I went over your git commit history to find the relevant emails, let me know if I should switch to other accounts in case you did not receive an invite.

**Comment by PushkarJ** [comment]
Cool. I got the link :) @DavidKorczynski are you okay if I share this with rest of the TAG Security Chairs and Leads too ?

**Comment by DavidKorczynski** [comment]
> Cool. I got the link :) @DavidKorczynski are you okay if I share this with rest of the TAG Security Chairs and Leads too ?

awesome -- yep, I left a comment when sharing the link that please share with whoever you see fit! 

Note I added a small section at the top of the doc with a deadline we are targeting. Just saying this since we will continue to add a bit of content and doing a bit of refinement in places.

**Comment by anvega** [comment]
Link to draft: https://docs.google.com/document/d/1JrsSwYlqBu98P6IYj0aWUcy1i6HsJA6HSwZ-0mH9TB0

**Comment by DavidKorczynski** [comment]
For reference, we have converted it to Markdown and added additional parts. A PR will be made in the next few hours.
