### ISSUE TITLE
validate personas and use cases

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/tag-security#109]
draft proposal
- Cloud native user: security roles & practices (target companies > N employees)
- Interview at least 4 people who fit each persona and ask them about their work
    - describe their role & responsibilities
    - what do they do day-to-day to ensure the security of their systems or prevent misuse?
    - how do they (or their company or colleagues) know that this work is effective?
- Create a survey and ask WG members to invite people they know who might fit these personas (without actually sharing our personas) or share on social networks
    - ask some of the above as survey text questions
    - consider:
        - country where they work
        - language they speak at work
        - company size
        - how long have they been in this role
        - industry experience (in years)
    - we will share results of our study with participants (whether we interview them or not)
- Synthesize the results into a report

If needed, refine with interviews to gather qualitative data

- Update personas, if needed. Add/edit use cases.  Consider updating language based on how people describe themselves and their role.

**Comment by lumjjb** [comment]
I believe there is a survey that is currently being drafted for cloud native security by CNCF from Katie Meinders.

**Comment by lumjjb** [comment]
Closing from triage review
