### ISSUE TITLE
Kyverno security assessment --- completed or waiting to proceed?

### ISSUE THREAD

**Issue by JustinCappos** [cncf/tag-security#1091]
I'm trying to clear up the status of items in the assessment queue and ran across [the merged PR on Kyverno's self assessment](https://github.com/cncf/tag-security/pull/852).  

It seems like there is some mix of effort here, like a full assessment was intended, but it may not have been carried out.  I do see that the self assessment ended up in our repository, which indicates that this may have been the intended end goal.  There doesn't seem to be an issue for the full assessment created on the tracker and a lot of the other work for this is missing.

@JimBugwadia, @jlk : What is the desired / intended outcome from your side here? 

If we did a full assessment, we'd need to recruit a team, but I think that shouldn't be too difficult.  From a quick look at the self assessment, there are a few things that would need to be expanded upon from your side, but overall it is helpful to give an overview of the project.  I'd imagine there would be quite a bit of back and forth in the review phase which would require effort from your side, but you'd get an assessment from our group out of it.

Also, it's worth mentioning, that we currently have at least two assessments ahead of this in the pipeline, so it may take a little time until this starts.

@JimBugwadia, @jlk, and others from the Kyverno team, let us know if you'd like to proceed with a full assessment  or if the self assessment is enough and we should remove the item from our queue.

**Comment by anvega** [comment]
@JimBugwadia, @jlk Nudge here. The directory where the partial assessment was merged is reserved for completed full joint assessments. Probably worthwhile to give it another pass so its consistent with the quality and depth of the other reviews.

**Comment by jlk** [comment]
Sorry missed the last ping. I'll sync up with Jim.

**Comment by anvega** [comment]
Cheers @jlk Thanks!

**Comment by jlk** [comment]
OK - didn't catch up with Jim, just read over things and put that part of my brain back on the stack. 🤓 

Kyverno engaged with STAG Security Pals as part of #554 . I don't remember exactly how they got on my radar, but after an initial chat the Self Assessment seemed like a good First Step so as a Security Pal™️  I helped @JimBugwadia work through that. 

Looking around, looks like Kyverno's still at Incubation level, but I'd guess the need for a full assessment will come at some point in the next year...

**Comment by anvega** [comment]
Thanks. Self-assessments have never before been submitted, only kept as a google doc. While the title doesn't change, what gets checked in as "completed" is the full assessment, which starts as a self-assessment, but goes through an evolution of many revisions from edits from the different reviewers, and the project team expanding on the original assessment to cover those review questions.  

We'll label the entry with an annotation so that it is clear what exists was done as part of the pal's pilot, and pending a complete joint assessment should the project team want to revisit it at a later point in time.
