### ISSUE TITLE
[Presentation] Secure Software Guiding Principles

### ISSUE THREAD

**Issue by jkmarz** [cncf/tag-security#1093]
Title: Secure Software Guiding Principles

Speakers: Jessica Marz/jkmarz

Description: The Secure Software Guiding Principles is a public pledge to perform an interlocking set of actions designed to enhance security of software supply chain. This is actually going to be worked through the OpenSSF Best Practices Working Group, with the objective to have the Principles endorsed by the OpenSSF Governing Board as something that software producers should adopt, but we would like to get feedback from the CNCF Security TAG about it! You can read the current draft of the Principles here: [https://docs.google.com/document/d/1y9c9hTTIrQtfWDtY6iNFHwUt2cv1lLj3ZW9DnxDKhJI/edit?usp=sharing ]

Time: How long will the presentation take? (estimate) 15 minutes

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page. I will prioritize this meeting! Let me know when works for your agenda and I will be there.

TO DO
- [X] TAG Representative: @mnm678 
- [X] Schedule date: July 26
- [X] By opening this issue, I, (jkmarz/Jessica Marz) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by mnm678** [comment]
Would you like to present this at the July 26 meeting?

**Comment by jkmarz** [comment]
July 26 would be great!

**Comment by mnm678** [comment]
Thanks for the presentation @jkmarz!
