### ISSUE TITLE
[Presentation] Bank-Vaults introduction

### ISSUE THREAD

**Issue by sagikazarmark** [cncf/tag-security#1103]
Title: Bank-Vaults introduction

Speakers: @sagikazarmark

Description: Introduce the Bank-Vaults project to TAG Security. Bank-Vaults is a Cloud Native secret management solution (currently heavily focusing on Hashicorp Vault). I'll talk a bit about the history, components and future plans.

Website: https://bank-vaults.dev
GitHub: https://github.com/bank-vaults

I've been asked to do this presentation after submitting a sandbox application: cncf/sandbox#54

Time: 10-15 minutes

Availability: Either US or EMEA meeting works for me after August 20.

TO DO
- [ ] TAG Representative
- [ ] Schedule date
- [x] By opening this issue, I, @sagikazarmark acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by sagikazarmark** [comment]
Friendly ping :)

The TOC is going to process the sandbox application of Bank-Vaults on Sept 12. Ideally, we'd like to present the project to the TAG before that.

Thanks!

**Comment by sagikazarmark** [comment]
Hey folks!

Just checking in: Any chance we'll be able to get a slot before the TOC vote (Sept 12th)?

@PushkarJ can you help me coordinate with the right folks?

**Comment by ashutosh-narkar** [comment]
@sagikazarmark we can schedule this for the 9/6 meeting. Will that work for you?

**Comment by sagikazarmark** [comment]
@ashutosh-narkar That sounds great! Thank you!

**Comment by ashutosh-narkar** [comment]
Perfect! You're on the schedule for the 9/6 meeting. If you can share your slides before the call that would be great. Thanks!

**Comment by sagikazarmark** [comment]
@ashutosh-narkar you can find the slides here: https://slides.sagikazarmark.hu/2023-09-06-cncf-tag-security-bank-vaults-introduction/

**Comment by sagikazarmark** [comment]
Demo: https://github.com/sagikazarmark/demo-bank-vaults

**Comment by anvega** [comment]
Thanks again for the presentation. Left a comment in the issue tracking the application.

https://github.com/cncf/sandbox/issues/54#issuecomment-1711997821
