### ISSUE TITLE
Buttons are aligned left instead of center in Tablet mode

### ISSUE THREAD

**Issue by VivekBaldha0712** [cncf/tag-security#1110]
![image](https://github.com/cncf/tag-security/assets/86009821/21d6820d-ba02-42a6-8891-1fe59d1b7b5b)
Buttons should be in the center for the better presentation of site.

**Comment by sublimino** [comment]
Thanks for the report, what URL is this and can you give browser/OS debug details please @VivekBaldha0712?

**Comment by VivekBaldha0712** [comment]
Sure. On this https://www.cncf.io/projects/

**Comment by anvega** [comment]
@VivekBaldha0712  You can submit an issue with that page directly in the corresponding repository at https://github.com/cncf/cncf.io/issues/new?title=Your+issue&projects=cncf/cncf.io/1&body=From+URL%3A+https%3A%2F%2Fwww.cncf.io%2Fprojects%2F
