### ISSUE TITLE
TAG Security website info is wrong

### ISSUE THREAD

**Issue by jberkus** [cncf/tag-security#1116]
This page: https://tag-security.cncf.io/

With source here: https://github.com/cncf/tag-security/blob/main/website/content/_index.md

... has the info for TAG-App Delivery, not TAG-Security.  Please update!

**Comment by ragashreeshekar** [comment]
I have created a service ticket for the same. I'll follow up and relay here as I receive updates.
[CNCFSD-1988](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1988)

**Comment by jberkus** [comment]
Er, shouldn't you just create a PR?  You own that repo.

**Comment by PushkarJ** [comment]
@jberkus yes you are right, the website content is co-owned by us and CNCF staff (see the commit history). We are planning to discuss how to make changing this easier in the future as part of that ticket so PRs would be the way to go.

**Comment by ragashreeshekar** [comment]
Received updates on the service ticket, and I have created the PR to address this issue. 
Reference - https://github.com/cncf/tag-security/pull/1122.

**Comment by anvega** [comment]
Thanks @jberkus. We've fixed this but looks like the page has yet to be regenerated.

**Comment by PushkarJ** [comment]
This is now fixed post merge of https://github.com/cncf/tag-security/pull/1150
