### ISSUE TITLE
[Presentation] TAG Compliance proposal

### ISSUE THREAD

**Issue by sunstonesecure-robert** [cncf/tag-security#1119]
Title: TAG Compliance Mission Discussion

Speakers: Who will be presenting this? List names/github IDs of presenters.
Robert Ficcaglia @rficcaglia 
Anca Sailer @ancatri
Jayashree Ramanathan @jrnp7

Description: 

Several members of STAG and K8s SIG-security would like to start a separate Compliance TAG to focus not only on technical controls, but overall regulatory compliance as CNCF projects become more and more critical to compute and data infrastructure for private enterprises and public sector organizations worldwide that are subject to complex legal requirements. TAG Compliance will assist the community as a SME body to address the nuanced and often contradictory technical AND non-technical compliance design forces.

Time: How long will the presentation take? (estimate)
15-20 min

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page.
10/25/2023 10AM Pacific

TO DO
- [X] TAG Representative: @mnm678 
- [X] Schedule date: October 25
- [X] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by PushkarJ** [comment]
Tagging @mnm678 is tentatively scheduled to be the facilitator on proposed date of Oct 25. 

Please work with her to ensure you  are on schedule

**Comment by mnm678** [comment]
You are scheduled for October 25.

**Comment by ancatri** [comment]
Sounds good, looking forward!

--
Thank you,
Anca
_______________________________________
Anca Sailer, Ph.D., Distinguished Engineer
***@***.***   –   1 914 945 3273
IBM Research

On Oct 11, 2023, at 11:34 AM, Marina Moore ***@***.***> wrote:

﻿
You are scheduled for October 25. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <cncf/tag-security/issues/1119/1757972741@ github. com> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2U-rqXQViVEQkMYTsistJseSW9NzUUef-BrAE8P0iFZgAfrvbjpovUxLtmfvt54eGriWMAlVA6xlmg0oBiWw31mwU1mu5_n0c-lk$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

You are scheduled for October 25.

**Comment by sunstonesecure-robert** [comment]
just to capture next steps from the discussion:

- [ ] meet at Kubecon NA and discuss futher collaboration opportunities in the near term as TOC refactors TAG processes
- [ ] gather feedback on the mission statement and presentation
- [ ] summarize feedback and recommendations and review with TOC Q1 2024

**Comment by ancatri** [comment]
Looks good

--
Thank you,
Anca
_______________________________________
Anca Sailer, Ph.D., Distinguished Engineer
***@***.***   –   1 914 945 3273
IBM Research

On Oct 25, 2023, at 5:15 PM, sunstonesecure-robert ***@***.***> wrote:

﻿
just to capture next steps from the discussion: meet at Kubecon NA and discuss futher collaboration opportunities in the near term as TOC refactors TAG processes gather feedback on the mission statement and presentation summarize feedback and
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2U-rqXQViVEQkMYTsistJseSW9NzUUef-BrAE8P0iFZgAftPjxpIXUwLlmfvt54e0KxIRK9X_Z0wP8zyBdxl0HwJSDFhfF1CITfK$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

just to capture next steps from the discussion:

  *    meet at Kubecon NA and discuss futher collaboration opportunities in the near term as TOC refactors TAG processes
  *    gather feedback on the mission statement and presentation
  *    summarize feedback and recommendations and review with TOC Q1 2024

**Comment by brandtkeller** [comment]
@sunstonesecure-robert @ancatri Would love to participate in the KubeCon collaboration session.

**Comment by PushkarJ** [comment]
Thank you for the presentation. Let's continue the conversation on this as planned
