### ISSUE TITLE
[Unconference] TAG Security Supply Chain WG

### ISSUE THREAD

**Issue by jkjell** [cncf/tag-security#1127]
Description: What's your topic?
Learn about all the work being done in the TAG's Supply Chain Working group. Find out how you can contribute and help propose what we could work on next!

Benefits to Ecosystem: what will attendees learn from the talk that will help them in their cloud native journey?
Help community members learn from experts in the Supply Chain security space and increase contributors to the working group.

**Comment by PushkarJ** [comment]
Congrats @jkjell you are selected Wednesday 4:30-5:05 PM slot for November 8 2023. Schedule will be updated soon. If you have schedule conflict please let us know as soon as possible. See you tomorrow ! 🎉🙌🏼👍🏼

**Comment by jkjell** [comment]
Thanks PJ, I'll be there! Also, paging @mnm678 and @mlieberman85 for the discussion. I'm sure they both already know but... just in case.  ☺️

**Comment by jkjell** [comment]
KubeCon completed - Thanks for the opportunities to present!
