### ISSUE TITLE
[Unconference] Don't Sign your Containers!

### ISSUE THREAD

**Issue by jkjell** [cncf/tag-security#1128]
Description: What's your topic?
Learn how you can do more than just sign your container images by creating robust supply chain metadata instead!

Benefits to Ecosystem: what will attendees learn from the talk that will help them in their cloud native journey?
Attendees will learn about different types of supply chain metadata, based on in-toto attestations, and how they can leverage them to create useful policy to improve their security posture.

**Comment by PushkarJ** [comment]
Congrats @jkjell you are selected Wednesday 3:25 - 4:00 PM slot for November 8 2023. Schedule will be updated soon. If you have schedule conflict please let us know as soon as possible. See you tomorrow ! 🎉🙌🏼👍🏼

**Comment by jkjell** [comment]
Thanks PJ, I'll be there!

**Comment by jkjell** [comment]
KubeCon completed - Thanks for the opportunities to present!
