### ISSUE TITLE
[Unconference] All things OpenSSF

### ISSUE THREAD

**Issue by jkjell** [cncf/tag-security#1129]
Description: What's your topic?
Come to learn about the working groups, projects, and intentions of the OpenSSF!

Benefits to Ecosystem: what will attendees learn from the talk that will help them in their cloud native journey?
The attendees will be able to learn about the on going work in the OpenSSF and how it relates to work being done in the CNCF.

**Comment by PushkarJ** [comment]
Hi @jkjell because of limited time slots we couldn't select this one but I think we could cover some of the topics here in the other two sessions you are selected for tomorrow. Hope that's ok 👍🏼

**Comment by jkjell** [comment]
KubeCon completed - Thanks for the opportunities to present!
