### ISSUE TITLE
[Unconference] The Active Observer of a Zero Trust Architecture

### ISSUE THREAD

**Issue by davidhadas** [cncf/tag-security#1132]
Description: In this talk I will discuss how an Active Observer can be introduced as part of a Zero Trust solution to construct Confidence Levels needed for both Access Control and the ability to handle compromised services.  

Benefits to Ecosystem: Why is this talk or discussion important to cloud native security?
Interest in Zero Trust is growing and the community need to drill down to understand how ZTA can be build in CN

Additional info:
- Reference to supporting material - the Zero Trust White paper https://docs.google.com/document/d/10g2390JdCBXmSmzQ_EGHFWrg2JosPsXLaqXaGQ-B9NA/edit?usp=sharing
- I give a talk on November 7 • 2:30pm - 3:05pm
- I am leaving Chicago on Thursday around 11AM

**Comment by ragashreeshekar** [comment]
Thanks for the submission @davidhadas. 
Please be invited to present this session at 2:30 - 3:05 PM, Wednesday 11/08.

**Comment by mnm678** [comment]
Thanks for the presentation! Closing as completed.
