### ISSUE TITLE
[Presentation] Auto VEX generation for projects with Kubescape Operator

### ISSUE THREAD

**Issue by slashben** [cncf/tag-security#1163]
Title: Auto VEX generation for projects with Kubescape Operator

Speakers: 
* Ben Hirschberg - @slashben

Description: This is an introductory presentation to TAG Security about [VEX](https://github.com/openvex/spec) [generation capabilities](https://kubescape.io/docs/operator/generating-vex/) of the Kubescape project. This capability is first of its kind in the OSS scene. Beyond the introduction, we are also seeking to trigger discussion about how could we turn this capability into a way to easily generate VEX-es for our projects. 

Time: 30m

Availability: Can join meeting from the 8th of December

cc: @oshratn

TO DO
- [x] TAG Representative: @PushkarJ 
- [x] Schedule date: Dec 13 10 AM pacific
- [x] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by PushkarJ** [comment]
Hi @slashben we have a meeting on December 13 and December 20. Which  day suits you best?

**Comment by slashben** [comment]
December 13 is great!

**Comment by PushkarJ** [comment]
Thank you @slashben . You are all set for Dec 13. Can you review the last TODO about presentation guidelines and mark it as done if there are no concerns ?

**Comment by anvega** [comment]
The presentation took place already.
