### ISSUE TITLE
[Presentation] OpenCRE.org and CNCF, standard harmonization usecases for the modern cloud 

### ISSUE THREAD

**Issue by northdpole** [cncf/tag-security#1210]
Title: OpenCRE.org and CNCF, standard harmonization usecases for the modern cloud 
Speakers: Spyros Gasteratos (@northdpole), Rob Van Der Veer (@robvanderveer)

Description: 
In this presentation we will showcase what the OpenSource Standards Harmonization platform OpenCRE.org is, how it came to be and what gotchas we had to overcome in order to get here.
We will further discuss why we believe it makes sense for standards writers to refer to OpenCRE for their linking needs and  what the platform can do with its several use cases.
We will close this presentation by showcasing the integration with the excellent Cloud Native Security Controls and discuss next steps.

Time: 40 minutes (approximately, can trim down)

Availability: 17/1 or 31/1 @ 13:00 London
TO DO
- [x] TAG Representative @mrcdb , @sublimino 
- [x] Schedule date
- [ ] By opening this issue, I, (@northdpole) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by mrcdb** [comment]
hi @northdpole , looks interesting!

I recommend having someone like @sublimino as formal "TAG Representative" for the issue, but I can help facilitate the EMEA meeting if needed :smile: 

With regards to the date, 17/1 @ 13:00 London works for me

**Comment by northdpole** [comment]
Hey @mrcdb , can we please postpone this for the 31st? We can then have Rob Van Der Veer participate in the presentation.

**Comment by sublimino** [comment]
> Hey @mrcdb , can we please postpone this for the 31st? We can then have Rob Van Der Veer participate in the presentation.

Sure thing, moved in the meeting notes to the 31st :+1:

**Comment by anvega** [comment]
The presentation took place already.
