### ISSUE TITLE
List of Conference Talks to submit CFP

### ISSUE THREAD

**Issue by zeal-somani** [cncf/tag-security#1228]
### Upcoming Conferences

1. **Title of Talk 1 - TBD**
   - **Conference Name:** [fwdcloudsec](https://fwdcloudsec.org/conference/north-america/cfp.html)
   - **CFP close date:** February 16, March 29
   - **Dates:** [June 17-18]
   - **Location:** [Arlington VA]
   - **Link to Presentation:** [Link to presentation slides or recording if available]

2. **Title of Talk 2 - TBD**
   - **Conference Name:** [SOSS Community Day NA 2024](https://openssf.org/event/hosting-soss-community-day-na-2024/)
   - **Date:** [April 15]
   - **Location:** [Seattle WA]
   - **Link to Presentation:** [Link to presentation slides or recording if available]

3. **Title of Talk 3**
   - **Conference Name:** [Conference 3]
   - **Date:** [Date of Talk 3]
   - **Location:** [Location of Conference 3]
   - **Link to Presentation:** [Link to presentation slides or recording if available]

# Additional Talks (if applicable)

4. **Title of Talk 4**
   - **Conference Name:** [Conference 4]
   - **Date:** [Date of Talk 4]
   - **Location:** [Location of Conference 4]
   - **Link to Presentation:** [Link to presentation slides or recording if available]

5. **Title of Talk 5**
   - **Conference Name:** [Conference 5]
   - **Date:** [Date of Talk 5]
   - **Location:** [Location of Conference 5]
   - **Link to Presentation:** [Link to presentation slides or recording if available]

**Comment by PushkarJ** [comment]
@zeal-somani Can you share the intent of this issue? Related to https://github.com/cncf/tag-security/issues/1227
