### ISSUE TITLE
[Presentation] Ratify project introduction and demo for CNCF Sandbox application

### ISSUE THREAD

**Issue by FeynmanZhou** [cncf/tag-security#1239]
Title: Ratify project overview and demo for CNCF Sandbox application

Speakers:  @akashsinghal @luisdlp

Description: Ratify is a verification engine on Kubernetes which enables verification of artifact security metadata and admits for deployment only those that comply with policies users create. We are applying for CNCF sandbox status, and as part of that we'll give a brief overview of how Ratify works, and the typical workflows and scenarios that it fits into.

Time: 10~15 minutes

Availability: We are open to the schedule and be comfortable with the weekly meeting on each Wednesday at 10 am (UTC-7) in Apr and May. Please let us know if you have a suggested occurrence for this presentation.

TO DO
- [ ] TAG Representative
- [ ] Schedule date
- [x] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by mnm678** [comment]
Would you like to present on April 17?

**Comment by FeynmanZhou** [comment]
> Would you like to present on April 17?

Hi @mnm678 ,

Thanks for your response.

We have a conflict on April 17. Is it possible to present Ratify on April 24?

**Comment by mnm678** [comment]
You are scheduled for April 24.

**Comment by akashsinghal** [comment]
Here are the slides that we will be presenting in the meeting: 
[CNCF TAG Security Presentation - Ratify.pdf](https://github.com/cncf/tag-security/files/15087573/CNCF.TAG.Security.Presentation.-.Ratify.pdf)

**Comment by anvega** [comment]
Presentation took place already.
