### ISSUE TITLE
Broken link to related groups

### ISSUE THREAD

**Issue by chrpotr** [cncf/tag-security#1244]
I get a 404 error when I click on the link to related groups found [here](https://tag-security.cncf.io/#related-groups)

> There are several groups that are affiliated to or do work and cover topics relevant to the work of Security TAG. These can be seen [here](https://tag-security.cncf.io/governance/related-groups/)

Broken link points to https://tag-security.cncf.io/governance/related-groups/

**Comment by brandtkeller** [comment]
Noticing a number of broken links associated to local markdown files. I want to look for root-cause but otherwise can migrate resources to their expected locations.

**Comment by brandtkeller** [comment]
I see the following links broken on the homepage:

- publications
- governance charter
- governance process
- slack governance
- meeting time process
- gathering past events
- new members
- related groups
- proposed policy working group
- supply chain security
- past events page

I'm no hugo/docsy expert but the current website layout with the use of a `root/` directory for copying the content does not look to support the linking very well. With some careful copying into `website/content` this should all work appropriately at the homepage. Will submit a PR for a first draft.
