### ISSUE TITLE
[Presentation] cert-manager Graduation Overview

### ISSUE THREAD

**Issue by SgtCoDFish** [cncf/tag-security#1254]
Title: cert-manager Graudation Overview

Speakers:
- Ashley Davis (@SgtCoDFish)

Other attendees from the cert-manager project:
- Adam Talbot (@ThatsMrTalbot)

Description: An overview of what cert-manager is and does, mostly with the aim of facilitating connections, questions and input from tag-security. Related to (and required by) [cert-manager's Graduation Application](https://github.com/cncf/toc/issues/1306).

Time: 10 mins, with extra time after for questions if required.

Availability: European timezones preferred!

Checklist:

- [x] TAG Representative
- [x] Schedule date - pencilled in for 2024-05-22 EMEA meeting
- [x] By opening this issue, I, (Ashley Davis - @SgtCoDFish) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by sublimino** [comment]
Hi @SgtCoDFish, sounds great! 

EMEA meetings are currently free for the next few weeks, please choose a time in [the meeting document](https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/edit).

As part of the graduation in https://github.com/cncf/toc/issues/1306 we can support you in the `Document Security Self-Assessment` phase, and walk through a self-assessment doc based on [this template](https://github.com/cncf/tag-security/blob/main/assessments/guide/self-assessment.md) and [this process](https://github.com/cncf/tag-security/tree/main/assessments).

The [cert-manager incubation due diligence document](https://docs.google.com/document/d/1HCh3Q4LR6LFq1yHX2JIdGjp9_n82L22aEQDCMwCV5M0/edit) from a couple of years ago might be useful as a baseline to support the graduation documents too. Any questions please ask, we're here to help :pray:

**Comment by SgtCoDFish** [comment]
Thanks very much for the quick reply 😁 

I've put us in for 2024-05-22 and we'll prepare for then!

> As part of the graduation in https://github.com/cncf/toc/issues/1306 we can support you in the Document Security Self-Assessment phase, and walk through a self-assessment doc based on [this template](https://github.com/cncf/tag-security/blob/main/assessments/guide/self-assessment.md) and [this process](https://github.com/cncf/tag-security/tree/main/assessments).

That sounds great, thank you for pointing to that because I'd been meaning to investigate it! I guess there's nothing stopping us getting started with the self-assessment now (before the 22nd), right?

**Comment by sublimino** [comment]
> That sounds great, thank you for pointing to that because I'd been meaning to investigate it! I guess there's nothing stopping us getting started with the self-assessment now (before the 22nd), right?

Absolutely! And if you share the doc link for public comment we can support async before the 22nd too 🙏

**Comment by maelvls** [comment]
Hey, here is the self-assessment doc: https://hackmd.io/_e-m6hnzRzqsosUv3aG60A. I'm struggling and need help with the subsections "Actors" and "Actions". Are the actors the same as in [the security audit report](https://ostif.org/wp-content/uploads/2024/03/AdaLogics-2023-cert-manager-audit-report.pdf): cert-manager contributors, untrusted users outside of cluster, limited privilege cluster users, cert-manager maintainers, third-party contributors, third-party maintainers? Let me know if you are available on the Kubernetes Slack.

**Comment by mrcdb** [comment]
hi @maelvls , thanks for sharing the self-assessment doc. 

The [self-assessment guide](https://github.com/cncf/tag-security/blob/main/assessments/guide/self-assessment.md#actors) describes actors as _"the individual parts of your system that interact to provide the desired functionality"_, so I would consider them as the different components of cert-manager rather than the threat actors. Actions then should delineate which interactions exist between the actors.

I am available on the CNCF Slack

**Comment by SgtCoDFish** [comment]
Thanks for having us on the EMEA meeting today!

I'm taking away the following actions:

1. Move from HackMD to a Google Doc for the self assessment
2. Ask for feedback on the completed self assement Google doc

I'll comment on this issue when I've done those. I'll also update the graduation application to reflect the meeting and self assessment!

**Comment by SgtCoDFish** [comment]
Here's the Google doc for our self-assesment - the above HackMD can now be ignored!

https://docs.google.com/document/d/1Sl1SqYbPSbBMoZroBU8M1dMw5DN-uUgoR1KLHoo5tr0/edit?usp=sharing

Anyone should be able to comment on it - any problems, let me know!

**Comment by SgtCoDFish** [comment]
Thanks very much! I'll try to raise a PR soon 👍

**Comment by SgtCoDFish** [comment]
I raised the PR here: https://github.com/cncf/tag-security/pull/1269

Sorry it took a while, it's been a busy time!
