### ISSUE TITLE
broken links in OpenFGA Self Assessment markdown

### ISSUE THREAD

**Issue by sunstonesecure-robert** [cncf/tag-security#1256]
- This link:
https://github.com/cncf/tag-security/blob/c74d28b15f4f8ade2b71b0c29a89f177c57e57aa/assessments/projects/openfga/self-assessment.md?plain=1#L50
seems to be a 404
- For the Snyk monitoring badge - the link goes to a Snyk page saying the project is missing a manifest file

**Comment by aaguiarz** [comment]
@lj365 can you take a look?

**Comment by lj365** [comment]
The https://github.com/orgs/openfga/security/risk is only available to certain users. It's not a "true" 404, its permission issues. 

For the Snyk monitoring badge, indeed, Snyk doesn't support Go as of now for public repositories (https://support.snyk.io/hc/en-us/articles/360003997277-Badge-Support-for-Repositories). 

Although, it is being scanned as part of the [Cloud Native Foundation Snyk Group](https://app.snyk.io/group/beb04572-ae07-461f-967b-ca5fe12041c1)

**Comment by sunstonesecure-robert** [comment]
@lj365 thanks! well at least it looks nice ;)  for practical purposes - would it be possible to arrange to send a copy of the latest report out to the TSSA reviewers for review? (or to me directly and I can distribute to them) - thanks!

**Comment by anvega** [comment]
Looks like this is working as designed =) 

Please consider either removing the link as it's not meant to be public so people don't have issues accessing it or as @sunstonesecure-robert recommended to share a copy of the contents.
