### ISSUE TITLE
Cloud Native Policy White Paper

### ISSUE THREAD

**Issue by hannibalhuang** [cncf/tag-security#126]
The policy team has started the drafting process of [cloud native policy white paper](https://docs.google.com/document/d/1StDYW1zHVSF1Qswk0ScsyKw766AbAHOikyCNtqCsMMY/edit?usp=sharing)

It is still very much in the early stage and hopefully by mid-year we will have a 0.1 version out.

TODO:
- [X] STAG sponsor for co-work with k8s policy WG: @achetal01

**Comment by hannibalhuang** [comment]
some progress update, we added a lot of case studies summaries into Chapter 3, and a lot of discussion with Google and Ebay developers regarding certain content. We will probably be looking at adding formal verification related stuff into the white paper.

**Comment by sunstonesecure-robert** [comment]
This is no longer an active effort in the policy WG, now under the [Kubernetes SIG hierarchy](https://github.com/kubernetes-sigs/wg-policy-prototypes). It is still worthy of effort, but the pointer should be reassigned.

**Comment by anvega** [comment]
Closing this as it has been stale for over two years. Also the Kubernetes Policy Management Whitepaper was published.
