### ISSUE TITLE
[Suggestion] Improve which working groups are linked and HOW

### ISSUE THREAD

**Issue by brandtkeller** [cncf/tag-security#1261]
Description: What's your idea?

Impact: Current groups/initiatives/etc are linked from the repo/website in a variety of disparate means. It might be good to establish a common pattern for how to surface these efforts and any other pertinent information.

Scope: With current efforts such as #1257 underway - this is likely a good consideration for related but separate content revisions.

**Comment by anvega** [comment]
See https://github.com/cncf/tag-security/pull/1266

**Comment by anvega** [comment]
https://github.com/cncf/tag-security/pull/1271
