### ISSUE TITLE
[Presentation] Kubescape project update (feedback for incubation)

### ISSUE THREAD

**Issue by slashben** [cncf/tag-security#1262]
Title: Kubescape project update

Speakers: @slashben @matthyx 

Description: It has been nearly 2 years since Kubescape was introduced to TAG-Security and around a year ago when we last presented. This presentation is meant to give a project update to the TAG about the progress we made in the last year in adoption and development. 

Time: 30 minutes

Availability: All meeting times should work after CNSCon in July

TO DO
- [x] TAG Representative: @PushkarJ  
- [x] Schedule date: July 10
- [x] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by PushkarJ** [comment]
Thanks @slashben. Which one would you prefer between July 3 or July 10?

**Comment by slashben** [comment]
@PushkarJ , July 10 will be better

**Comment by mrcdb** [comment]
@slashben, would it be possible for you to share a link to the slides for the presentation?

We can add the slides link to the presentation info in the [meeting notes](https://docs.google.com/document/d/1XDmNG1P1YRnidQJEuZFKufaXaIenNHiY-TdYMlt0Un4/edit#heading=h.qd70dyuhrp1e) so that anyone interested can see what was discussed on 10/7, in addition to the notes that the TAG members have taken.

**Comment by matthyx** [comment]
> @slashben, would it be possible for you to share a link to the slides for the presentation?
> 
> We can add the slides link to the presentation info in the [meeting notes](https://docs.google.com/document/d/1XDmNG1P1YRnidQJEuZFKufaXaIenNHiY-TdYMlt0Un4/edit#heading=h.qd70dyuhrp1e) so that anyone interested can see what was discussed on 10/7, in addition to the notes that the TAG members have taken.

@mrcdb I have added a PDF link to the meeting notes, let me know if that's enough?

**Comment by mrcdb** [comment]
> > @slashben, would it be possible for you to share a link to the slides for the presentation?
> > We can add the slides link to the presentation info in the [meeting notes](https://docs.google.com/document/d/1XDmNG1P1YRnidQJEuZFKufaXaIenNHiY-TdYMlt0Un4/edit#heading=h.qd70dyuhrp1e) so that anyone interested can see what was discussed on 10/7, in addition to the notes that the TAG members have taken.
> 
> @mrcdb I have added a PDF link to the meeting notes, let me know if that's enough?

Yes, thank you!

**Comment by mnm678** [comment]
Thank you for the presentation!
