### ISSUE TITLE
Project presentation template for presenting project to SAFE

### ISSUE THREAD

**Issue by pragashj** [cncf/tag-security#130]
Some of the things that the template should cover:
- Use cases that it solves
- Categories of security problem that it solves
- Technology choices  
- Architecture & Design
- Test cases and coverage
- Community and adoption (metrics around that)

**Comment by ultrasaurus** [comment]
In today's SAFE WG, we reviewed this [template](https://docs.google.com/presentation/d/1lv-Qj6r5iZ2Vf3Yhu6bY4q3rFlFt6W-Jy_AR0IUDFkY/edit#slide=id.g4f9dfd301a_0_0) -- created by @ckemper67 and @ultrasaurus 

[2019-02-15 SAFE WG Meeting notes](https://docs.google.com/document/d/1WLnEErqODywjkQVTAESpwK8pgIbxsNDp6SqOtw3kjlk/edit#bookmark=id.y36vddmj59ck)

**Comment by ultrasaurus** [comment]
@ckemper67 @JustinCappos @SantiagoTorres @ultrasaurus met on 3/18 to discuss revisions to the template based on in-toto experience.

Key takeaway:  We'd like to create a more clear delineation between the properties that the users of the systems should get and the project itself.
1. Is the project aiming at the right thing (solving an important problem for cloud native security, safety, etc.)
2. Is the project executing effectively (e.g. are there holes in project process or implementation)

Where #2 is expected to be more similar between projects and we think could be addressed through document / async feedback, and #1 would benefit more from discussion with presentation as a framework for discussion with the group.

We brainstormed a revised outline for the presentation.

Next steps:  

1. @ultrasaurus to make a copy of the in-toto presentation and revise the content in-place to match the new format 
2. @SantiagoTorres to fill in any missing parts of presentation and revise as needed and also fill in accompanying doc
3. present to SAFE WG 
4. revise the template

see full [meeting notes](https://docs.google.com/document/d/1yb-Bw0OPXPEy1fBsISfDGisSumVL8ulfDctnLYmxKu8/edit) -- not formatted for easy reading, but in case needed for reference

**Comment by TheFoxAtWork** [comment]
closing - existing presentation template has been greatly reworked since this issue.
