### ISSUE TITLE
TAG Documentation Update: TAG  Security

### ISSUE THREAD

**Issue by riaankleinhans** [cncf/tag-security#1312]
This issue supports updating the TAG README, Charter and moving documents to the TAG’s Gdrive. The work will be tracked in the TOC Tracking issue [#1366](https://github.com/cncf/toc/issues/1366).

The following points should be addressed:
  -  PR updating TAG repo README in accordance to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md)
  - PR removing TAG repo charter
  - PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the [template](https://github.com/cncf/toc/tree/main/tags/tag-charters)
  The aim of this update is to ensure that no information is lost from the TAG’s repo level charter.
  - Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
  The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.

**Comment by anvega** [comment]
Thank you for this feedback. A few points to consider:

1. Is this a guideline? We recently updated our README to be more concise, and it's fairly close to the suggested template.

2. We have both a short version of the charter in the README and an expanded version in the governance folder. This allows visitors to quickly understand our scope without being redirected to the TOC repo.

3. While we appreciate the effort to maintain consistency across TAGs, we've aimed to be well-organized while also adhering to CNCF's principle of "minimum viable governance that enables projects to be self-governing" (as per https://www.cncf.io/blog/2019/08/30/cncf-technical-principles-and-open-governance-success/).

We're open to further discussion on how to balance these considerations.

**Comment by riaankleinhans** [comment]
@anvega thank you for your feedback.

#### README:
 You are correct, the TAG security README is well maintained.
One change that I would like to TAG to make. (I am also willing to help with PR's) is to move the TAG Leadership to the TOC repo page: https://github.com/cncf/toc/blob/main/tags/cncf-tags.md
The rational is to have it only in one place, approved by the TOC, as the information in the TOC and TAG repo often get out of sync.

#### Charter
The short version in the README is perfect, however the [TOC](https://github.com/cncf/toc/blob/main/tags/tag-charters/security-charter.md) and [TAG](https://github.com/cncf/tag-security/blob/main/governance/charter.md) versions of the Charter is out of sync. 
The Charter is the description of the relationship between the TAG and the TOC and should only be changed in collaboration with the TOC as often as it is needed. (And it is hard to manage version control of the same document in two places.)

**Comment by anvega** [comment]
Thank you for the detailed explanation @riaankleinhans. I understand the reasoning behind these suggestions, particularly regarding version control and maintaining consistency between the TOC and TAG repos.

The proposed changes sound reasonable to me, as they're not contentious and aim to improve overall organization. However, I'd like to gather input from the rest of the TAG leadership before proceeding, especially considering recent efforts by the chairs to showcase the entirety of the repo on the TAG website.

Perhaps we could discuss this in our TAG meeting tomorrow or set something ad-hoc to ensure we're aligning our documentation and information architecture strategy with both the TOC's guidelines and our own recent initiatives? 

Please go ahead with the proposed PR so we have something concrete to review. This will help facilitate our discussion and decision making process.

**Comment by riaankleinhans** [comment]
@anvega I created a PR #1376 in the TAG repo and a corresponding PR in the TOC repo https://github.com/cncf/toc/pull/1376

Both are still WIP and open for discussion.

**Comment by riaankleinhans** [comment]
All TAG Security google docs that I am aware of have now been moved to the project@cncf.io /[ tag-security folder](https://drive.google.com/drive/folders/1kVxmRt34KJUFWGlk_3_C8ro77NLK-vdK) 

Once PR #1316 merge I think we can close this issue.
The related PR in TOC repo have been approved https://github.com/cncf/toc/pull/1376 by @linsun

Adding your approval / review on both PRs would be appreciated.

@PushkarJ @mnm678 @anvega @eddie-knight
