### ISSUE TITLE
[Suggestion] Update Repo Website to tag-security.cncf.io

### ISSUE THREAD

**Issue by szh** [cncf/tag-security#1317]
Now that we have the newly launched site, I propose we update the GitHub repo's website url, as shown below to https://tag-security.cncf.io/ instead of cncf.io/projects

![Screenshot 2024-07-10 at 3 57 26 PM](https://github.com/cncf/tag-security/assets/546965/6ad98b0e-5fe7-4bda-a9af-fb8b16816ecc)

**Comment by brandtkeller** [comment]
@szh Agreed - can you help point me to where this screenshot originated? is it on the TAG Security website or another location within the CNCF?

**Comment by szh** [comment]
On the tag repo page

**Comment by PushkarJ** [comment]
![Screenshot 2024-07-10 at 6 45 18 PM](https://github.com/cncf/tag-security/assets/3390906/556633e2-ccef-428f-9b97-f9295963ed1e)
Edited this as sounds like have the GitHub Karma / Permissions to edit it :) 

We can keep this issue open for now, to see if anyone has other thoughts on this change. After a week or so, if we don't hear back, we can close the issue and assume lazy consensus on the website update for GitHub Repo
