### ISSUE TITLE
Fix community meeting recordings upload to YouTube

### ISSUE THREAD

**Issue by mrcdb** [cncf/tag-security#1334]
The Zoom feature that automatically uploads meeting recordings to the [TAG YouTube channel](https://www.youtube.com/@cncftagsecurity9823/videos) does not work anymore for several months.

It would be nice to have the ability to view past community meetings' recordings, especially when presentations or working sessions are held. Moreover, this is mentioned in the presenter script *"[...]this meeting is being recorded and posted to youtube shortly after"* and we may want to update that in case this is not fixable.

**Comment by mnm678** [comment]
Thanks for raising this! One idea @riaankleinhans had on this topic is to switch the meetings to LFX, which would make the recordings easier to access.

**Comment by eddie-knight** [comment]
Hey @riaankleinhans, we discussed this on today's community call and the consensus is that we're ready to migrate the meetings to LFX, with some cautions.

1. We need to ensure that guests can join meetings without an LFX account
2. We need to ensure that the meeting is updated on the primary CNCF calendar

**Comment by riaankleinhans** [comment]
Prefect. 
@eddie-knight , would the change be for the mail TAG Security meetings for EMEA and North America?
Should I also include the WG meetings?

**Comment by eddie-knight** [comment]
Thanks, that's perfect. 

Yes, we can move all TAG meetings over.

Two more thoughts...

1. The community meeting descriptions currently have an old link, which itself contains a reference to a new doc link. Can we get that updated while you're in there?
1. For explicit clarity, could you update this issue with which meetings are impacted? That way we can make sure folks are aware of changes that impact them.

**Comment by riaankleinhans** [comment]
@eddie-knight I created a GDoc containing my plan for faultless transition.
Please add any meeting description  and meeting document links in the document.
I also need edit access to the TAG Security Calendar.
http://document/d/1pFSPs3Z5OqXmnWdP1vJxmKARHcgtmQTqes4uqIan41U/edit

**Comment by mnm678** [comment]
We have transitioned to LFX. @riaankleinhans, where can we access the recordings for past meetings?

**Comment by mnm678** [comment]
Recordings are available at: https://zoom-lfx.platform.linuxfoundation.org/meetings/cncf?view=week under the day of the past meeting

**Comment by mrcdb** [comment]
Thanks ! I think this issue can be closed now as meetings have transitioned to LFX and recordings are automatically made available as pointed out by @mnm678 .
