### ISSUE TITLE
[Baseline WG] Gather feedback on Baseline Metrics

### ISSUE THREAD

**Issue by eddie-knight** [cncf/tag-security#1336]
The draft metrics for the Open Source Project Security Baseline are now available for feedback.

As part of the Security Baseline WG, we will be soliciting survey responses from TAG members, the TOC, and project maintainers. 

The survey has a closing date of August 20th.

Please use the comments on this issue to track progress as we share the survey out. Supplemental discussion will be had in the [CNCF Slack](slack.cncf.io) channel `#tag-security-baseline-wg`.

## Survey Link

https://forms.gle/Cr2iSBUDK3nbEtSy6

**Comment by eddie-knight** [comment]
@mrcdb is drafting a message that can be shared on the TAG slack and mailing list, with the goal of introducing the survey along with background information.

I will be reaching out to TOC members this week, in hopes that we can get a few survey responses from their perspective.

**Comment by dehatideep** [comment]
I posted my survey. Additional discussion points captured at: https://docs.google.com/spreadsheets/d/1C3gm5h1P1TFUcTQ-fjV0q7BISIFkzcWg/edit?usp=sharing&ouid=117540464562694021446&rtpof=true&sd=true
