### ISSUE TITLE
[Presentation] OpenFGA Project Status

### ISSUE THREAD

**Issue by aaguiarz** [cncf/tag-security#1339]
Title: OpenFGA Project Status

Speakers: Who will be presenting this? [aaguiarz](https://github.com/aaguiarz)

Description: Give a brief introduction to the [OpenFGA project](https://openfga.dev), talk about the progress we made in the last 2 years, and share different adoption use cases. Slides are [here](https://docs.google.com/presentation/d/1-TFfvKPi3jJ-jO-bjsHb3Soj_kKcQCf4Y_UvST7z744/edit#slide=id.p).

Time: How long will the presentation take? 20 mins

Availability: August 7th 1pm ET, August 14th 1pm ET

Slides
TO DO
- [x] TAG Representative @eddie-knight 
- [x] Schedule date: August 14th, NA Community Meeting
- [X] By opening this issue, I, @aaguiarz acknowledge that the presentation topic and speaker will follow the [presentation guidelines](../CONTRIBUTING.md#present-to-the-tag)
- [x] If this is a presentation for a project moving levels, the TAG Representative should complete the [Moving Levels Recommendation](../project-resources/moving-levels-review-template.md)

**Comment by eddie-knight** [comment]
Hi @aaguiarz :wave:

I've added you to the NA meeting schedule for August 14th.

I'll add a comment after this one with the recommendation template, which we'll fill out during the call.

**Comment by eddie-knight** [comment]
# Template for TAG recommendation to TOC

## Project Overview

### Ecosystem Adoption

What ecosystem adoption has the project seen?

### Past TOC Reviews

How has the project addressed comments from previous reviews (incubation if graduation, sandbox if incubating, etc)?

## Security Reviews

### TAG Security Assessments

Has the project completed a TAG Security Self-Assessment and/or Joint Assessment? If yes, please add a link and discuss how this has impacted their security posture.

### Security Audit

Has the project completed an external security audit? If yes, how have they addressed the findings?

## Best Practices

### Metrics

Which security best practices does the project follow (for example CNCF best practices badge, OpenSSF Best Practices, CLO monitor), and how does it rate by these metrics?

### Static Analysis

Does the project perform static analysis?

## Sub-project Considerations

If the project has sub-projects, how does their security posture compare to the base project?

## TAG Recommendation to the TOC

**Comment by mnm678** [comment]
Thank you for the presentation!
