### ISSUE TITLE
[Presentation] Kexa introduce to sandbox

### ISSUE THREAD

**Issue by estebanmathia** [cncf/tag-security#1340]
Title: Verifying multiple cloud providers for security, compliance & costs optimization with a Github Action
 
Speakers: Adrien EPPLING @aeppling & Esteban MATHIA @estebanmathia
 
Description: We've been working on this project for one year now, and we are now willing to find our first user base, we can present you few use cases that demonstrate how the project can be used in various situation and at different scales. We could also discuss about the community aspect we wish to develop!
 
Time: 20 minutes (demo) + speak
 
Availability: Speakers will be based in Europe, we can adjust our availability to fit a time slot.
We can present to you as from 12/07
 
 
TO DO
- [x] TAG Representative
- [x] Schedule date
- [x] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](../CONTRIBUTING.md#present-to-the-tag)

**Comment by mrcdb** [comment]
hi @estebanmathia ! we can schedule you for one of the next bi-weekly EMEA meetings at 1PM UK time, these are the next available dates:
- 11/9
- 25/9
- 9/10

Please let me know if any of these suits you and I can update the agenda.

**Comment by estebanmathia** [comment]
Hello, we can be available for 25/09 at 1PM UK time

**Comment by mrcdb** [comment]
You have been scheduled or 25/09 at 1PM UK time. The meeting has recently transitioned to LFX. This is not yet reflected in the README but will soon. This is the link: https://zoom-lfx.platform.linuxfoundation.org/meeting/98348738138?password=70e6a945-563a-491f-8485-ecf7394ec13a

**Comment by mrcdb** [comment]
Thanks for the presentation today @estebanmathia and @aeppling! Could you share the link to the slides so we add it to the meeting notes doc?

**Comment by aeppling** [comment]
https://www.canva.com/design/DAGRj5pK4zQ/-3DfABMwI8S3EokVzCVs3g/edit?utm_content=DAGRj5pK4zQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
