### ISSUE TITLE
[Presentation] Secure Identity and Context in Microservices with Tratteria

### ISSUE THREAD

**Issue by tulshi** [cncf/tag-security#1359]
Title: Secure Identity and Context in Microservices with Tratteria

Speakers: Atul Tulshibagwale/tulshi

Description: 
[Tratteria](https://tratteria.io/) implements a new IETF OAuth WG draft called "[Transaction Tokens](https://datatracker.ietf.org/doc/draft-ietf-oauth-transaction-tokens/)" (TraTs). TraTs are short-lived signed JWTs that provide immutable identity and context information in microservices call chains.  By providing such immutable context, TraTs prevent attacks like software supply chain, privileged user compromise or malicious insiders, because microservices automatically deny calls that do not have such TraTs associated with them, or the parameters of the call do not match an associated, valid TraT.
 
Tratteria is a Kubernetes-native framework designed to facilitate the adoption of TraTs in existing applications to secure their call chains. The framework consists of a TraT issuance service, a Kubernetes custom controller for configuration management, and sidecar agents for verifying TraTs. Tratteria requires applications to implement the SPIFFE for service-to-service trust. TraTs generation and verification policies for APIs are described using Kubernetes Custom Resources, allowing applications to describe their services, API endpoints, and immutable context elements (such as path and query parameters, headers, and body elements). Convenient defaults let applications reuse such policy descriptions across a number of microservices. Tratteria documentation includes a tutorial on why TraTs are required, what they are, and how to use them in existing applications. It has a quickstart guide that provides a sample application, which uses the Dex IdP for user authentication and shows the TraTs to the user. While Tratteria can operate alongside service meshes such as Istio, ongoing development aims to optimize this integration, potentially leveraging existing Istio capabilities for improved overall functionality.

Time: Approximately 30 minutes

Availability: Sep 4 10 AM PT, Sep 18 10 AM PT, Oct 2nd 10 AM PT or Oct 9th 10 AM PT.

TO DO
- [ ] TAG Representative
- [ ] Schedule date
- [ ] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](../CONTRIBUTING.md#present-to-the-tag)
- [ ] If this is a presentation for a project moving levels, the TAG Representative should complete the [Moving Levels Recommendation](../project-resources/moving-levels-review-template.md)

**Comment by y-tabata** [comment]
@eddie-knight We need to schedule a date.

**Comment by mrcdb** [comment]
hi @tulshi 

The next available date in the AMER timezone is October 2nd at 10 AM PT, would it still work for you? Thanks!

**Comment by tulshi** [comment]
Hi Marco,
That time works for me. How long should the presentation be?

Thanks,
Atul

**Comment by mrcdb** [comment]
Hi @tulshi , the meeting link for the EMEA Zoom meeting is up to date.  Looking forward to the presentation on October 2nd!

**Comment by tulshi** [comment]
The 10 AM PT slot has the name "North America..." for the Oct 2nd meeting.
I suppose that is the correct one (not EMEA)?

**Comment by mrcdb** [comment]
You are absolutely right, as you will be joining the NA meeting. Sorry!

**Comment by tulshi** [comment]
Thank you, Security TAG for your time today. If you have any questions please let me know in this issue or email me at atul@sgnl.ai. Please also let me know of any next steps.

**Comment by jkjell** [comment]
Presentation completed.
