### ISSUE TITLE
[Proposal]  TAG-Runtime and TAG-Security Collaboration project - Cloud Native AI Security Whitepaper

### ISSUE THREAD

**Issue by dehatideep** [cncf/tag-security#1374]
Description: what's your idea?
In the last couple of years following whitepapers have been published by respective CNCF TAGs:
[Cloud Native AI Whitepaper](https://tag-runtime.cncf.io/wgs/cnaiwg/whitepapers/cloudnativeai/) - TAG Runtime (AI Workgroup)
[Cloud Native Security Whitepaper](https://tag-security.cncf.io/community/resources/security-whitepaper/v2/cloud-native-security-whitepaper/) - TAG Security 

Now, TAG Runtime is starting on a [Cloud Native AI Security Whitepaper](https://github.com/cncf/tag-runtime/issues/177), which needs expert from both TAGs or at the least get to benefit from each other expertise/experience.

This issue is raised to get answers for followings:
1. How this project can be run in a collaborative fashion by above two TAGs? 
2. Joint ownership of the project/final artifacts - what is to be done, if anything?
3. What could be the best way to proceed on this one and if creating a cadence for this one is a way to go, given people from both sides need to work together.
4. What processes we have or may need to create in the tag-security for this collaboration?

Impact: Describe the customer impact of the problem. Who will this help?  How
will it help them?

This is about CNCF internal processes for the collaboration among TAGs for a given deliverable.
* Note that this is particularly about "Cloud Native AI Security Whitepaper" which involves collaborating with TAG Runtime but it could be true for collaboration with any other TAG within CNCF.

Scope: How much effort will this take? ok to provide a range of options if or
"not yet determined" for initial proposals.  Feel free to include proposed tasks
below or link a Google doc
This is to be discussed among TAG Security and STAG leadership and simply find a suitable way to collaborate with TAG Runtime (or any other TAG in the future).

Intent to lead:

* [ ] **I volunteer to be a project lead on this proposal if the community is
  interested in pursing this work.** This statement of intent does not preclude
  others from co-leading or becoming lead in my stead.

Proposal to Project:

* [ ] Added to the planned meeting template for _mm dd_
* [ ] Raised in a Security TAG meeting to determine interest - _mm dd_
* [ ] Collaborators comment on issue for determine interest and nominate project
  lead
* [ ] Scope determined via meeting _mm dd_ and/or shared document *add link*
   with call for participation in #tag-security slack channel thread *add link*
   and mailing list email *add link*
* [ ] Scope presented to Security TAG leadership and Sponsor is assigned

TO DO

- [ ] Security TAG Leadership Representative:
- [ ] Project leader(s):
- [ ] Issue is assigned to project leaders and Security TAG Leadership
  Representative
- [ ] Project Members:
- [ ] _Fill in addition TODO items here so the project team and community can
  see progress!_
- [ ] Scope
- [ ] Deliverable(s)
- [ ] Project Schedule
- [ ] Slack Channel (as needed)
- [ ] Meeting Time & Day:
- [ ] Meeting Notes (link)
- [ ] Meeting Details (zoom or hangouts link)
- [ ] Retrospective

**Comment by jkjell** [comment]
This will be proposed to the Commons WG.

**Comment by dehatideep** [comment]
Update on this collaboration:
1. AI Security whitepaper is a deliverable of tag-runtime and this task group meets every 1st and 3rd Fri of the month at 8 am PT. https://zoom.us/j/9890721462?pwd=N2xyRkZaN2JWZkNmS3EzbE1HVnhEQT09
2. Tag-Security folks would have a chance to contribute and review the paper. Docs are at: https://drive.google.com/drive/folders/1luVtzJRlkekc2_5ovV0RjvIPpQTcbWot
3. Tag-Runtime leads will keep TOC apprised to make sure this whitepaper is a go-ahead and aligns with serves the purpose. Some of the folks in TOC actually are part of this paper task group, so TOC is aware.

Collaboration model: Tag-Runtime owns and will carry forward this paper and will rope-in tag-security for review. Of course tag-security folks can vey well be the contributor to this paper. Some of the folks already are doing it.

With this model, this issue itself can be closed.

**Comment by dehatideep** [comment]
Collaboration model as explained above is established. No further action is needed.
