### ISSUE TITLE
[Suggestion] Approval process for PRs of a WG

### ISSUE THREAD

**Issue by vikas-agarwal76** [cncf/tag-security#1376]
Description: As part of the Compliance WG we want to add and manage content within our Compliance folder community/working-groups/compliance in the TAG-Security github repo. Since every time a content is added/updated we need to create a PR and a Tag-security maintainer needs to approve/merge it. If the WG content is updated frequently it will require involvement of the TAG-Security maintainer to approve it every time.

One option we discussed in the Compliance WG call last time was to see if it is possible to have folder level approval process. I believe using CODEOWNERS file we can allow approvers for specific folder in the Tag-security github repo. Will it be possible to use this option to add 2-3 approvers for compliance folder so that we don't need to bother the TAG-Security maintainers every time we need to update the content?

The other option is to follow the current process of TAG-Security maintainer approving every PR for content update within Compliance WG folder.

Would like to understand which option works best for the TAG or if there is any other alternative.

**Comment by vikas-agarwal76** [comment]
Hi, not sure if the TAG got a chance to discuss this. Any suggestion on various options acceptable to TAG would be highly appreciated.

**Comment by eddie-knight** [comment]
Hi @vikas-agarwal76, this was highlighted on today's EMEA community call. Would you be available to join the AMER community call later today to discuss this?

This may relate to some ongoing discussions between the WG leads (@rficcaglia and Anca) with the recently appointed STAG representative (@brandtkeller)

**Comment by sunstonesecure-robert** [comment]
@vikas-agarwal76 @brandtkeller  the preference of the STAG was:

> follow the current process of TAG-Security maintainer approving every PR for content update within Compliance WG folder.

@brandtkeller promises to jump on PRs if we @ him on these so let's give this process a try and if we need to revisit, we can do so

I'd recommend closing this for now and re-open if the approvals are either overwhelming for Brandt or not working for the WG teams. thanks!
