### ISSUE TITLE
[Proposal] Can you please add the way automatically set estimates field of Story Points

### ISSUE THREAD

**Issue by coloredpanda** [cncf/tag-security#1385]
Description: it would be great to have an option of setting estimates field somehow

Impact: Currently we're asked to size the work and when Story Points field is empty it raises the questions, we need a way to make it clear that we estimated the effort (usually because it's automated field will be set to 0). So the impact is less work from administrative side of things.

**Comment by eddie-knight** [comment]
Hi @coloredpanda, I think this is the wrong location for the discussion you've raised. Please reach out to me on Slack if there is something else to discuss regarding the TAG.
