### ISSUE TITLE
Updating docs - "security review" to "security assessment"

### ISSUE THREAD

**Issue by pedroignacio13** [cncf/tag-security#1409]
Since the formerly "Security Review" process is being updated to "Security Assessment" process, we should update the various pages of the documentation that have a reference to the old "Security Review" process.

**Comment by pedroignacio13** [comment]
I'd be happy to help with this issue if it's considered important.

**Comment by eddie-knight** [comment]
@pedroignacio13 Absolutely, I think it would be great if you'd like to put up a pull request to help establish consistent language throughout the repo.

**Comment by pedroignacio13** [comment]
For sure, my brother. I'll start working on it this week and will keep you posted.

**Comment by pedroignacio13** [comment]
Hi @eddie-knight , I just created the PR to update our website.
The PR number is #1411 .
Feel free to hit me up on Slack if you have any doubts!

**Comment by pedroignacio13** [comment]
PR #1413 opened to fix terms on TAG Security's website.

**Comment by mrcdb** [comment]
@pedroignacio13 PR merged, thanks! I think we can close this issue now.
