### ISSUE TITLE
[Proposal] Guidance for projects on evaluation and tracking security dependencies

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/tag-security#155]
This has come up in discussions in meetings about whether we might help projects through the assessment process by recommending best practices or common techniques for projects to consider, evaluate and track security of their dependencies

@lumjjb comment
> Within the ecosystem, is there a concern of delegation of security responsibilities from one project to another and vice versa? Perhaps a project is relying on security mechanisms of another CNCF technology which has not been reviewed yet? How would this affect the security posture of the project? I suppose that this would be a rare case that can be handled whenever it comes up.

**Comment by ficcaglia** [comment]
Taking a cue from Ash's OPA write up he mentions the CII badge framework so I posted a "worksheet" in https://github.com/cncf/sig-security/issues/153#issuecomment-487657305

**Comment by mattklein123** [comment]
FYI this is an issue we are planning on putting a considerable amount of effort into within Envoy. See https://github.com/envoyproxy/envoy/issues/10471 for more information and discussion. From my perspective there is a lot of overlap between what we need to do for Envoy and what other projects also need, so it would be a shame to duplicate effort.

Is this worth a chat in one of the SIG meetings? cc @htuch @justincormack

**Comment by justincormack** [comment]
Yes I think it would be a good discussion topic, with the aim of trying to set up a useful outcome for projects eg guidelines, working group, amendments for CII or whatever seems most useful.

**Comment by htuch** [comment]
Please count me in on any meeting here. We are likely to formulate an Envoy-side policy as a starting point, but would like to ensure it has alignment with best practices across CNCF. Our main focus is in the C++ dependency space and establishing a consistent set of guidelines for when it is reasonable to add an additional dependency to Envoy. We are also interested in tooling that can allow us to propagate dependency information to determine the security posture of Envoy components such as extensions.

**Comment by anvega** [comment]
@mlieberman85 is currently reevaluating this proposal as part of the supply chain security workgroup

**Comment by mlieberman85** [comment]
Will write something a bit more extensive up later but the gist of what some folks have been asking for is:

- A self-assessment for supply chain security best practices with Guidance on how to hit the requirements, e.g. SSCP.
- An automated assessment along with automated remediation of any gaps, e.g. OpenSSF Scorecard
- Some sort of program sponsored through OpenSSF to help provide security help on certain CNCF projects that critically need it.

**Comment by anvega** [comment]
The scope of this proposal has been subsumed by the charter of the TAG's Supply Chain working group, and it's captured as an active effort that they are driving towards to. We'll close this proposal as this is now acted upon the workgroup's active efforts.
