### ISSUE TITLE
write up more detail on how we organize security reviewer teams 

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/tag-security#160]
@JustinCappos @justincormack @lumjjb and I met and discussed how to organize teams for the security audits.

Here are notes which may only make sense to the people who were present -- capturing them here in advance of PR with better explanation

![image](https://user-images.githubusercontent.com/41906/57339311-ee56d300-70e5-11e9-9f4a-9ff6c43c8b4f.png)

- Group of 10 people in the security assessment team
- Build a broader community
- Each do 2, which will then be 5 assessments total, then retrospective

Good idea to have 3 when possible
Lead do an initial through review, ask dumb questions, make the doc clear

Timeline
- 48 hours “dumb question phase” — ask a bunch of clarifying questions to make the document clear about 
- 5 days, where review team forms an opinion 
- Presentation (could be separate meeting)
- Summary info
    - Like an executive summary of page of an audit
    - Slide too

**Comment by rficcaglia** [comment]
I think the dumb question phase might be a bit optimistic...I had prior detailed understanding of OPA and even with that, I had several passes at the write up, the OPA code, the supporting documents (security audit), etc...and with other work items and travel and such, I think a work week (5 biz day) window seems more realistic, especially for a project I had never looked at before in any functional way.

From that I would then be equipped to actually form an opinion.

So I guess I am advocating for:

- 5 biz day discovery and Q&A cycle
- 5 biz day Team cycle (including presentation prep?)
- 1 biz day presentation and summary info

**Comment by ultrasaurus** [comment]
Sorry not to be clear in the notes.  The "dumb question" phase is for a single person (usually the lead security reviewer) to take a pass through the doc and ask clarifying questions.  Then the discovery cycle begins (which could include clarifying questions, but we save security questions until each reviewer has had the chance to review separately.

**Comment by TheFoxAtWork** [comment]
closing as the recent security assessment process updates have likely changed/addressed this.  can be reopened if need be.
