### ISSUE TITLE
Provide expertise on TOCTTOU, crypto usage, and related topics

### ISSUE THREAD

**Issue by JustinCappos** [cncf/tag-security#168]
Security issues come up in different organizations and a trend is that even large, well-resourced companies seem to end up with solutions that still contain weaknesses and/or could be improved.  This is especially true in situations that deal with crypto algorithms or race conditions (notably Time-Of-Check-To-Time-Of-Use bugs).  

We should have a smaller subgroup (to control the disclosure of sensitive items) that can help with these issues.

**Comment by justincormack** [comment]
I think providing support when projects have security issues is definitely something that could be done, was this the circumstance you were thinking of, or at other times?

**Comment by JustinCappos** [comment]
Yes, I've seen quite a few situations like this crop up.  I think we tend to hear about these things through blog posts, deep dives, etc.  In many cases, folks in the security group may have already seen this situation happen many times and/or worked with groups to fix these issues.  We're not being used as a resource for these issues and we really should be...

**Comment by lumjjb** [comment]
I agree very much with @JustinCappos that I often see many instances of TOCTTOU bug instances especially around assumptions around atomicity of resource interactions in k8s apiserver or etcd kv store. 

Along the lines of common mistakes, having an OWASP top 10 style Wiki could be a good resources as well.

**Comment by cloudsriseup** [comment]
@JustinCappos agreed.  Much needed.

**Comment by lumjjb** [comment]
Potential topic for #110 , closing issue in favor of microsite issue.
