### ISSUE TITLE
Threat modeling 

### ISSUE THREAD

**Issue by tpepper** [cncf/tag-security#171]
KubeCon EU presentation on security audits mentioned a finding / recommendation for projects to understand their threat model, but this feels overly abstract.

Should an input criteria to a CNCF sec audit be that the project have a threat model documented? CNCF is suggesting projects follow the LF’s CII best practices recommendations, but that doesn’t require a threat model.

Even if not required, I suspect threat modeling education by the SIG out to it’s associated projects would have value as many many software engineers are unfamiliar with what establishing one entails and exceptionally few projects have them.

**Comment by omerlh** [comment]
I think this is a really good proposal, we should at least recommend the project to have it - and maybe set it graduation criteria. There are some discussions on how to document, I have some example I wrote [here](https://kamus.soluto.io/docs/threatmodeling/threats_controls/) and will be happy to hear feedback about the format and readability.

**Comment by lumjjb** [comment]
I believe we do ask for some threat modeling when performing security reviews for the CNCF projects - is that along the lines of what you have in mind?

**Comment by omerlh** [comment]
Interesting, where does it documented?

**Comment by JustinCappos** [comment]
This is listed in the security assessment docs that the project submits to the SIG-Security working group.  I'll list a few examples here:  
https://docs.google.com/document/d/1O3O7eFCTZ_7lLZ9IhHSWFiXhjWf2gPuJbzZ7u0m-9uI/edit?pli=1#heading=h.oykub2ep8ndw
https://docs.google.com/document/d/1L15ZZXnDxe3eqXnKHiZRxdr59tGkt_ipPixdA6RbzII/edit#heading=h.4zw236cia0t9

**Comment by TheFoxAtWork** [comment]
This is issue is completed initially with PR #349.
