### ISSUE TITLE
CVEs for vulnerabilities found during security reviews/audits

### ISSUE THREAD

**Issue by TheMoxieFox** [cncf/tag-security#177]
I am submitting this as a proposal from a DM twitter conversation with @justincormack 

The scoring criteria used for ranking vulnerabilities found during security audits is not published,  per @justincormack 's suggestion, this is perhps based on the same criteria used for CVSS scoring.

**Proposal**: Given the above assumption, why are not all vulnerabilities discovered during CNCF security review/audit registered as CVEs following a responsible disclosure process?

**Background**: Early adopters looking exploring the CNCF landscape may experiment and use projects/products and deploy them in either an initial low impact production workload or for testing purposes.  Given the very nature of the cloud landscape, many of these deploys occur in an internet accessible domain.  If a vulnerability is discovered during the current process of the review/audit, end users have a difficult time finding them to understand the need to update/patch.  CVEs naturally, are easier to patch and many organizations already monitor publications to the national vulnerability database.  

**Justification**:  Naturally CVEs are easier to track and monitor and reach a wider audience than vulnerabilities squirreled away in hard to find reports.  As the Security SIG of CNCF, publishing these vulnerabilities _after following a responsible disclosure process_ in a industry standard database is the natural progression of the review process.

**Additional Thoughts**:  It is unclear if the conditions for graduation into the CNCF is inclusive of 0 Critical or High findings.  If these conditions do not exist, it is _strongly_ recommended they be included as the CNCF brand is considered (to many in the community right or wrong) as an endorsement of a product or project.  If these conditions do exist, they should be more widely known (I do not find such evidence readily available).

**Comment by joshuagl** [comment]
This is an excellent idea, it might be valuable for CNCF to become a CVE Numbering Authority (CNA) for member projects.

Red Hat has a good open source focused write-up about CVE assignments: https://github.com/RedHatProductSecurity/CVE-HOWTO

**Comment by rficcaglia** [comment]
I look to @ultrasaurus to advise whether the charter of the SIG is so tactical in scope (eg. finding specific CVEs) vs. more strategic (e.g. how do you design a secure CN system/component.)  I think finding tactical, practical attacks with specific examples that warrant a CVE is best owned by the much larger community of users and researchers (who can be informed by SIG discussions to be sure).

Perhaps the SIG review process is not explicitly looking for CVEs but rather pointing out to the borader community areas they should be looking at for CVEs.

**Comment by ultrasaurus** [comment]
I read this as a process improvement recommendation.  I agree that if the SIG assessment or code audit were to find a security vulnerability, tracking as a CVE seems like a good idea.  

@JustinCappos had talked about writing up an issue tracking process. I don't see an issue for that, so maybe we didn't write it down yet.  Please link if it exists, or just chime in here!

**Comment by TheMoxieFox** [comment]
Solely as a process improvement.  If a vulnerability is found it should be submitted as a CVE following responsible disclosure with the company in question.  If the assessment or audit is providing scoring on a vulnerability found as a result of said activity, it should adhere to industry accepted standard proceed for vulnerabilities. Especially if the scoring is based on cvss.

 
 
  On Wed, 29 May 2019 at 16:39, Sarah Allen<notifications@github.com> wrote:   
I read this as a process improvement recommendation. I agree that if the SIG assessment or code audit were to find a security vulnerability, tracking as a CVE seems like a good idea.

@JustinCappos had talked about writing up an issue tracking process. I don't see an issue for that, so maybe we didn't write it down yet. Please link if it exists, or just chime in here!

**Comment by JustinCappos** [comment]
I'd like to defer to @zparnold on this.  He's thought a lot about this process and should help to shape it...

**Comment by ultrasaurus** [comment]
related issue discussed in TOC meeting today: https://github.com/cncf/toc/issues/213

**Comment by cloudsriseup** [comment]
"... If a vulnerability is found it should be submitted as a CVE following responsible disclosure with the company in question.  If the assessment or audit is providing scoring on a vulnerability found as a result of said activity, it should adhere to industry accepted standard proceed for vulnerabilities. Especially if the scoring is based on cvss..."   

Strongly agreed.  The process is simple.

**Comment by TheFoxAtWork** [comment]
This is complete as of the PR to provide security resources.
