### ISSUE TITLE
Key Elements of a Trustworthy System

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/tag-security#20]
The working group will outline the common problem of the fragmented and isolated security in distributed infrastructure, refine the requirements for a solution, and discuss the constraints and tradeoffs.  

We will initially collaborate via google doc, and later turn into a more formal recommendation.  For now, please add comments, ideas and question to the doc linked below:

"Key Elements of a Trustworthy System” [google doc](https://docs.google.com/document/d/11gyDDsKtMchMlj9ZKDl5LSHNxgu04tq1dTSD1BnTG9o/edit)

**Comment by justincormack** [comment]
I cant access that doc - I requested access but I wonder if there is an undocumented Google Group for Safe as well?

**Comment by TheFoxAtWork** [comment]
@pragashj recommends deferring until landscape project is complete

**Comment by pragashj** [comment]
Should we see how much of this can be incorporated in to the landscape? 
https://github.com/cncf/sig-security/issues/348
If not, we can work to create more clarity on this issue to see what we can cover here that is different from whitepaper and landscape.

**Comment by cseader** [comment]
What is the overall purpose of this? It seems the white paper addresses the needs here.

**Comment by lumjjb** [comment]
Addressed by Cloud Native Security Whitepaper  https://github.com/cncf/tag-security/tree/main/security-whitepaper
