### ISSUE TITLE
[Suggestion] Define security testing requirements 

### ISSUE THREAD

**Issue by omerlh** [cncf/tag-security#215]
Description: 
Define different types of security testings that we expect CNCF projects to run continuously. Consider defining levels of maturity, e.g. all projects must scan the dependencies used, optional is to run SAST/DAST and how we can reflect those levels (badges?).
Consider also defining the required tools that are considered as "good enough" - might be risky, as we'll have to endorse specific tools/vendors. OWASP projects could be a good start (Zap, dependency track, etc).

Impact: Describe your hopes for how this would reduce risk for the cloud native ecosystem. Who will this help? How will it help them?
Security testing helps to catch various security issues before merging. Ideally, issues like prometheus/prometheus#5580 will be detected earlier and not reported by external users.

Scope: How much effort will this take? ok to provide a range of options if or "not yet determined" 
Small effort to define "maturity levels", a lot bigger effort to go over existing projects and map them to the right level, communicating the change etc.

**Comment by raesene** [comment]
If we're looking at maturity for application security, which seems like a good approach, I'd recommend looking at the OWASP Application Security Verification Standard (ASVS).

It's an actively maintained project which defines maturity levels for application security and suggests lists of requirements or tests that can be used to assess applications at varying levels

https://www.owasp.org/index.php/Category:OWASP_Application_Security_Verification_Standard_Project#tab=Home

**Comment by omerlh** [comment]
Yes, that's a great suggestion. ASVS is pretty long, so maybe it's better to create a subset of it.

**Comment by ultrasaurus** [comment]
It would be good to look at the CNCF Audits and draw from already documented practices.  

Also consider referencing (rather than duplicating), relevant criteria from [CII Best Practices Security](https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#security)

**Comment by ultrasaurus** [comment]
Also, I think the initial assessment of https://github.com/prometheus/prometheus/issues/5580 was that these were false positives... it would be good to include guidance on how to catalog / respond to discovery of false positives.  I imagine this may come up a lot with open source projects where companies typically do security audits themselves and may need help triaging reported issues.

**Comment by rficcaglia** [comment]
Having used the CII criteria to review OPA and Falco, I don't see a strong argument AGAINST using CII as the MVP for assessment criteria.  Can anyone articulate how the CII criteria fail to meet the goal?

**Comment by omerlh** [comment]
It's actually pretty good, I never saw this list. it's more practical compared to ASVS, I'll be happy to see all CNCF project using these criteria. I filled an issue to add a threat model to the criteria (see coreinfrastructure/best-practices-badge#1302)

**Comment by rficcaglia** [comment]
CII does discuss threat models for higher badges:
https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md#documentation_security

**Comment by rficcaglia** [comment]
Not recommending any particular methodology or format but this is an
informative example from OWASP:
https://www.owasp.org/images/a/aa/AppSecEU2012_PASTA.pdf

**Comment by cloudsriseup** [comment]
BSIMM has a decent section on testing - https://www.bsimm.com/framework/software-security-development-lifecycle/software-security-testing.html  .  Other sections include the third party libraries (open source) risk mgt. challenges, and answering many of the questions above.

**Comment by ficcaglia** [comment]
@mhausenblas  just wondering - can we close this particular issue if we add to the microsite in some sort of "resources" list or FAQ?

**Comment by mhausenblas** [comment]
I like the idea of a FAQ and happy to add that. Unsure if that means we want to close this issue right now or when the site is up.

**Comment by omerlh** [comment]
I'll be happy to work on this if someone is willing to mentor and guide me in the process.

**Comment by anvega** [comment]
A portion of this is captured in the OpenSSF Best Practices and another piece is covered in the SSF Reference Architecture. Closing this issue as it has been stale for a few years although feel free to reopen if you feel the ask still stands.
