### ISSUE TITLE
what is "formal verification" policy overview for?

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/tag-security#272]
See https://github.com/cncf/sig-security/issues/196 for notes on discussion in policy team meeting and subsequent PR https://github.com/cncf/sig-security/pull/242 wrote up notes to close the issue... it got merged without clarification on what it is and how/whether it relates to ongoing work of the group.

- is this a recommendation?
- is this a description of an on-going project?  (if so, there should be an issue tracking it and we should retrofit process: https://github.com/cncf/sig-security/blob/master/governance/process.md)
- or is this just notes from the group?  (e.g. for people interested in formal verification, here's a writeup of what that means)

I had a couple of people mention to me over the past year that they felt "formal verification" was impossible yet the doc seems to at times simply define the kind of verification done by OPA and other solutions.  If it is really seeking to "prove" correctness, then that needs to be made clear and maybe document that this is experimental.

**Comment by ultrasaurus** [comment]
@rficcaglia perhaps you can answer these questions?  I think it could be addressed in some intro at the top that would help situate the document (in parallel with https://github.com/cncf/sig-security/pull/268 that should provide some context)

**Comment by rficcaglia** [comment]
> I had a couple of people mention to me over the past year that they felt "formal verification" was impossible

I encourage all those with opinions and feedback to liberally add to the document and/or GHI comments,  especially with case studies and even more welcome are "anti" case studies.  

However, "impossible" is somewhat incompatible with the documentation that both Azure and AWS use formal verification and reasoning for provable security in their production cloud platforms. AWS has published a great deal about it here:

https://aws.amazon.com/security/provable-security/

and it forms the basis of several their production products, ie it's not just academic research. Azure's documentation is more diffuse, but it seems from my searching, if anything Microsoft has done even more work in this area than AWS.

How this relates to the group is probably best left as a group discussion. I'll just opine that If the leading cloud vendors use it as a [core/significant](http://highscalability.com/blog/2018/9/19/how-do-you-explain-the-unreasonable-effectiveness-of-cloud-s.html) part of their cloud security, it seems that it should be considered as part of discussing security for any cloud native system in some way or another, even if to determine that for some cloud native systems it may not apply for specific reasons x,y,z.

I will note that formal methods are not policy specific.  in fact, probably the most common use of it is probably static program analysis, used for both the iOS and Android kernels, so in terms of # devices active in the world, it is arguably the most pervasive security tool deployed in the history of computing. That a particular use case (RBAC policy analysis, and separately network policy analysis) is of interest to the Policy WG is orthogonal to the larger impact/utility of formal methods.

**Comment by justincormack** [comment]
I would say at present this is notes for people interested.

Formal verification, for some use cases, is definitely not impossible. I think it can be helpful to see it as a particularly effective way of writing very comprehensive test cases, but that requires some work. Like anything else it is a tool, and its use is very dependent on exactly what you are trying to do, so I would think that concrete use cases that would be relevant would probably be in the form of specific projects related to formal methods for a particular domain of relevance.

**Comment by rficcaglia** [comment]
Here's a fairly balanced discussion:

https://www.hillelwayne.com/post/why-dont-people-use-formal-methods/

I think for use cases where 95%-99% confidence is acceptable, FM are probably overkill/cost prohibitive.  Where ~100% is worth the exponentially greater time and effort, then FM make some sense, e.g. iOS or Android kernels, high stakes financial smart contracts, RBAC logic in kubernetes (???)

But yes I agree with Justin that there is no silver bullet here. Just another tool in the toolbox.

**Comment by hannibalhuang** [comment]
The formal verification for cloud native policy is an experiment the policy team has been discussing this year. What @rficcaglia proposed was the design documentation of that idea, and for a trail of discussion regarding FV you could refer to [the policy team meeting minutes](https://docs.google.com/document/d/1ihFfEfgViKlUMbY2NKxaJzBkgHh-Phk5hqKTzK-NEEs/edit#heading=h.bcgxtrqp8rbt)

This is an experiment/direction that policy team is interested in trying out, with also collaboration with folks from the AWS Automated Reasoning group and possibly Azure. This is not a project proposal, not a formal decision of any kind, and not even a recommendation. 

The merged PR #242 is a design doc for a proposal that we believe is worthy documented under sig-security policy team effort. We could definitely rename/reorganize the folder to better reflect the experiment nature and unofficialness of the proposal. 

Also as @rficcaglia and @justincormack discussed above, FV is just one tool out of many, but it is an interesting tool and far from "impossible". Open source is all about trying out new ideas, and this is what the effort is about at its core

**Comment by ultrasaurus** [comment]
@hannibalhuang @rficcaglia @justincormack this is very good context -- consistent with what I've heard discussed and very aligned with what I would expect us to be doing in this SIG.  What's missing from the PR is exactly this kind of context.  I suggest a "background" section where the document is put into context with the SIG.  Also, I think it would be good to move the author to the top -- that would be consistent with a few other docs in the repo.

**Comment by ultrasaurus** [comment]
Catching up here and reading the [AWS paper](https://d1.awsstatic.com/Security/pdfs/Semantic_Based_Automated_Reasoning_for_AWS_Access_Policies_Using_SMT.pdf), it seems this is in a similar domain to Rego / OPA.  I believe the implication of the paper is that by using a policy language (and perhaps this specific policy language, ZELKOVA) then it is possible to verify that policies are expressed as intended. 

I apologize for my short-hand above.  I should not have said that formal verification of policy was impossible, rather that can only represent a subset of what is needed to verify the security of a system.  It may be obvious to you all, but would be good to situate this work amongst the other things that are needed (e.g. policy controls must also be securely implemented, etc).

**Comment by ultrasaurus** [comment]
@hannibalhuang @rficcaglia @justincormack would one of you be willing to take content from this thread and make a PR that clarifies the content in the repo?

...or @hannibalhuang / @ericavonb could raise at policy team meeting and see if someone else is up for scribing some clarifications and/or adding overview content.

**Comment by rficcaglia** [comment]
I think the last discussion relevant to this was pre-KUbecon when Christian
@ Google discussed some AI based verification, so it might be good to
update the content to compare and contrast how that tool works.  in any
event, yes this is due for an update and we can/should take it up at the
next policy WG session.

**Comment by anvega** [comment]
Although a big proponent of formal verification, I'm somewhat saddened the issue didn't spark enough discussion for activation energy to be reached either in the form of an ongoing project or different. There is now a tla+ foundation as part of The LF. That's a good redirection point for anyone who stumbles upon this issue. As the discussion has been stale for a few years, I'll close the issue.
