### ISSUE TITLE
Due Diligence of members and Disclaimers on content by the group

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#277]
Description: The SIG Security group should provide more transparent and explicit instruction/guidance/disclaimers to our members and to our audience/users regarding responsible use of the draft assessments.

Impact: Be more clear to new users and to members of the group while informing individuals that come across our draft docs or PRs.  Establishes expectations and "rules of the road" in addition to our Code of conduct

- There is some information in [outcome](https://github.com/cncf/sig-security/tree/master/assessments#outcome) section of overview doc.  We reviewed this in the 10/25 meeting and discussed the following ideas:
  - [x] include a stronger statement where the assessment is not a recommendation, but rather as an aid for organizations/individuals in selecting a project to meet their needs, not as a substitute for their own assessment
  - [x] maybe in this section or at top of page an explicit disclaimer about draft documents 
- [X] Add section to [CONTRIBUTING](https://github.com/cncf/sig-security/blob/master/CONTRIBUTING.md) about how we report issues that we find/discuss to the project/company and do not treat discussion (verbal, slack or draft doc) as a verified vulnerability in advance of going through format reporting process

**Comment by TheFoxAtWork** [comment]
i think the label needs changes to suggestion but not sure

**Comment by ultrasaurus** [comment]
Added some notes about what needs doing.  Added "enhancement" tag and "help wanted" since I think it just needs someone willing to write words for a PR.  

Anyone should feel free to do a small PR that covers part of this issue if you are inspired about how to draft text that is a specific improvement to address any of the items on the list or move the repo toward delivering the described impact.

**Comment by TheFoxAtWork** [comment]
Here is what i'm tracking for files to update:

- [ ] [Code of conduct ](https://github.com/cncf/sig-security/blob/master/CODE-OF-CONDUCT.md)- regarding appropriate use of the work from this group by individuals within the group (potential coverage concerns regarding competitive advantage, links to guidance on draft docs, etc.)
- [ ] [Outcome section Security Assements](https://github.com/cncf/sig-security/tree/master/assessments#outcome) include explicit language regarding what assessments are and are not, how to be used.  Explicit language of regarding items in draft
- [ ] Update [new members](https://github.com/cncf/sig-security/blob/master/NEWMEMBERS.md) to point to [contributing](https://github.com/cncf/sig-security/blob/master/CONTRIBUTING.md)
@ultrasaurus do we have a defined process for how this group handles reporting of vulnerabilities as part of our assessments?  the docs under assessments don't state what a member should do if they find something, how they report it to either the project or the assessment team... etc.

**Comment by TheFoxAtWork** [comment]
please assign this to me

**Comment by JustinCappos** [comment]
> please assign this to me

enjoy!

**Comment by TheFoxAtWork** [comment]
Going to submit PR less than the reporting of vulns as part of assessments... i believe this needs more discussion

**Comment by TheFoxAtWork** [comment]
https://github.com/cncf/sig-security/pull/285

**Comment by lumjjb** [comment]
Looks like the part on due diligence is merged. Let's tick those checkboxes :).

**Comment by lumjjb** [comment]
Adressed by PR, closing
