### ISSUE TITLE
[Suggestion] Develop a guide to security- privacy-related telemetry (via OpenTelemetry?)

### ISSUE THREAD

**Issue by knowlengr** [cncf/tag-security#278]
This is a placeholder for a liaison suggestion from Paul Bruce, a new member (Oct 2019) to work with OpenTelemetry.

See https://www.cncf.io/blog/2019/05/21/a-brief-history-of-opentelemetry-so-far/

**Comment by lumjjb** [comment]
Retagging as suggestion, unless we have someone that is taking this up.

**Comment by anvega** [comment]
Closing the issue as it has been stale over 3 years.
