### ISSUE TITLE
[k8s/wg-policy] Fold in Policy artifacts in to this repo

### ISSUE THREAD

**Issue by pragashj** [cncf/tag-security#288]
@hannibalhuang 
Can you please take care of the creating PR with getting the artifacts in to this repo.
Also can you publish the meeting information on the readme?
Thanks!

**Comment by lumjjb** [comment]
@hannibalhuang is this something that has been taken care of or requires attention?

**Comment by anvega** [comment]
See https://github.com/cncf/tag-security/tree/main/policy
