### ISSUE TITLE
[Suggestion] From Previous Calls...Can sig-security back project X?

### ISSUE THREAD

**Issue by rficcaglia** [cncf/tag-security#289]
Description:

Discuss “Can this be a Sig-security backed project?” This came up during the call 10/9 re: Falco’s security hub.  But it would also apply to many other initiatives/projects/research. (RPI in policy WG another example). What does “backed” mean practically? Is there value-add role for sig-security? Possible negative aspects of this?

- Pros

  - custodial/administrative/tracking?
  - Better communication/coordination with other SIGs and WGs?
  - Credible Stamp of approval on best practices?
  - Higher visibility for projects?

- Cons

  - We are still working out how to do assessments properly; taking on new stuff seems ambitious
  - Not having time to give something a stamp of approval might be interpreted as a negative signal where it’s not
  - Why are projects not succeeding on their own? Will this just become a graveyard for failed projects?  

- TBD

  - Is there inherently little/no incentive for security projects to succeed?  Is it that security doesn’t (immediately/predictably within the next quarter, etc) save anyone money, doesn’t make operators/businesses more money (except maybe security consultants/vendors)?
  - What structure/form would this take if it is a good idea? Like an pre-sandbox incubator? 
  - Is there CNCF TOC approval/sponsorship/funds?

Impact: 
Describe your hopes for how this would reduce risk for the cloud native ecosystem. 
Could be an incubator for otherwise unloved projects.

Who will this help? 
Overall community by better security.

How will it help them?
Advocacy for mo' better stuff.

Scope: 
"not yet determined"

**Comment by anvega** [comment]
Closing this issue as it has been stale for 3 years.
