### ISSUE TITLE
where to put assessment summary slides in the repo?

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/tag-security#343]
I don't think the [assessment summary slides](https://docs.google.com/presentation/d/1Cinwa2grYSdP4yNQKS1ICIBH3oSkBPgDZl2RlG5asRA/edit#slide=id.g5a0cdb412d_0_0) are linked from anywhere...

I would prefer an open format, but don't know of one that works well for slides.  In the meantime, these should be linked somewhere

**Comment by ultrasaurus** [comment]
@JustinCappos @TheFoxAtWork @lumjjb @rficcaglia  thoughts about where these should be linked?

**Comment by TheFoxAtWork** [comment]
@ultrasaurus I can see them either going in the individual project folder under assessments; [i.e assessments>projects>in-toto](https://github.com/cncf/sig-security/tree/master/assessments/projects/in-toto) , or under the projects folder to enumerate ones that are complete; [i.e. assessments>projects](https://github.com/cncf/sig-security/tree/master/assessments/projects)

**Comment by rficcaglia** [comment]
no strong opinion on where - I myself would think to look in
assessments>projects>project first.

as to open format haven't tried pandoc but maybe we can convert
markdown<->slides: https://pandoc.org/

**Comment by lumjjb** [comment]
Yea, i second the caution towards using binary blobs as they don't generally deal well with git diffing and history. I think having links initially to 1 set of slides that have all the 1 slide reviews would be okay to start with.

**Comment by TheFoxAtWork** [comment]
Can we re-scope this to just including the link in assessments>projects>project per @rficcaglia 's comment?  we could add it under Step 5 of the [Assessments guide](https://github.com/cncf/sig-security/tree/master/assessments/guide), simple enough to get started.  that would close out this issue.  If we need to we can address standard formatting as a separate issue.

**Comment by TheFoxAtWork** [comment]
This change is included in the #449 PR's (#479 & #488)  once those are merged we can close this.

**Comment by anvega** [comment]
https://github.com/cncf/tag-security/pull/479 & https://github.com/cncf/tag-security/pull/488) merged
