### ISSUE TITLE
[Presentation] Overview of Proposed NIST Big Data Analytics Initiative (and Cloud Mesh)

### ISSUE THREAD

**Issue by knowlengr** [cncf/tag-security#359]
Title: Overview of Proposed NIST Big Data Analytics Initiative (and Cloud Mesh)

Speakers: 
Wo Chang 
Digital Data Advisor
ISO/IEC JTC 1/SC 42/WG 2 Working Group on Big Data, Convenor
IEEE Big Data Governance and Metadata Management, Chair
NIST Information Technology Laboratory

Gregor von Laszewski [https://laszewski.github.io/](url)
Assistant Director, Digital Science Center
School of Informatics and Computing 
Indiana University

Description: A working group at NIST produced a reference architecture for Big Data which was released in three versions, the latest to be published later this year. A follow-on initiative around Big Data Analytics, which among many other facets would include safety, security and privacy considerations from the prior work, has been proposed. As part of this work, the Cloud Mesh framework developed at IU-ISC could be leveraged to provide design patterns from working code or, alternatively, form the basis of white papers to support best practices for analytics. 

The work is relevant to this SIG because analytics are seen by many as a key element in systems reliability, quality and cybersecurity. 

It has also been suggested that an exploration of this topic is useful to refine the scope of "cloud native," and to identify possible CNCF tooling or practices that could be used in the proposed effort.

For more on Cloud Mesh, see [https://cloudmesh-community.github.io/project/cloudmesh-nist/](url)

Time: How long will the presentation take? 40 min

Availability: Pending collaboration with Gregor.

TO DO
- [ ] SIG Representative
- [ ] Dan proposed 18 MAR, or a date in April (except 22 APR)

**Comment by ultrasaurus** [comment]
From meeting notes, looks like this presentation was given [2020-03-18](https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/edit#heading=h.jfxm33flneo) 

if that's true, it would be great to link slides / video

**Comment by anvega** [comment]
Presentation already took place.
