### ISSUE TITLE
[Suggestion] End-User presentation deck

### ISSUE THREAD

**Issue by cseader** [cncf/tag-security#362]
Description: What's your idea?
Create an End-User presentation deck which would have content relating to who SIG-Security is and what they do. Explains security concerns relating to cloud native. Sets a course for how you might incorporate security practices in your organization relating to cloud native. Give suggestions on what you might use for security in your CI pipeline. Information on Attack trees and how to do your own. Give a general overview of DevSecOps in relation to the above. etc.

Impact: Describe your hopes for how this would reduce risk for the cloud native ecosystem. Who will this help? How will it help them?
This will help anyone presenting to meetup's or other such groups interested in SIG-Security or interested in general with security relating to cloud native practices. This would be a value for anyone discovering how to move forward with security and CI/CD pipelines and give a general understanding of DevSecOps and what that can mean. 

Scope: How much effort will this take? ok to provide a range of options if or "not yet determined" 
Initial creation should only take about a week or few dedicated days of time to have a draft ready.

Thoughts welcome

**Comment by dshaw** [comment]
@cseader As I mentioned in today's meeting, check out the new [Contributor Strategy group](https://github.com/cncf/toc/pull/370) as potential partners to help validate this content.

**Comment by lumjjb** [comment]
@cseader Is there still interest in trying to pursue this?

**Comment by anvega** [comment]
Closing this issue as it has been stale for over 2 years.
