### ISSUE TITLE
[Suggestion] Define a review process for CNCF projects being considered for Graduation

### ISSUE THREAD

**Issue by ashutosh-narkar** [cncf/tag-security#367]
Description: When a CNCF project is being considered for Graduation status, it is recommended that the project first be reviewed by the appropriate SIG. For example, one of the suggestions in [Harbor's Graduation Proposal](https://github.com/cncf/toc/pull/311) is that the project be reviewed by Sig-Runtime, Sig-Storage and Sig-Security. 

This issue aims to get feedback around how to formalize the review process that Sig-Security would perform for projects looking to graduate. This would help projects get a clear understanding of the process that needs to be followed to get a recommendation from Sig-Security.

Couple of options that could help define this process:

- _Review the project's due diligence doc and make a recommendation_: This approach is similar to the process followed by Sig-Runtime in its review of Harbor. Their recommendation can be found [here](https://github.com/cncf/sig-runtime/blob/master/recommendations/graduated/harbor.md).

- _Use the [Security Assessments](https://github.com/cncf/sig-security/tree/master/assessments#security-assessments) process_:  Sig-Security has defined an in-depth process to assess the security aspects of a project. At the end of the assessment, the SIG-Security reviewers provide feedback as well. So a project looking to graduate that hasn't gone through a security assessment before, could be requested to go through this formal process in order to get Sig-Security's recommendation.
The benefit of using this approach, is that we already have a well-defined process in-place and  additionally we can leverage the [Updates and Renewal](https://github.com/cncf/sig-security/blob/master/assessments/intake-process.md#updates-and-renewal) flow of the Security Assessment process for projects that are looking to graduate and have already gone through the Security Assessment process in the past.
We would need to update the renewal process with more details than we currently have but in the long run the same process can be used for annual reviews and for the graduation recommendation.  As suggested in [this](https://github.com/cncf/sig-security/issues/326) issue, creating a section for _Critical Functions & Features_ would be a good first step.

__Update__:
The TOC recently updated the process/template for graduation. More details in [this](https://github.com/cncf/toc/pull/374) pull request.

**Comment by TheFoxAtWork** [comment]
This should be lightweight as we are still working through what a SIG Security Assessment process looks like, also refer and link to [TOC  PR 374](https://github.com/cncf/toc/pull/374)

**Comment by michelleN** [comment]
@ashutosh-narkar thank you for the feedback and suggestions. Given the updated, lightweight process @TheFoxAtWork referenced (#374), do you still feel we should add this level of detail to the graduation process. I think it makes complete sense for multiple SIGs to review a project however I don't think it will be needed for all projects that go through the process.

Optional SIG reviews can be kicked off (requested/suggested) by TOC members or SIG chairs during the period for public comment if necessary. If we agree on that, we should document it in the process and reference the examples you've outlined above. 

Happy to request this be added to the next TOC meeting for discussion if you'd like to come and talk more about. Also happy to let you lead any changes here. Thank you. cc/ @amye

**Comment by ashutosh-narkar** [comment]
Hello Michelle,

Thanks for your reply. The idea behind creating #367
<https://github.com/cncf/sig-security/issues/367> was to create a process
around how Sig-Security in particular would provide a recommendation for a
project looking to graduate. In Harbor's graduation proposal
<https://github.com/cncf/toc/pull/311>, getting a review from Sig-Security
was raised few months ago. So having a process in-place for such scenarios
seemed to be the right thing.

When I brought up #367 <https://github.com/cncf/sig-security/issues/367> on
the last Sig-Security call on 3/11, I was informed by @TheFoxAtWork
<https://github.com/TheFoxAtWork>  and @justincormack about your work on
#374 <https://github.com/cncf/toc/pull/374>. The process the TOC would
follow for graduation as you've outlined in #374
<https://github.com/cncf/toc/pull/374> is clear and looks good to me.

The "Optional SIG reviews" that you mention would be handled differently by
each SIG, correct ? And if yes, I was trying to get a conversation started
purely from the perspective of Sig-Security about how that process would
look and how we (Sig-Security) can streamline it for future projects.

Thanks
Ash Narkar

**Comment by TheFoxAtWork** [comment]
@lumjjb is this covered by our last TL discussion?

**Comment by TheFoxAtWork** [comment]
Related to new Security process changes in #479 & #488  as well as the Due Diligence process of #440

**Comment by anvega** [comment]
Closed as stale over two years. For the the lastest process see https://github.com/cncf/toc/tree/main/process
