### ISSUE TITLE
[Assessment] Quay Incubation Assessment

### ISSUE THREAD

**Issue by raravena80** [cncf/tag-security#386]
Project Name: 

Quay

Github URL:

TOC PR: https://github.com/cncf/toc/pull/386
SIG-Runtime Issue: https://github.com/cncf/sig-runtime/issues/16

Project proposal stage and issue (NA if not applicable):

Incubation.

The project has already presented to SIG-Runtime, but we need to do a security assessment just like we did with Harbor to see if there are any areas of concern. Update the findings at the end of the DD document: https://bit.ly/quay-dd-document

Security Provider: yes/no (e.g. Is the primary function of the project to support the security of an integrating system?)

- [ ] Identify team
   - [ ] Project security lead
   - [ ] Lead Security Reviewer
   - [ ] 1 or more additional reviewer(s)
   - [ ] Declaration of reading of [security reviewer guidelines](https://github.com/cncf/sig-security/blob/master/assessments/guide/security-reviewer.md) and declaration of conflits (by each reviewer)
   - [ ] Sign off by 2 chairs on reviewer conflicts
- [ ] Create slack channel (e.g. #sec-assess-projectname)
- [ ] Project lead provides draft document - see [outline](https://github.com/cncf/sig-security/blob/master/assessments/guide/outline.md)
- [ ] "Naive question phase" Lead Security Reviewer asks clarifying questions 
- [ ] Assign issue to security reviewers
- [ ] Initial review
- [ ] Presentation & discussion
- [ ] Share draft findings with project
- [ ] Assessment summary and doc checked into /assessments/projects/project-name (require at least 1 co-chair approval)
- [ ] CNCF TOC presentation (if requested by TOC)

**Comment by lumjjb** [comment]
@josephschorr Would be glad to start the ball rolling on this process. The first part of our process is the project to fill up a short security self-assessment (https://github.com/cncf/sig-security/blob/master/assessments/guide/outline.md) and we can work from there! Please reach out if you have any questions.

**Comment by BillDett** [comment]
Thanks- we're working on a first pass at the self assessment now and we will reach out if we have questions!

**Comment by BillDett** [comment]
Hello- sorry, this fell onto a back burner over the last month- we are continuing to work on it in the background!

**Comment by JustinCappos** [comment]
I'm going to close this issue as there seems to be no progress from the Quay project side.  If in the future, a self assessment is completed, please reach out and we will start the process anew.
