### ISSUE TITLE
[Suggestion] Simplify the Roles page

### ISSUE THREAD

**Issue by yeelinglam** [cncf/tag-security#398]
**Description**: provide an at-a-glance on all the roles currently available

**Impact**: clarify the list of roles, especially for prospect members

**Scope**: not yet determine and require discussions with the group

Additional Considerations:
- Add "Active Member" requirement section
- Tie it to current list of people serving in each role as a potential for shadowing for anyone who may want to take on a role in the future

**Comment by anvega** [comment]
Closing this as we moved away from membership list and we now document official tag leadership roles.

**Comment by szh** [comment]
Looks like https://github.com/cncf/tag-security/blob/main/governance/roles.md?plain=1#L44-L45 is out of date. Should it be removed? Or is there a different action that should be taken?

**Comment by mnm678** [comment]
> Looks like https://github.com/cncf/tag-security/blob/main/governance/roles.md?plain=1#L44-L45 is out of date. Should it be removed? Or is there a different action that should be taken?

It looks like that is left over from the previous process and can be removed.
