### ISSUE TITLE
[Proposal] Security Reference Architecture for Cloud Native Applications and CI/CD pipeline

### ISSUE THREAD

**Issue by vinayvenkat** [cncf/tag-security#405]
Description: Security Reference Architecture for Cloud Native Applications and CI/CD pipelines

Impact: Operators are being overloaded with a number of technologies pertaining to the cloud native eco-system. As a a result they find it difficult to operationalize different tools and capabilities. The purpose of this document is to make available a reference architecture that they can adopt in order to operationalize security for their applications throughout the build, deploy and run phases for container workloads. It provides an architectural reference of the interactions and integrations of various tools needed to secure container applications. 

Scope: The initial proposal can be accessed at: https://docs.google.com/presentation/d/1tzUc_Bi5dEV1N2Jf1Li3J1SWn7SFwp06mBJP9Rucdks/edit?usp=sharing

TO DO
- [ ] SIG Representative
- [ ] Project leader(s)
- [ ] TBD

**Comment by vinayvenkat** [comment]
@TheFoxAtWork Can you please assign this to me. Thanks!

**Comment by lumjjb** [comment]
@vinayvenkat is this effort part of the whitepaper/landscape now? Or do you still want this proposal to be something separate?

**Comment by TheFoxAtWork** [comment]
@vinayvenkat has this been covered in the white paper, will be covered by the landscape, or leveragable of the DoD DevSecOps reference architecture discussed in the 1/13 meeting?

**Comment by anvega** [comment]
Closing this issue as it has been stale for a few years. The https://github.com/cncf/tag-security/tree/main/supply-chain-security/secure-software-factory satisfies the ask of the issue.
