### ISSUE TITLE
[Suggestion] assesment outline: does "operation" belong in "intended use"?

### ISSUE THREAD

**Issue by itaysk** [cncf/tag-security#418]
Description: I was reading the https://github.com/cncf/sig-security/blob/master/assessments/guide/outline.md doc, and I saw that under "Intended Use", which describes the use cases and personas in high level, we ask for "Operation" which describes operational considerations of the application. This is a bit confusing because at this place in the document the system design hadn't yet introduced so diving into operational aspects, which will include internal terminology and familiarity with the design, might be confusing for the reader. (I'm also not sure semantic the relation to the use cases section). I think that the "Operation" part could belongs under "Configuration and Set-Up" which comes right after the "Design" section, or possibly in the design section.

Impact: Describe your hopes for how this would reduce risk for the cloud native ecosystem. Who will this help? How will it help them? 
Make the security assessment doc more readable and understandable

Scope: How much effort will this take? ok to provide a range of options if or "not yet determined" 
easy fix

**Comment by lumjjb** [comment]
Linking this issue when the review happens: https://github.com/cncf/sig-security/issues/167

**Comment by TheFoxAtWork** [comment]
@itaysk  does https://github.com/cncf/sig-security/pull/479 resolve this issue?

**Comment by anvega** [comment]
Closing this issue to inactivity. Also take it https://github.com/cncf/tag-security/pull/479 solves for the ask.
