### ISSUE TITLE
[Suggestion] Map usecases.md Users to OSCAL

### ISSUE THREAD

**Issue by sunstonesecure-robert** [cncf/tag-security#423]
## Description: What's your idea?

OSCAL has a schema definition in the SSP/implementation layer for User:

https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/ssp/json-schema/#user

and responsible roles:

https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/ssp/xml-schema/#global_responsible-role 

Map the suggested personas [here](https://github.com/cncf/sig-security/blob/9a2435d6323602be099626275cfeec4af87d840c/usecase-personas/README.md) to OSCAL definitions

_Note: these are not 1:1 mappings but possibly n:m_
 
- Operators: Enterprise, Quota, Network => asset-administrator, network-operations 
- Administrators: Security, Compliance/Audit = asset-administrator, asset-owner, security-operations, incident-response
- Developers, including Third Party Security Products => configuration-management, maintainer
- End-users => user, help-desk, security-operations, incident-response, asset-owner
- Platform Implementers => provider, maintainer, asset-owner

In addition cloud IAM platforms have lots of "predefined" roles which map to human level responsibilities, and generally map to resource read, write, or some action (eg. execute or similar):
https://cloud.google.com/iam/docs/understanding-roles#predefined_roles
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html

## Impact: Describe your hopes for how this would reduce risk for the cloud native ecosystem. Who will this help? How will it help them?

Provide a reusable and reviewable definition of user <-> role <-> responsibility types so that relevant permissions that can be forward engineered, reverse engineered and reviewed, version controlled, composed, verified, tested and reused.

Once these definitions have achieved consensus agreement, the concrete deliverable would be to oncorporate this into the whitepaper and map efforts. Then possibly in the future into specific tooling, eg. policy definition and assessment/enforcement tools.

## Scope: How much effort will this take? ok to provide a range of options if or "not yet determined" 

* 1 day for initial strawman, 7-14 calendar days to incorporate feedback
* 1 day to incorporate consensus definition into whitepaper and mapping documents; 7-14 calendar days to review
* TBD: incorporating these types into APIs or CRDs or other concrete tooling implementations

Additional info:

- [OSCAL](https://github.com/usnistgov/OSCAL)
- [Usecase personas](https://github.com/cncf/sig-security/blob/9a2435d6323602be099626275cfeec4af87d840c/usecase-personas/README.md)

**Comment by chasemp** [comment]
This is interesting to me, anything ever come of it?

**Comment by sunstonesecure-robert** [comment]
Not yet but still in motion.  I intend to present to the Policy WG probably
after the holidays.

**Comment by achetal01** [comment]
I am interested in contributing to this work stream....
Has the work started and is there a document with more detailed mappings of controls & use cases to OSCAL?

Thanks

**Comment by lumjjb** [comment]
Tagging policy WG folks just to ensure visibility. @hannibalhuang @ericavonb @rficcaglia

**Comment by sunstonesecure-robert** [comment]
Let's target the next Policy WG agenda - 12/23.  Will add to the agenda.

**Comment by TheFoxAtWork** [comment]
Wanted to check in here and see if this is worked under the Policy WG or does this need larger involvement?

**Comment by rficcaglia** [comment]
Happy to have larger involvement definitely! but we are working on this in
the Policy WG and specifically wrt the Policy Report CRD. the scope
naturally could be expanded into different areas of focus so by no means do
we have a monopoly on all use cases/users

**Comment by TheFoxAtWork** [comment]
Awesome !   Would you do a check in on this with the SIG meetings in February?  See if we can drum up some others to join in the fun.

**Comment by sunstonesecure-robert** [comment]
just FYI I think newer oscal has modified this to be:
https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/ssp/json-schema/#global_system-user

and now user type is an annotation:

> ALLOWED VALUES for system-user/annotation/@name
>The value may be locally defined, or one of the following:
>type: The type of user, such as internal, external, or general-public.
>privilege-level: The user's privilege level within the system, such as privileged, non-privileged, no-logical-access.

so I think the specific task here would be to define the type values for system-user

The [PolicyReport CRD](https://htmlpreview.github.io/?https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/docs/index.html) doesn't have any definition of user, there would need to be one. I can [raise it at the next discussion - of note it is a member of the assessment-results oscal schema](https://github.com/usnistgov/OSCAL/blob/aba66b5eafe6f53f28ab368e81c471a846f5aece/json/schema/oscal_assessment-results_schema.json#L1130).  We did discuss also having a component implementation - and [system-user is also a member of that schema](https://github.com/usnistgov/OSCAL/blob/aba66b5eafe6f53f28ab368e81c471a846f5aece/json/schema/oscal_component_schema.json#L942)

**Comment by david-waltermire-nist** [comment]
I am the Technical Director for the OSCAL project. I would be happy to talk with you about this use case if you have any questions. We can chat on the [OSCAL Gitter](https://gitter.im/usnistgov-OSCAL/Lobby). There is also a bi-weekly [OSCAL Lunch with the Devs](https://pages.nist.gov/OSCAL/contribute/dev-lunch/) where we talk about use of models. Perhaps we could touch base there? The next one is on 2/25.

**Comment by sunstonesecure-robert** [comment]
I also think [NICE Framework](https://www.nist.gov/itl/applied-cybersecurity/nice/nice-framework-resource-center) may be pertinent to this effort.

**Comment by anvega** [comment]
Closing this given the https://github.com/cncf/tag-security/blob/main/cloud-native-controls/phase-one-announcement.md was produced. If users were out of scope, will leave it to the determination of that working group to expand upon.
