### ISSUE TITLE
[Presentation] Trusted Service Identity (Bringing together SPIFFE/SPIRE, Keycloak, Keylime)

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#434]
Title: What is the title of your presentation? 

Trusted Service Identity (Bringing together SPIFFE/SPIRE, Keycloak, Keylime)

Speakers: Who will be presenting this? List names/github IDs of presenters.

@mrsabath
@lumjjb 

Description: Describe in a short paragraph what the presentation is about.

Trusted Service Identity by IBM Research is an effort to close the gap of preventing access to secrets by an untrusted operator during the process of obtaining authorization for data access by the applications running in the public cloud.The project ties Key Management Service and IAM, technologies with identity solutions as well as host provenance, integrity and hardware root of trust.

We aim to show how we are planning to bring together various CNCF projects: SPIFFE/SPIRE, Keycloak and Keylime to create a solution for providing high-assurance identity, authorization and global visibility. 

Time: How long will the presentation take? (estimate) 30-40 mins

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page. 

TBD

TO DO
- [ ] SIG Representative
- [ ] Schedule date

**Comment by cseader** [comment]
Why Keycloak? Why not Gluu?

**Comment by lumjjb** [comment]
Eventually we want to support both.. we started with keycloak first because of our familiarity with the team as well as better organizational alignment (i.e. IBM + Red Hat).

**Comment by anvega** [comment]
I could not determine from the meeting notes whether this presentation ever occurred. I'll close the issue for now because it's been a few years. If its something you'd still like to present on, we can reopen the issue and get it on the schedule.
