### ISSUE TITLE
[Sec Assess WG] Naming and Scope of assessments

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#444]
This issue was created from results of the Security Assessment Improvement Working Group (https://github.com/cncf/sig-security/issues/167#issuecomment-714514142). 

# Naming and Scope of assessments

## Premise
- Assessment is an overloaded term, and can lead to confusion

## Ideas
- Have a better articulation of what is a sec assess.
- Include scope to include additional aspect of code audit related checks/certification
- Add mapping aspects of assessments to compliance frameworks
- Additional suggestion of scope to include related to security testing
  - Implement hands-on security testing #394
  - Define requirements for hands-on security testing / best practices
  - Must be a process for onboarding and approving new "hands-on" testers

## Logistics
- [ ] Contributors (For multiple contributors, 1 lead to coordinate)
 - Placeholder_1
 - Placeholder_2
- [ ] SIG-Representative

**Comment by TheFoxAtWork** [comment]
@lumjjb is this considered complete?

**Comment by anvega** [comment]
With the publication of the assessments book, we've ratified the use of assessment.
