### ISSUE TITLE
[Sec Assess WG] Benefits of a Security Assessment for Projects

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#445]
This issue was created from results of the Security Assessment Improvement Working Group (https://github.com/cncf/sig-security/issues/167#issuecomment-714514142). 

# Benefits of a Security Assessment for Projects

## Premise
- It is not entirely clear that why a project should be incentivized to participate in an assessment

## Ideas
- Add "benefit for the project" to security assessment guide
 - Independent evaluation provides a primer to the CNCFs security audit team
 - It provides a SECURITY.md 
 - Self evaluation should be reflective of their software development practices
- Provide badging: As a badge, reference material for security aspect of the project

## Action Items
- [x] PR for adding benefit to assessment guide (@RonVider)
- [ ] Requirements for a SECURITY.md, what is required, and mapping from assessment documents (@itaysk)

## Logistics
- [x] Contributors (For multiple contributors, 1 lead to coordinate)
 - @itaysk 
 - @RonVider
- [x] SIG-Representative @lumjjb

**Comment by itaysk** [comment]
@lumjjb I'm interested in this one

**Comment by RonVider** [comment]
@lumjjb Add me here :)

**Comment by lumjjb** [comment]
Thanks @itaysk and @RonVider  , going to wait till end of week to see who is anyone else wants to get involved and we can set up some time to discuss.

**Comment by ultrasaurus** [comment]
this looks like it was addressed by https://github.com/cncf/sig-security/pull/459 -- closing

**Comment by ultrasaurus** [comment]
oops -- noticed there's an open checkbox "Requirements for a SECURITY.md, what is required, and mapping from assessment documents (@itaysk)"

should that be opened as a separate issue?

**Comment by itaysk** [comment]
it attempted to address it in https://github.com/cncf/sig-security/pull/494 but that wasn't merged. since the entire doc was rewritten since, I can assume it's no longer relevant (haven't got time to catch up since I didn't have much availability past couple of months for personal reasons). I'm going check that checkbox and if needed we can open a new one.

**Comment by lumjjb** [comment]
Yea i think a lot of the work there is still very good contributions, just need to see where they fit in the restructured doc.

**Comment by lumjjb** [comment]
Hey @itaysk and @RonVider ! How have you been? By any chance would you like to revive this issue? :)

**Comment by anvega** [comment]
Closing the issue as it has been stale for a few years and feel we have improved how we socialize the value of an assessment given the number of assessment requests currently queued up.
