### ISSUE TITLE
[Sec Assess WG] Security Assessment Process Mechanics Improvements

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#449]
This issue was created from results of the Security Assessment Improvement Working Group (https://github.com/cncf/sig-security/issues/167#issuecomment-714514142). 

# Security Assessment Process Mechanics Improvements

## Premise
- There are several points of mechanical improvement to the security assessment process. This issue encapsulates the brainstormed ideas around various aspects of the process. 

## Ideas

Process documentation
- Define the new process(es) then define the roles for each part
- Break the process into 3 parts, one for each part of the CNCF cycle: Self, Joint, Independent
- user community should determine who is assessed first and what assessment goals are highest priority since they are the ones using a project IRL - require user "sponsors" who participate and review assessment before presentation to SIG and TOC

Tracking issue:
- Keep conflict of interest statements on the issues.

Self-assessment:
- Self-Assessment table of contents (like harbor)
- For concerns of self-evaluating self, Sign off by project lead for integrity of self-assessment
- Joint evaluation should review the previous self evaluation, maybe do a small hands-on assessment, and highlight 'security features' of the project

Reviewing process
- Come up with recommendations for security reviewers (i.e. here are 10 things you can do for a review)

Feedback and post review
- Review survey - Fresher feedback from review participants post review
- Integrate 1 page summary slides into repo

Misc:
- (needs clarification) Projects should be provided "summer of security" support for initial assessment and ongoing assessment efforts 

## Logistics
- [x] Contributors (For multiple contributors, 1 lead to coordinate)
 - @TheFoxAtWork 
 - @magnologan 
- [x] SIG-Representative @TheFoxAtWork

**Comment by TheFoxAtWork** [comment]
add me :)

**Comment by magnologan** [comment]
I'm interested!

**Comment by tegrekara** [comment]
Interested

**Comment by TheFoxAtWork** [comment]
@tegrekara would you review the [resources in the repo](https://github.com/cncf/tag-security/tree/main/assessments) to determine if they are clear, easy to understand, etc?  There is the overview, the process, the templates, roles, etc.  If you find anything feel free to create a new issue or start a PR.

@lumjjb for the purposes of this issue is there enough to call this complete?

**Comment by TheFoxAtWork** [comment]
Closing issue as i believe this work is currently complete.
