### ISSUE TITLE
Cloud Native Security White Paper Webinar 

### ISSUE THREAD

**Issue by vinayvenkat** [cncf/tag-security#450]
Description: I propose to conduct a webinar to amplify the message of the Cloud Native Security White Paper 

Impact: 
The Cloud Native Security Whitepaper contains an in-depth assessment of the needs for security that is appropriately integrated throughout the environment as well as the application lifecycle. There would be a tremendous benefit is a subset of the authors discussed the implications of the paper in a webinar. The webinar can be in a roundtable format to discuss the various aspects and provide thought leadership for the stakeholders to takeaway as the adopt the right security posture for Cloud Native workloads. 

Scope: Medium 

TO DO
- [ ] SIG Representative
- [ ] Project leader(s)
- [ ] TBD

**Comment by chasemp** [comment]
Is the thought for this to be a Q&A session primarily aimed at both informing the general public and potentially gathering data on where to improve the whitepaper, or is it to create a mostly broadcast presentation that walks through the various elements of the paper (maybe pulling in related but excluded details)?  Or both :D

**Comment by gadinaor** [comment]
@vinayvenkat happy to support this

**Comment by lumjjb** [comment]
@TheFoxAtWork @ultrasaurus @pragashj @JustinCappos do you think we could host a webinar during the SIG meeting? I think could be a good way to introduce more people to the SIG as well.

**Comment by TheFoxAtWork** [comment]
@lumjjb i think this is very doable.  Any specific thoughts?  CNCF webinar simulcast on twitch?

**Comment by vinayvenkat** [comment]
@lumjjb Are you thinking use one of our Sig-Security meetings and do the webinar? I was also thinking how we can publicize this on a broader scale. For example, have it available on the CNCF webinars site etc. 
Please let me know and happy to coordinate the details for this. I have a lot of ideas :-)

**Comment by ejazr83** [comment]
I would be willing to get involved and support this as well. I can support doing a webinar and organising one for the ANZ timezone as well.

I think a paper walk through is fine but it might make sense to have slides version of the paper to make it more visual when presenting and then have a QnA session

**Comment by vinayvenkat** [comment]
@ejazr83 I'm thinking it would be good to have two versions of the webinar. One version is like a roundtable with a moderator and 3 other participants to share their views on how to consume . The second version can be the one wherein we convert the paper into a slide deck and deliver it as a webinar.

**Comment by magnologan** [comment]
Happy to help here! o/

**Comment by apmarshall** [comment]
Also happy to help with this.

**Comment by Harrysk** [comment]
@vinayvenkat I am late to this discussion, but wondering if we are still working on this issue - planning to have this webinar sometime soon? I am happy to support and contribute to planning and organising this webinar. 
- Cheers, Hari.

**Comment by magnologan** [comment]
Any plans to do this webinar? I can host the session and ask questions on CNCF Twitch if others are willing to participate. 

@dcomas maybe we can talk about it on our podcast?

**Comment by TheFoxAtWork** [comment]
closing this issue as inactive
