### ISSUE TITLE
2021 KubeCon+CloudNativeCon EU Cloud Native Security Day!

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#454]
Description: SIG-Security Day at the upcoming Virtual EU Kubecon/CloudNativeCon. The goal of the day is to bring together the broader Cloud Native security community in a community oriented space to discuss and share current challenges (and solutions) in Cloud Native security.

Social Media:
#cnsecurityday
CNCF Website Security Day

Program committee
* SIG Chair: @TheFoxAtWork 

* Team Leads: @anvega 

* CFP Reviewers: (needs reconfirmed in January) 
  * @anvega 
  * @TheFoxAtWork 
  * @marco-lancini
  * @johnhillegass - 
  * @dlapiduz - needs SIG-membership
  * @itaysk 
  * @sublimino 
  * @alokraj - needs SIG-membership
  * @danpopSD - 
  * @umairmkhan - needs SIG-membership

CTF
* @sublimino 
* @ronvider 
* @magnologan 
* @denhamparry

slack channel: #sig-security-events

Date: TBD

TO DO
- [x] Website: review past content and update as appropriate
- [x] CFP prep
- [x]  CFP Review
- [x] Security Day event schedule/planning
- [ ] Retrospective: doc

Proposed Format
Virtual conference with hallway track "slack-track" launching poll of threaded topics.

Capture the Flag!
An educative CTF to promote Kubernetes security awareness. All levels welcome! Each CTF scenario will be run in parallel with a talk, with friendly people on hand in Slack to help anybody that gets stuck.

Learn how to protect your cluster by pwning another and capturing their flag. From n00b to 1337, we have a number of different scenarios for hands-on learning. Join the Slack channel and our training team will get you up and running throughout the day.

**Comment by marco-lancini** [comment]
I'd be happy to help!

**Comment by JohnHillegass** [comment]
I'd like to help as well!

**Comment by dlapiduz** [comment]
I'd love to help!

**Comment by itaysk** [comment]
I can help as well

**Comment by RonVider** [comment]
I'd be happy to help with the CTF :)

**Comment by sublimino** [comment]
Happy to assist the CFP/CTF effort again, providing today goes well! :upside_down_face:

**Comment by alok-raj** [comment]
I'd love to help!

**Comment by anvega** [comment]
Having chatted with Emily around expectations, I'd love to help out as team lead to take on coordination and logistics in preparation ahead of, as well as all other team lead tasks, come the day of the event.

**Comment by danpopSD** [comment]
count me in.

**Comment by TheFoxAtWork** [comment]
@marco-lancini, @JohnHillegass, @dlapiduz, @RonVider, @alokraj, @danpopSD  Thanks so much for your interest!  i've add you as program committee.  Checking through our members list shows that you are not yet members of the SIG!  

Please go through our [new members page](https://github.com/cncf/sig-security/blob/master/NEWMEMBERS.md), attend some of our meetings, learn more and become members.  Our next meeting is December 2nd 2020

**Comment by umairmkhan** [comment]
I m happy to help :)

**Comment by magnologan** [comment]
I'm in too! o/

**Comment by TheFoxAtWork** [comment]
Closing program committee call.

**Comment by denhamparry** [comment]
I'm late to the party but happy to help out wherever I can in regards to the CTF

**Comment by freddyfernando** [comment]
I'll be happy to help with the CTF as well.

**Comment by danpopSD** [comment]
@TheFoxAtWork put me in coach!

**Comment by ragashreeshekar** [comment]
I'm very delayed to the party, would love to collaborate as well. Pls let me know if there is anything I can work on.

**Comment by anvega** [comment]
Post event debrief notes: https://docs.google.com/document/d/1uAptpj3zury9YEvuZB8-WcfCbUSooonoUsLlW23cRcA/edit
