### ISSUE TITLE
White Paper->Figure 1: Lifecycle ought to go left to right

### ISSUE THREAD

**Issue by cvcrckt** [cncf/tag-security#463]
We often speak of shifting security to the left (including in the whitepaper). Perhaps the lifecycle portion of Figure 1 in the WP should be flipped to read from left to right (dev->distrib->deploy...) in order to correspond with the saying.

sig-security/security-whitepaper/RackMultipart20201111_figure1.png

**Comment by TheFoxAtWork** [comment]
@gadinaor @vinayvenkat @PushkarJ @pragashj Thoughts?

**Comment by vinayvenkat** [comment]
Yes, we always talk about this in the context of shift left. I was aware of this however I didn't bring it up as we don't explicitly talk about the concept of shift left by referring to that figure. But yes, if we have the opportunity to fix it, would be good to do so.

**Comment by TheFoxAtWork** [comment]
Awesome  - we can certainly update the figure in the markdown version since it is our working document. If enough changes happen to it we can republish the PDF as a 2.0

**Comment by anvega** [comment]
v2 paper is now published
