### ISSUE TITLE
[Proposal] Cloud Native Security White Paper Chinese translation

### ISSUE THREAD

**Issue by rootsongjc** [cncf/tag-security#470]
Description: The [Cloud Native Community](https://cloudnative.to/en), began translating this white paper last week and has now completed the translation. The following people are involved.
- @rootsongjc
- @N3erox0
- @cafra
- @aiaicaow
- @hbrls
- @losery
- @knwng
- @babysor
- @dwctua
- @gtb-togerther

The white paper is carefully reviewed by a translation team to ensure quality.
@babysor will submit a PR on behalf of the community.

**Comment by lumjjb** [comment]
Hi @rootsongjc, do you think this is in a ready state for merging in?

**Comment by rootsongjc** [comment]
This PR is almost ready, https://github.com/cncf/sig-security/pull/471 @magnologan Could you check it?

**Comment by magnologan** [comment]
Me? I think you meant @lumjjb right? My Chinese skills are not that good! =)

**Comment by TheFoxAtWork** [comment]
Closing as resolved with #471
