### ISSUE TITLE
[CNSWP] Propose and ideate on breakout topics for the CNSWP

### ISSUE THREAD

**Issue by vinayvenkat** [cncf/tag-security#495]
Description: We need to identify appropriate breakouts for the cloud native security white paper in order to deep dive on 
specific topics. 

Impact: The impact of this effort will be a more detailed discussion and suggestions on how security practitioners can operationalize security as described in the white paper. It also highlights the practices for each and every topic brought up in the CNSWP. 

Scope: Will update this shortly. Its not going to be easy!

TO DO
- [ ] SIG Representative
- [ ] Project leader(s)
- [ ] TBD

**Comment by faisalrazzak** [comment]
I'm interested

**Comment by achetal01** [comment]
I will like to contribute to breakout topics as well.

**Comment by TheFoxAtWork** [comment]
add me in!

**Comment by magnologan** [comment]
I can help with the K8s related deep dive.

**Comment by TheFoxAtWork** [comment]
Wanted to drop this here while still in my mind: either the next iteration or one of the separate deep dive papers needs to include explanation and importance of verifiable reproducible builds

**Comment by joshuagl** [comment]
I would like to help with the verifiable reproducible builds (and related build system hygiene?) deep dive

**Comment by TheFoxAtWork** [comment]
@PushkarJ do you think this issue is overcome by the survey and the topic resolution from the survey? CC @lumjjb @achetal01

**Comment by PushkarJ** [comment]
@TheFoxAtWork yes agree. I think the last two pending action items on #480 and the ongoing work such as supply chain security, serverless security whitepapers and security map covers the intent and scope of the issue already.

**Comment by TheFoxAtWork** [comment]
closing as OBE in favor of #480
