### ISSUE TITLE
Project to Create an Automated Security Framework to evaluate CNCF Projects

### ISSUE THREAD

**Issue by vinayvenkat** [cncf/tag-security#496]
Description: Develop and automated framework to evaluate the security posture for CNCF graduating projects. 

Impact: The impact of this automated framework will be to easily evaluate the security posture for projects and provide concrete feedback highlighting areas which need to be addressed from a security perspective. This will help project owners understand the security attack surface and concrete steps that they can take which can improve the security for their projects. Additionally, if we automate this then we can periodically perform these assessments and keep the projects updated in terms of their security posture. 

Scope: TBD
TO DO
- [ ] SIG Representative
- [ ] Project leader(s)
- [ ] TBD

**Comment by sunstonesecure-robert** [comment]
this somewhat overlaps topics in the Policy WG so happy to break out there too -- next one scheduled 1/5

**Comment by gadinaor** [comment]
@vinayvenkat happy to to collaborate here - there is definitely a collection of tools that can be used to provide security assessments - artifacts level, deployment hardening level etc.

@sunstonesecure-robert if I understand correctly the Policy WG focused on a standardized assessment reporting format , right?

**Comment by sunstonesecure-robert** [comment]
> @sunstonesecure-robert if I understand correctly the Policy WG focused on a standardized assessment reporting format , right?

as one of the topics - yes - the WG strives to cover all aspects of policy in CN systems .... policy domains, definition, specification as code, enforcement, review, compliance, audit ... but we had to start concretely somewhere with 1 of these and reporting policy assessment results was just the one that gained traction in 2020.

**Comment by itaysk** [comment]
@vinayvenkat count me in!
Obviously there's alot of prior work in this space, which is also to say that on top of the product itself, the adoption strategy should not be underestimated.

**Comment by JonZeolla** [comment]
I'm in as well

**Comment by magnologan** [comment]
Sorry if I didn't completely understand the goal here. But what we are trying to get out this exactly? Is it a document with best practices/standard for Cloud Native developers to follow? Or is it more like a generic tool that would basic security implementations (code security) in all CNCF projects such as: 

- No hardcoded credentials
- Strong crypto algorithms
- Proper input validation
- Parametrized queries

Thanks!

**Comment by sunstonesecure-robert** [comment]
> Sorry if I didn't completely understand the goal here. But what we are trying to get out this exactly? 
> 

I think that's still undefined (or fuzzy defined). 

 I see 2 perspectives at least:

* operator (bottom up) - this is vulnerability oriented, configuration oriented, secure baseline oriented ... the "what" and "how" of security
* compliance (top down) - this is human policy oriented, threat oriented, process oriented, communication oriented, framework oriented ... the "who" and "why" of security.  

I think the operator tools exist (Aqua and others).  The compliance tools tend to be more dashboard and human readable document focused.  I haven't myself seen an executable tool (or set of tools) that bridges the gap: map a high level human compliance framework (eg NIST 800-53 OSCAL) and threat definition (MITRE, STIX?) to an executable policy file (e.g. rego rules) and map level OS and code vulnerability (eg CVSS) and configuration baseline scans (eg OVAL, XCCDF) back up to the compliance layer. IBM has some open source tools that might fit the bill that they have discussed in the Policy WG sessions.

**Comment by magnologan** [comment]
I think that the goal for this issue should be to focus on the automation part. Things like SAST (Static Analysis) and SCA (Software Composition Analysis) would be helpful here and should be part of this framework. Giving the project maintainers a better understanding of their dependencies and code issues is a good first step IMHO.

**Comment by TheFoxAtWork** [comment]
Possibly related: https://github.com/cncf/sig-security/issues/422

**Comment by elinesterov** [comment]
@sunstonesecure-robert 
>the scorecard topics certainly do some of that. it does provide concrete steps

I would argue they do it in the **Checks** section where they explain what the check is and pointing to a guideline on how to enable it.
https://github.com/ossf/scorecard/blob/main/README.md#checks
I would add CNCF specific projects ( I guess the easiest way to pull it from the CNCF landscape project) and do a PR to the repo. 
Any ideas on tools that could be used easily to create a dashboard with CNCF projects? It needs to consume endpoint with JSON so possibly could be done with a static website.

**Comment by elinesterov** [comment]
It seems it is better to join forces with OSSF on this one. They already started working on the dashboard: https://github.com/ossf/Project-Security-Metrics. Our part will be to bring and update over time CNCF related data and create corresponding dashboards. I'll follow up with them.

**Comment by elinesterov** [comment]
To follow up o today's conversation I had a question if there is a source that we can parse and the source would contain URLs to the repository of all CNCF projects. My initial thought was to figure out if we can get the data from l.cncf.io and here you go! The repo actually has a YAML file with the content https://github.com/cncf/landscape/blob/master/landscape.yml.

So it seems we have all the parts we need to kick off the initial project:
1. The data source https://github.com/cncf/landscape/blob/master/landscape.yml. Another source could be https://sourcegraph.com/cncf
2. tool to use for each project evaluation https://github.com/ossf/scorecard
3.  Need to build job that will be executed periodically
4. Data pipeline ingestion to elasticsearch + kibana. I have a quick prototype on elasticsearch cloud. 
5. need to figure out how to get it into https://insights.lfx.linuxfoundation.org/projects/sigstore/dashboard 

cc: @lumjjb

**Comment by sunstonesecure-robert** [comment]
> Need to build job that will be executed periodically
wouldn't that be done via github action in the project repo(s)?

> need to figure out how to get it into https://insights.lfx.linuxfoundation.org/projects/sigstore/dashboard
there is an enroll button on Insights but do you mean how do we modify Insights to add the Kibana visualizations into its dashboard?

Of note - the LF Security tool itself lists OSSF in its scans... but... nothing seems to be scanning currently: https://security.lfx.linuxfoundation.org/#/a0941000002wBz9AAE/foundation-details

I also don't see OSSF in Insights itself?

**Comment by elinesterov** [comment]
>wouldn't that be done via github action in the project repo(s)?
I don't have any preferences here. I guess any way would work.

> there is an enroll button on Insights but do you mean how do we modify Insights to add the Kibana visualizations into its dashboard?

I mean we'll need to figure out how to add the dashboard we create there and how it can ingest the data.
>Of note - the LF Security tool itself lists OSSF in its scans... but... nothing seems to be scanning currently: https://security.lfx.linuxfoundation.org/#/a0941000002wBz9AAE/foundation-details

It seems it is done by Snyk which scans for vulnerabilities. Have no idea who manages it and what is the purpose. I don't think we need to put another dashboard here like one we discuss here unless we understand:
  * what is the value of doing that
  * what do we want to see on the dashboard
  * who is going to use it and why

> I also don't see OSSF in Insights itself?
I'm not sure what you mean here :)

**Comment by sunstonesecure-robert** [comment]
of relevance: 

https://openssf.org/blog/2021/05/03/introducing-the-security-metrics-project/ 

[thanks to community for eyes open!](https://cloud-native.slack.com/archives/CDJ7MLT8S/p1620109544277200)

**Comment by sunstonesecure-robert** [comment]
also see: https://github.com/cncf/tag-security/issues/612

**Comment by anvega** [comment]
Marking this issue as out of scope for tag security as pointed out in discussion it would duplicate the effort of the openssf scorecard
