### ISSUE TITLE
Cloud Native Security Policy Framework

### ISSUE THREAD

**Issue by achetal01** [cncf/tag-security#498]
Description:  Define a superset of the security policies  and their definition for the whole cloud native domain which covers CI-CD Pipelines, Control Plane and Data Plane. 

Important to scope it right and have focus on ONLY Security policies here, this work can be integrated into the Policy working group and can be an input into their Policy assessment and governance framework.

Impact: Enterprises who are new to Cloud Native or still maturing, will get a great resource of best practice security policies to enforce as code. They can decide which ones to enable and enforce and which ones they don't based on their risk tolerance.

Scope: How much effort will this take? ok to provide a range of options if or "not yet determined" for initial proposals.  Feel free to include proposed tasks below or link a Google doc 

TO DO
- [ ] SIG Representative STAG Representative- @achetal01 
- [ ] Project leader(s)
- [ ] TBD

**Comment by JonZeolla** [comment]
I'd like to contribute to this.

**Comment by itaysk** [comment]
sounds like the produce of this will be similar to #496? am I correctly understanding?

**Comment by sunstonesecure-robert** [comment]
Trying to interpret other folks' comments from the call yesterday but I think #496  is more about assessing projects/products in an automated (policy driven?) way, whereas this is more like here's an off-the-shelf bundle of policy (as code) that you can tailor to your specific stack...or at least that's how I understood the goal.

**Comment by alok-raj** [comment]
I'd like to contribute to this.

**Comment by lumjjb** [comment]
Already being worked on by policy working group
