### ISSUE TITLE
Attack Matrix for Cloud Native Technologies

### ISSUE THREAD

**Issue by achetal01** [cncf/tag-security#502]
Description: Develop Attack Matrix (similar to Mitre Framework) for CaaS and FaaS. This can be a separate effort or a subdomain to security white paper.

Impact: It will help consumers /Enterprises who are using Cloud native technologies, Understand the cyber-attack chain and help them to  put controls in place to “kill” or contain the attack at various stages, and better protect the Platform and the Runtime environment.

It will also help SOC teams build appropriate intelligence and scripts so they can recognize these attack patterns 

Scope: It requires focussed work from the participants who have experience with Mitre Like framework.

1. Cover Container as a service Attack Matrix - There are different flavors of this and may require defining all the scenario's first. e.g. Private CaaS, Public CaaS
2. Serverless /Function as a Service - Address attack matrix for Public FaaS and Private FaaS as well

Goal is to keep it Technology agnostic as much as possible.

Reference :
https://www.nsa.gov/news-features/press-room/Article/2665993/nsa-funds-development-release-of-d3fend/
https://www.darkreading.com/threat-intelligence/microsofts-kubernetes-threat-matrix-heres-whats-missing/a/d-id/1339106
https://blog.spiffe.io/scrutinizing-spire-security-9c82ba542019
https://blog.spiffe.io/scrutinizing-spire-to-sensibly-strengthen-spiffe-security-part-two-b8351ee2ff79
https://medium.com/mitre-engenuity/help-shape-att-ck-for-containers-7fe4905623c5
https://sysdig.com/blog/mitre-attck-framework-for-container-runtime-security-with-sysdig-falco/

Reference a Previous Issue - https://github.com/cncf/sig-security/issues/110

TO DO
- [ ] SIG Representative
- [ ] Project leader(s)
- [ ] TBD

**Comment by TheFoxAtWork** [comment]
Notes from planning session  [fox]  related to #413 possible.  recommend pulling them together?
1/20 - [chairs]  finance group did threat analysis on k8s (stuck in notes somewhere)

**Comment by sublimino** [comment]
@TheFoxAtWork for the FSUG work on k8s at https://github.com/cncf/financial-user-group/blob/master/projects/k8s-threat-model/README.md we collaborated on that and I'm happy to help bootstrap this work, timetable dependant! /cc @jonmuk @rowan-baker

**Comment by TheFoxAtWork** [comment]
Please hold on.  We have a roadmap discussion coming up at the end of the month where this and many other projects are up for discussion.  We (as a SIG) have some planning to do.

**Comment by Harrysk** [comment]
I would like to contribute to this project!

**Comment by ragashreeshekar** [comment]
Pls count me in!

**Comment by TheFoxAtWork** [comment]
Folks i'd like to propose this as a topic for discussion at an upcoming TAG meeting.  @achetal01  thoughts?

**Comment by TheFoxAtWork** [comment]
this should be checked against D3fend which was just launched with Mitre. https://d3fend.mitre.org/

**Comment by achetal01** [comment]
https://www.nsa.gov/news-features/press-room/Article/2665993/nsa-funds-development-release-of-d3fend/

**Comment by anvega** [comment]
It's coming on two years that the issue has been stale. This feels overtaken by efforts from MITRE ATT&CK https://www.trendmicro.com/en_us/research/21/e/mitre-attach-for-containers-why-it-matters.html. We will close the issue and reopen if there are willing volunteers to adapt/apply to specific CNCF projects.
