### ISSUE TITLE
[Suggestion] SIG-App-Delivery Help.  operator paper needs security input

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#514]
Description: Colleagues in SIG-App-Delivery have asked for security focused assistance in writing an operator paper.

[Current Draft](https://docs.google.com/document/d/1daXHyR2yG5ArjO1PO83v4a0fmLCLo2kYNT3TwGZksng/edit#)

a slack channel #sig-app-delivery-operator-wg
POCs: Omer Kahani, Jennifer Strejevitch, Thomas Schuetz

**Comment by thschue** [comment]
The corresponding issue in sig-app-delivery would be https://github.com/cncf/sig-app-delivery/issues/39. Thank you!

**Comment by cseader** [comment]
I will contribute here

**Comment by jlk** [comment]
Happy to help out as well!

**Comment by jlk** [comment]
@TheFoxAtWork just an update for ya - draft PR for the security chapter went over last night. There's a little more work to be done, will send out a link when they cut a draft for review.

**Comment by jlk** [comment]
Haven't updated for a while...we wrapped up our work on chapter 4, that can be reviewed at https://github.com/cncf/tag-app-delivery/blob/master/operator-wg/whitepaper/04_Security.md. I think Thomas and the tag-app-delivery team are working on getting the overall WP in shape before general release.

**Comment by TheFoxAtWork** [comment]
All checking in here to see how this is progressing, when will it be up for public comment review?

**Comment by thschue** [comment]
This started today. The PR is available here -> https://github.com/cncf/tag-app-delivery/pull/114, the current version -> https://github.com/cncf/tag-app-delivery/blob/public-comment/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md

Thanks for your help!

**Comment by TheFoxAtWork** [comment]
@thschue Sent to a broader audience via lists: https://lists.cncf.io/g/cncf-tag-security/topic/tag_app_delivery_operator/83242460?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,83242460

**Comment by jlk** [comment]
This can be closed - the paper was released! https://www.cncf.io/blog/2021/07/16/learn-how-to-simplify-application-management-with-operators-with-the-cncf-operator-white-paper-from-tag-app-delivery/

**Comment by lumjjb** [comment]
Awesome! 🎉
