### ISSUE TITLE
[Suggestion] should document the process for CNSWP

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#528]
Description: As we create more papers, the process used to create the CNSWP seemed useful.  We should document that process, refine it as necessary and share it.  We've had one SIG reach out for this information which was shared out of band but was very useful

Impact: Streamline future papers

Scope: capture existing process from docs and write it up to commit to the repo.

Additional info:
- Organizing and executing the whitepaper.  did it through different phases.  Small group worked on a very rough outline.  We then opened it up to our working group to flush it out and define the scope, goals, non-goals, etc.
Once we had that roughed in, we had folks volunteer for first cuts based on the outline.  Essentially people that tagged themselves to add content to a particular area did one of two things, they either wrote the entire text for that in quotes "" to show exact text or they jotted down rough phrases/statements to be turned into exact text later.  We tried to keep with a two week sprint cadence and we did check in every two weeks but we did need to extend a few times for content.
After the "rough content" was added to the outline, we gave everyone two weeks to read through and adjust the entire language and content of each of the sections of the outline.  We had lots of comments, dialog, conversations, etc.  We tried to resolve a lot of the comments at that point.
Once that was done it was moved into a clean doc, rearranged a few things, organized the layout a bit more from feedback
We then opened it up for another two weeks of review, commentary, etc.
After that we closed it to just 3 people to perform a "narrative voice", to ensure the language, tone, phrasing was consistent.  It also gave that group time to resolve any non-scope items that crept in.

reach the outline: https://docs.google.com/document/d/1nKM-z-_yCSff2CWxF-lPmiWMtM5M2DgBi-Ztu1FQNSI/edit#heading=h.qex63c29z2to  the comment history on this should show you how we went through it (there should also be a revision history)

here is the notes: https://docs.google.com/document/d/1dQAsC1KgMEnVTnQbBKDaAhYPe90NQawGAAYPzG8_JfA/edit#heading=h.si41wejs2bzp

we got to the point were anything already written was off the table until we were ready for a full review. everyone wrote their own content first, others went over it and made changes/comments in the initial review, we hashed questions.  Closed the edits, cleaned it, then reopened for review

original issue: https://github.com/cncf/sig-security/issues/138

The key was we dedicated time closer to the end to so a full review.

**Comment by TheFoxAtWork** [comment]
@vinayvenkat would you take care of this?

**Comment by vinayvenkat** [comment]
@TheFoxAtWork Can you pls assign this to me? Thanks!

**Comment by TheFoxAtWork** [comment]
More notes for a write-up:

1. Identify intended whitepaper audience
2. Define whitepaper scope
4. Create schedule for whitepaper
5. Establish outline of whitepaper

- Outline
- Section author commitment
- Draft content
- Internal group review of draft
- Second round of content/editing
- Second group review of refined draft
- Single voice review
- SIG presentation on paper
- Community review
- Final edits and community review adjudication
- CNCF PDF publication, blog
- Markdown and maintenance readme

**Comment by achetal01** [comment]
One Comment I have is- There may be situations where multiple Different views on the subject matter or controls implementation. How should those be resolved. How will we arbitrate those and make final decisions. This is specially true in new technology and tools ..

**Comment by achetal01** [comment]
Another comment is we have to be specially careful to include References section and add any links or references that are used to develop our content. This is best practice to avoid any legal issues...

**Comment by TheFoxAtWork** [comment]
@achetal01 see #599 [247c355](https://github.com/cncf/tag-security/pull/599/commits/247c3559ffd66ff1c12eb7e9b6530de0370f526e)
