### ISSUE TITLE
Logistics: How does a Workgroup/subgroup archive or get access to its archived Zoom videos?

### ISSUE THREAD

**Issue by sunstonesecure-robert** [cncf/tag-security#536]
For example the Policy WG uses the sig-security Zoom every other Wed 8AM Pacific, so how can we get a link to those videos for posting/slack distribution, etc. 

Should we get a separate CNCF zoom account?  Should we continue to use this same sig-security zoom but assign a user to be admin and do some process? other?

**Comment by sunstonesecure-robert** [comment]
@lumjjb I don't seem to have assignment rights so can't assign to you

**Comment by TheFoxAtWork** [comment]
@sunstonesecure-robert I believe the policy WG videos are now being uploaded.  Can you determine if this issue is still needed?

**Comment by anvega** [comment]
WG videos are now automatically uploaded
