### ISSUE TITLE
[Suggestion] Additional improvements to the new member process for matching contributors

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#548]
Description: Make a more interactive new members process, making it easier for both new members to start working on issues and projects and also make it easier for members of the SIG to find contributors for projects. '

From the triage team + chairs/TLs, there could be a more emphasis about tagging issues, triaging them.
From the new members side, there could be an easier process, i.e. filling up a form that would register them, etc. 

Impact: Improve the general workflow of projects and create a facilitate a more collaborative environment

Scope: Create a PR to add improvements to the new members .md page as well as introduce it as part of the meeting facilitator script. About ~1 week modulo comments.

Related issues:
- https://github.com/cncf/sig-security/issues/115

**Comment by bradmccoydev** [comment]
Hi @lumjjb can you please tell me what the "meeting facilitator script" is, thanks.  I'm happy to help with this

**Comment by anvega** [comment]
We've moved away from the static new members file.
