### ISSUE TITLE
[Suggestion] Develop guidance for code signing of binary releases

### ISSUE THREAD

**Issue by joshuagl** [cncf/tag-security#558]
**Description**: I propose that CNCF/SIG Security develop guidance around code signing of binary releases, then work with the CNCF/TOC to encourage projects to follow the guidance.

Increasingly many CNCF projects provide binaries for releases which are intended to be run on Windows and macOS hosts. Both Windows and macOS have security features which authenticate a binary's code signature on first run. If the binary is not code signed the user must take extra steps to run it, bypassing warnings from their operating system about potentially insecure files from unknown publishers.

**Impact**:

Implicitly encouraging users to ignore/bypass the security protections of their OS and run untrusted code is a bad pattern to propagate. The tendency for Windows users to ignore Windows User Account Control (UAC) is widely discussed, it would be bad for the industry in general if similar behaviour emerged around code signing warnings.

Projects will benefit from these guidelines by being able to do the right thing with less effort, while being confident about making the right decisions (those recommended by the guidelines).

CNCF has a reputation for professionally run and security conscious open source projects, code signing will help maintain that reputation.

**Scope**: "not yet determined" 

**Additional info**:
- similar suggestion made to cncf/toc where @caniszczyk requested discussion and recommendations from SIG security: https://github.com/cncf/toc/issues/612
- Microsoft Code Signing documentation: https://docs.microsoft.com/en-us/windows/win32/seccrypto/cryptography-tools
- Apple Code Signing documentation: https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

**Comment by anvega** [comment]
Thanks for raising awareness of this at the time you did. Guidance has since been produced in both the Supply Chain Best Practices and the Software Factory Reference Architecture to enforce the signing and verification of binaries. A few different choices have emerged in how to do so and which projects in the ecosystem have started to adopt one or the other.
