### ISSUE TITLE
Create a map of open source Supply Chain Security tools and projects

### ISSUE THREAD

**Issue by aspanner** [cncf/tag-security#561]
Description: Create a map of open-source Supply Chain Security tools and projects

Impact: To provide an overview and quick orientation for all software supply chain practitioners of existing open-source tools and projects in support of securing the software supply chain.

Scope: Significant effort across all supply chain security whitepaper contributors - authors, initial reviewers and public reviewers

Additional info:
- ideally, this would form part of the overall security map

**Comment by rficcaglia** [comment]
@lumjjb can this be combined, deprecated by the CNSMAP effort?

**Comment by lirantal** [comment]
Has this issue been superseded by another, or still relevant as its own to document all the tools and proejcts?

**Comment by lumjjb** [comment]
There is a larger scoped effort ongoing for this at #551 which covers other areas as well. If you'd like to get involved, I'd take a look at that.

**Comment by lirantal** [comment]
Thanks, will do

**Comment by ragashreeshekar** [comment]
Possible related scope - https://github.com/cncf/tag-security/issues/984

**Comment by PushkarJ** [comment]
With #984 focussing on similar subject matter which possibly would end up in #551 it is probably safe to close this in favor of continuing work on those issues. 

Feel free to reopen for any other reasons that I may have missed.
