### ISSUE TITLE
Identity, Access, Credentials, Secrets, Certificates Paper

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#565]
Description: The Cloud Native Security Whitepaper did not go into detail about Identity, Access, Credentials, Secrets, Certificates and these concepts are still new and somewhat confusing to the community.  There is a lack of understanding in how each of these should work, how they are used, and what tools in the ecosystem support each of these concepts and how they interrelate.  It is requested that Cloud Native Security create a paper to clarify these leveraging the terms used from #564

Impact: This paper should provide the community with clarity on what an identity is, secret usage versus keys, how certificates are used and created/rotated. GitOps flow considerations, etc.  Providing this level of information should reduce the confusion on implementation of these components

Scope: This is expected to be a multi-week effort with much discussion.  it should follow our traditional paper process.
TO DO
- [ ] SIG Representative
- [ ] Project leader(s)
- [ ] Project members:  @gadinaor-r7 , @sublimino , @bradmccoydev , @andreacavagna01

**Comment by gadinaor-r7** [comment]
@TheFoxAtWork // happy to engage on this front

**Comment by sublimino** [comment]
+1 I can contribute some content too 👍

**Comment by bradmccoydev** [comment]
I can contribute also

**Comment by andreacavagna01** [comment]
+1 to contribute with some content too

**Comment by elinesterov** [comment]
I can help with that as well if you need another +1.

**Comment by szh** [comment]
I can also contribute to this if it's still relevant, but I'm thinking at this point it may make more sense to roll this into the next version of the whitepaper since that's going to be kicked off soon (#975).

**Comment by PushkarJ** [comment]
Oh no, how did we miss adding this in scope for v2 :-D Thankfully we have version 3 coming soon like @szh rightly mentioned!!

**Comment by anvega** [comment]
This is slated to be folded into security map v3, no longer a standalone paper.
