### ISSUE TITLE
Forensics and Investigations in Cloud Native Ecosystem

### ISSUE THREAD

**Issue by achetal01** [cncf/tag-security#572]
Description: Develop a White paper to share guidance on Forensics and Investigations in the Cloud Native Ecosystem. Tools, technologies, best practices that might provide greater insight into issues around the same in a multi cloud hybrid container platforms and Microservices.

Impact: Breaches will happen and there will be need to do forensics and gather info with chain of custody in place for investigators. Considering that Containers can be short lived...It is even more pertinent for Service providers and tenants to understand this.

Scope: Not determined yet.

TO DO
- [x] SIG Representative: @achetal01 
- [ ] Project leader(s)
- [ ] TBD

**Comment by achetal01** [comment]
I think this is an important initiative...

**Comment by anvega** [comment]
While an important initiative, since it didn't gather interest or activation, I'll proceed with closing the issue as it's been a few years. It can be explored again if there is renewed interest and willing volunteers to work on it.
