### ISSUE TITLE
[Proposal] Cloud Native Security White Paper Spanish translation v1

### ISSUE THREAD

**Issue by krol3** [cncf/tag-security#576]
Description: Cloud Native Security White Paper Spanish translation
Similar to https://github.com/cncf/sig-security/issues/470, https://github.com/cncf/sig-security/issues/509

Impact: This would help the Spanish community with the understanding and adoption of best practices for Cloud Native Security. This would also help the promotion of the white paper inside governmental organizations where only Spanish documents are allowed.

Scope: White Paper (44 pages)

sig-rep: @lumjjb 
This translation will be done with the support of the Kubernetes docs-es community @raelga

**Comment by lumjjb** [comment]
Awesome @krol3 ! Looking forward to making this the whitepaper more accessible to a larger audience! :). Let us assign a TL/chair to this so that we can keep track of the effort and make sure it gets the right attention.

**Comment by raelga** [comment]
Awesome++

**Comment by krol3** [comment]
Here's the document that we've created (@raelga, @krol3, @electrocucaracha) so we can start with the Spanish translation. Basically what you have to do is assign a specific topic or paragraph under your name and make the translation.

https://docs.google.com/document/d/13fPbWlT7gZyX9rvWIbBUSJQUvwAXVlgpvQU0lG7tzNI/edit

**Comment by lumjjb** [comment]
Hi @krol3 , what is the current status on this work?

**Comment by krol3** [comment]
Hi @lumjjb ! The status is almost a 9% of translations. I will put more effort with the contributors and I will return in 15 days to update the status. Is that ok?

**Comment by lumjjb** [comment]
Sounds good! Looking forward to your update!

**Comment by raelga** [comment]
The white paper localisation is being discussed during the Kubernetes SIG-Docs ES weekly meetings, feel free to join them at

http://go.rael.dev/k8s-sig-docs-es-meetings

**Comment by krol3** [comment]
Hi @lumjjb The status is almost a 45% of translations.

**Comment by lumjjb** [comment]
Hi! Just checking in here again!

**Comment by krol3** [comment]
Hi @lumjjb the status is almost a 65% of translations.

**Comment by krol3** [comment]
@raelga thanks! we are in 70% of translations.

**Comment by lumjjb** [comment]
almost there!!!!

**Comment by raelga** [comment]
The work is still in progress. :)

**Comment by krol3** [comment]
@lumjjb 90% translation, in the review part !!

**Comment by krol3** [comment]
@lumjjb we are in the process of review!

**Comment by raelga** [comment]
Still in review. 🙂

**Comment by krol3** [comment]
We're with expectation of finish at the end of this year, and before the Kubecon Amsterdan. cc @lumjjb

**Comment by raelga** [comment]
Still WIP.

**Comment by electrocucaracha** [comment]
We are still working on this, right? @krol3

**Comment by krol3** [comment]
yes! @electrocucaracha, we're reviewing

**Comment by anvega** [comment]
https://github.com/cncf/tag-security/pull/1040 merged
