### ISSUE TITLE
Missing documentation license

### ISSUE THREAD

**Issue by CsatariGergely** [cncf/tag-security#596]
The sig-security repo has only an Apache 2.0 License in the LICENSE file and there is no indication that all documentation is licensed under [CC BY 4.0](https://git.k8s.io/website/LICENSE) what should be the case according to the [CNCF charter](https://github.com/cncf/foundation/blob/master/charter.md).

**Comment by TheFoxAtWork** [comment]
I've placed a ticket in with the CNCF service desk (# CNCFSD-770) Legal to help us get this resolve.  Thank you @CsatariGergely for bringing this to our attention!

**Comment by CsatariGergely** [comment]
Thanks @TheFoxAtWork

**Comment by CsatariGergely** [comment]
@TheFoxAtWork is it possible for me to check the status of # CNCFSD-770? I would like to figure out an estimate for the resolution of this issue.

**Comment by lumjjb** [comment]
The current resolution for this is to use Creative Commons 4.0 for all documents in the repo, like CNCF. If not it is on our current list and will get to it soon.

If you'd be willing to, would be more than happy if you can open a PR to add it!  :)

**Comment by TheFoxAtWork** [comment]
The repo license will be changed FROM Apache 2.0 to CC-BY-4.0 effective Wednesday May 19th 2021
