### ISSUE TITLE
[Presentation] Software Factory - Setting up a Trusted Software Supply Chain with Ploigos

### ISSUE THREAD

**Issue by aspanner** [cncf/tag-security#600]
Presenters: @aspanner @hatmarch

Description:
Inspired by the earlier presentation of #501 we have found that the open-source project Ploigos is implementing such an approach which is also based on the DoD DevSecOps ref arch.

The presentation gives a short overview and is then mostly a demo where the Ploigos Software Factory Operator is deployed onto OpenShift in order to build and execute a build factory/pipeline including attestation using Rekor.

Time: ~30minutes

Open Source project in use:
https://github.com/ploigos/ploigos-software-factory-operator
https://github.com/sigstore/rekor
https://github.com/openshift
+others

SIG Representative @matthewflannery 
Schedule date 27th April 12pm Sydney Time

**Comment by matthewflannery** [comment]
Hi @TheFoxAtWork is this sufficient info? I understand this is a new process so want to make sure we are doing the right thing 

@hatmarch and @aspanner from Red Hat are keen to present this at the upcoming APAC SIG Security meeting

**Comment by matthewflannery** [comment]
Have updated the meeting agenda.

**Comment by TheFoxAtWork** [comment]
I believe this has already occurred - could someone verify?

**Comment by aspanner** [comment]
Thanks for the opportunity to present.
I would love to get more inputs across different Kubernetes services into project ploigos.
