### ISSUE TITLE
Audio recordings of CNCF Security Papers

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#606]
Description: Many members of the cloud native community either cannot read through our papers or have trouble making time to read through them.  This is a proposal to initiate audio recordings for sections of CNCF Security Papers produced by this group and make them available to the community to increase accessibility.

Impact: Support and extend our community
* Some members of our community experience long COVID symptoms that interfere with their ability to read deliverables of the group.  
* We would like our information to be welcoming to the visually impaired.  In other circumstances, providing critical content in written form only may be excluding a community of security and cloud native professionals.  While screen readers and text-to-software can assist in this, it is not conversational and in some cases difficult to cover technical terms, making it less appealing.

Scope: the scope can be separated into different parts, which ideally be contributed by a few different people
1. a few community members to read sections of a paper in their native language as it is written (or translated to).  It is suggested these be broken into heading sections of the paper, to make digesting the content presented time-bound and easier to pick up.  
2. a place to host the recordings.  It is recommended we engage the CNCF to determine their ability to assist, working with a Security TAG member to coordinate requirements.

See also:
- CNCF Slack channel: #tag-security-audio
- [project plan/schedule](https://docs.google.com/document/d/15wU_qKe-ifCIkICXbMmpGK3t8yE3zqYZIoROafZWBpA/edit) - planing in progress

TO DO
- [x] SIG Leadership Representative: Sarah Allen (@ultrasaurus)
- [X] Project leader: Chase Pettet (@chasemp) @ragashreeshekar 
- [x] Voices: Chase Pettet (@chasemp), Sarah Young (@sarah-yo), Emily Fox (@TheFoxAtWork), @ashutosh-narkar, @TheFoxAtWork, @raesene,  @Boes-man ? TBD more?
- [x] Editing: Alex Floyd Marshall (@apmarshall)
- [X] Create Slack channel for coordinating project #tag-security-audio
- [X] Kick-off meeting (July 9, 2021)
- [x] Figure out volunteers can upload audio recordings, accessed by other volunteers for production/QA (@ultrasaurus submitted [servicedesk ticket#857](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-857) -- [shared Google Drive folder](https://drive.google.com/drive/u/0/folders/1a7WT3KINTj0WbLof26yyLJnOQocqejCq) ask @chasemp if you need access
- [x] see [google doc](https://docs.google.com/document/d/15wU_qKe-ifCIkICXbMmpGK3t8yE3zqYZIoROafZWBpA/edit#) for detailed schedule and recording assignments

**Comment by chasemp** [comment]
What a great idea.  +1.  I would be willing to be recorded if that's a need.

**Comment by apmarshall** [comment]
My first "real" job was as an audio engineer, and I still do a fair amount of audio editing on the side. Would be happy to engineer for these recordings if/as needed.

**Comment by magnologan** [comment]
+1! Nice! I used to be a DJ in another life and now I'm helping @dcomas with the Cloud Native Security Talk Podcast. Happy to help here and also do the same with the pt-BR translation as well once that's done!

**Comment by ultrasaurus** [comment]
I'm also part of the target audience, and would be delighted to test drive the content when it is ready!

**Comment by ultrasaurus** [comment]
I volunteered to be SIG Leadership Representative and added in list of other helpers.  @magnologan said he could lead if no one volunteers before he finishes his current projects for the group.  This could get started sooner if there's someone else willing to take a leadership role in pulling this together.  I'm sure we could get CNCF staff help if there are logistical requirements or expenses -- we just need someone to take the lead on figuring out the TODO list and project managing.

**Comment by TheFoxAtWork** [comment]
I'm reaching out to our APAC members to see if this is of interest.

**Comment by JustinCappos** [comment]
Good thought!  I will mention this in the next meeting!

**Comment by magnologan** [comment]
As I've discussed with @ultrasaurus on Slack over DM, I'd love to take the lead on this, but I'm currently with too many projects that I'd like to finish, such as the Security Pals pilot program the translation of the CNSWP to pt-BR. So, if there are no leads by June, then I can probably take it. =)

**Comment by chasemp** [comment]
If I wanted to JDI and record the thing, does that raise objections? (this would be a first outing fraught with learning I imagine)  If not I'll have time next week.

**Comment by TheFoxAtWork** [comment]
I thought about it as well.  The group should define how to break up the body of the papers into manageable chunks.  multiple voices with quality recording also engages listeners (so as to not fall asleep on variety)

**Comment by chasemp** [comment]
@TheFoxAtWork that makes sense.  Maybe I'll take the summary section and just do that as a conversation piece / to get the ball rolling.

**Comment by ultrasaurus** [comment]
@chasemp if you record the whole thing, I would listen to it!   Then the audio engineer can take whichever section they like best from yours (or multiple sections).

btw: @sarah-yo also volunteered to record!  I like the idea of having a diversity of voices from different English-speaking countries.

**Comment by ultrasaurus** [comment]
@chasemp has volunteered as project leader 🥇 

According to our [governance process](https://github.com/cncf/tag-security/blob/main/governance/process.md#proposal-process), the next step to move this from a "proposal" to a "project" is to raise it for discussion at one of our meetings.  

@chasemp can you put it on the agenda for an upcoming meeting?

**Comment by chasemp** [comment]
@ultrasaurus  Sure can.

**Comment by ultrasaurus** [comment]
Also, in the spirit of brainstorming possible solutions in the spirit of making something quickly available and iterating.  I thought it might be fun to have a live reading with multiple readers queued up and then @apmarshall could edit the audio recording after (with potentially re-recording bits as needed).

**Comment by ashutosh-narkar** [comment]
Happy to volunteer !

**Comment by Boes-man** [comment]
@matthewflannery says we can blue steel, I am in.

**Comment by TheFoxAtWork** [comment]
Also happy to voice.

**Comment by chasemp** [comment]
I am getting my bearings for issues in github, as the assignee am I meant to be able to edit the description?  

At the moment, I either cannot or don't understand how :D

**Comment by ultrasaurus** [comment]
@chasemp it's a bit hard to find (or maybe I was incorrect about permissions).  Do you have a three-dot menu with edit option in top-right of description area?

![image](https://user-images.githubusercontent.com/41906/119695500-13205f00-be03-11eb-9b50-1764325ab66d.png)

**Comment by TheFoxAtWork** [comment]
I'll be pushing this proposal to Project and placing in the Planned and Scheduled

**Comment by raesene** [comment]
I'd be happy to try and contribute some voice reading, if that's helpful, I've got an accent I don't think we have yet (west coast Scotland)

**Comment by TheFoxAtWork** [comment]
@chasemp I would recommend putting together a tentative schedule and creating a slack channel "#tag-security-audio" to begin coordination. Be sure to invite commenters on the issue.

**Comment by chasemp** [comment]
> @chasemp it's a bit hard to find (or maybe I was incorrect about permissions). Do you have a three-dot menu with edit option in top-right of description area?

Indeed, I see the menu but have no rights beyond a normal comment (quote & reply)

**Comment by chasemp** [comment]
> @chasemp I would recommend putting together a tentative schedule and creating a slack channel "#tag-security-audio" to begin coordination. Be sure to invite commenters on the issue.

Channel is created.  Anyone here who I could find in slack I added.  I'll tinker with a schedule, and a potential breakdown.

FWIW there is a group that does audiobooks for works in the public domain and they have a good primer on beginning recording with free tools [here](https://wiki.librivox.org/index.php?title=Newbie_Guide_to_Recording)

**Comment by ultrasaurus** [comment]
@chasemp I sent a note to #tag-security-triage slack channel about this.  Maybe things changed in github or I just got confused and forgot.  I'll try to keep the description up-to-date.  Free to ping me on slack if I fall behind and miss something!

**Comment by ultrasaurus** [comment]
@Boes-man  sorry I don't understand the blue steel reference.  Perhaps https://www.dictionary.com/e/fictional-characters/blue-steel/ ?  If so, feel free to make whatever facial expression you like while doing audio recording!  I'll put you down as a voice volunteer.  Not sure what your real name is -- pls join the CNCF slack channel #tag-security-audio if you aren't already there

/cc @matthewflannery

**Comment by ragashreeshekar** [comment]
I'm happy to collaborate as well, Indian accent :D

**Comment by chasemp** [comment]
Getting the wheels turning here.  In the tag-security-audio channel is a document linked and a doodle poll for a kickoff meeting for those interested.

**Comment by ejazr83** [comment]
I am happy to voice as well or support in other ways. Is it worth doing some sample recordings so that we can choose who can do the recordings based on different criteria? I am available aligned to Sydney time.

**Comment by chasemp** [comment]
Kickoff meeting was today, if you're interested in taking part please get in the slack channel and see the [doc](https://docs.google.com/document/d/15wU_qKe-ifCIkICXbMmpGK3t8yE3zqYZIoROafZWBpA/edit?usp=sharing).

**Comment by ultrasaurus** [comment]
FYI -- we now have a [shared Google Drive folder](https://drive.google.com/drive/u/0/folders/1a7WT3KINTj0WbLof26yyLJnOQocqejCq) -- @chasemp will be sharing with people doing recording and production.

**Comment by justincormack** [comment]
Happy to help with recording.

**Comment by chasemp** [comment]
This slid to the back for a few of us.  @apmarshall has indicated he is swamped under but still working on editing.  I have been similarly heads down in $job things.  I can't directly edit the description here but am looking to touch base with alex and will update the doc attached for timeline.  

The wheel still turns my friends.

**Comment by chasemp** [comment]
Recently came across a tool that may lend itself well to a second iterations of this process with https://www.descript.com.  Thanks @ragashreeshekar

**Comment by apmarshall** [comment]
I promised this ages ago and then life happened. Here's an overview of the editing process:

Starting with the raw recordings uploaded by speakers:
1. Using Audacity, I ran the recordings through a pre-processing script that included (a) a high-pass filter (cutting out extreme low frequency sound, which is almost always noise), (b) a low-pass filter (doing the same for extreme high frequency sound), and (c) "normalizing" the sound so that peaks were around -3dB.
2. (Still in Audacity) Cut out dead time at the beginning and end of each track.
3. (Still in Audacity) Try to isolate any background noise in the track (ie, humming from an AC/fan, buzzing as a result of audio cable issues, etc). Basically, try to find a few seconds of the track with no speaking so that it's just the "noise." Using the Audacity Noise Reduction filter, present that segment as the "sample" to base noise reduction on. Then select the whole track and use the Noise Reduction filter to apply reduction. May need to experiment with the settings and listen to the test output to make sure the noise reduction does not "damage" the actual, desired audio.
4. (Still in Audacity) Play some representative samples of the track. Get a sense for the "normal" audio level. Now use Audacity's compression settings to pull down extreme peaks closer to that normal. Audacity's compression is a bit more coarse than I want for spoken audio, so I really only targeted the extreme highs here, trying to get rid of the worst peaks before moving on.
5. Export the track as a .wav file from Audacity.
6. Import the track to GarageBand.
7. Add the following to the track in GarageBand:
    1. A noise filter about 8-16dB below the lowest level of desired audio. May need to play with this to make sure you aren't cutting out "soft" moments in the desired audio
    2. Another layer of compression. The GarageBand compression is a lot smoother, so I was a bit more aggressive here, trying to get a nice smooth sound level.
    3. Equalizers: At the track level something tuned to the specific voice of the speaker (playing around with the defaults under "vocals" in GB), at the project level I used one of the "mastering" options to give a little polish to the finished track.
    4. If the audio sounds a bit empty, you can add a very light bit of reverb to "fill it in" a bit.
    5. Export from GarageBand as a .wav

To create the final recordings:
1. Create a new GarageBand project
2. Drag and drop the edited recordings in, using separate tracks for each speaker
3. Line them up and do any trimming of beginnings/endings necessary to get the timing right
4. You might want to do some volume adjustment between speakers to get a fairly consistent sound level
5. Apply a project-wide compressor to further smooth out the volume levels. Since all the tracks are pre-compressed, this one doesn't need to be aggressive. It's just designed to catch any remaining peaks.
6. If desired, add some project-wide EQ to add a little bit of polish to the final, final recording.
7. Export as a .wav and a .mp3. Wav is better quality, MP3 much smaller. Worth having both, but we'll probably only publish the MP3.

**Comment by ragashreeshekar** [comment]
Many thanks @apmarshall for all your efforts towards the v1 of the audio recording project. 
This is very much useful for the v2 - https://github.com/cncf/tag-security/issues/953 and as a tribe knowledge for the projects to come. Would you mind adding this as a document within what could be the security-audio folder?

**Comment by ragashreeshekar** [comment]
Two iterations are released and we have the knowledge transfer documented as well - https://github.com/cncf/tag-security/blob/main/audio-versions/README.md. Closing this issue, and will open one if necessary for further recordings.
