### ISSUE TITLE
[Suggestion] Provide better process around getting a proposal to project

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#609]
Description: Make this much more clear.  expand [this PR](https://github.com/cncf/sig-security/pull/545) to more clearly define the actual turn of a proposal to a project.

Impact: expedite corralling works in progress to be balanced with the workload of the TAG

Scope: Not much.

**Comment by TheFoxAtWork** [comment]
@ultrasaurus things in my head on this.
Want to talk about something? 
1. Review existing issues, if not there  Create an issue, 
2. add it to the planned meeting template, 
3. bring it up in the meeting, determine interest.
4. If interest, have them comment on the issue and nominate a project lead.  No interest, close the issue
5. get a co-chair to sponsor it.
6. start planning and present the plan to the co-chair.  Co-chair will review and determine if its ready to move to project or needs scheduled for later.

**Comment by TheFoxAtWork** [comment]
Before it becomes a project it needs a scope, a project lead, and a sponsor.

**Comment by lumjjb** [comment]
For closing issues - wait a certain amount of time i.e. 90 days for stale bot to close it

**Comment by lumjjb** [comment]
Interest should be issue based, meeting should be an optional but highly recommended step to accommodate for those who are not able to attend meetings.

**Comment by TheFoxAtWork** [comment]
related to this particular file: https://github.com/cncf/tag-security/blob/main/governance/process.md

**Comment by lumjjb** [comment]
@TheFoxAtWork is this issue closed with https://github.com/cncf/tag-security/commit/a2b1131348646f64476e9732010a4acb513c198f#diff-786d2899dd9c5edc902945f769f76a1194eebeccc1a8c017a9647bd72654ff0c, or do you think there are more specific things we need to address?

**Comment by TheFoxAtWork** [comment]
concur this can be closed.
