### ISSUE TITLE
[Project] Convert sig-security to tag-security / Security TAG

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#613]
Description: In light of the TOCs approval to change SIGs to TAGs we need to update our naming convention in the repo

Impact: fairly large?  several of our  links are embedded as URLs not repo paths

Scope: figure out naming conventions, make a list of all the things we need to change outside of the repo, make the changes -- will take a bit of iteration from at least a few people who know the workings of the group to effectively brainstorm the list of things, new folks could be involved to help make the changes once the list of things to change is assembled  

TO DO
- [x] SIG Leadership: @ultrasaurus 
- [x] design team to make a new logo - in progress
- [x] Slide templates for kubecon & other presentations
- [X] Meeting notes google doc changes (thx @TheFoxAtWork)
- [X] Slack channel renames (Thanks @amye :) )
- [x] figure out appropriate short-names and edit [CONTRIBUTING.md#writing-style](https://github.com/cncf/tag-security/blob/main/CONTRIBUTING.md#writing-style)
- [x] make PR(s) with changes to repo
- [x] anything else?

**Comment by lumjjb** [comment]
+ Require design team to make a new logo
+ Slide templates for kubecon

**Comment by amye** [comment]
> * Require design team to make a new logo

Already in progress:) 
> * Slide templates for kubecon
> * Meeting note templates

Meeting Doc has been updated.
> * Slack channel renames (Thanks @amye :) )

**Comment by ultrasaurus** [comment]
converted to a project, since it's already in progress and we def need to do it
