### ISSUE TITLE
[Discussion] Secure timestamping in regards to short-lived keys & certificates.

### ISSUE THREAD

**Issue by mikhailswift** [cncf/tag-security#625]
Description: As discussed during the May 12 meeting, I'm currently working on using short lived keys to sign artifacts and now need to handle making sure the signature was generated during the key's validity window.  RFC3161 exists as a way to standardize this process but doesn't define any specifications for transport.  I'm appealing to the tag-security group as a whole for individuals who have experience in this field to perhaps form a small meeting to discuss the issue.

Impact: This will impact my work on the in-toto project and how we approach supply chain security in that context.

Scope: I do not believe this to be a significant scope.  A few people chimed in during the meeting who seemed experienced in this field.  A few references were provided: https://github.com/sigstore/rekor/pull/293 and TUF's handling of timestamps were of particular note.

@colek42 @trishankatdatadog Marina Moore also expressed interest on being tagged on this, but I am unable to find a github account for them.

**Comment by trishankatdatadog** [comment]
Cc @mnm678

**Comment by trishankatdatadog** [comment]
Cc @dlorenc @SantiagoTorres

**Comment by lumjjb** [comment]
@lukehinds tagging in case this is relevant for fulcio

**Comment by dlorenc** [comment]
Hey! Yes, we've taken this approach in sigstore. Let me know how I can help.

**Comment by lukehinds** [comment]
>  I'm currently working on using short lived keys to sign artifacts and now need to handle making sure the signature was generated during the key's validity window

This is exactly what sigstore stores (with in-toto integration underway). Any reason to not just use / contribute to sigstore , are we missing something?

**Comment by mnm678** [comment]
For shortlived keys like you describe, I agree that you should look into sigstore's approach.

More generally for ensuring timeliness of in-toto metadata, @trishankatdatadog has also had success using TUF as a transport mechanism for the in-toto metadata, which provides timeliness through TUF's timestamp and snapshot roles.

**Comment by colek42** [comment]
For our use case, we need to tie attestations to specific containers (file systems) and hardware (TPM AK) with an out-of-band process.  SPIFFE/SPIRE framework provides this for us.  I think [this](https://github.com/sigstore/rekor/pull/293) PR on Rekor will definitely be part of the solution.

in-toto additionally gives us the ability to make attestations with flat files.  This is great when we need to verify software in air-gapped environments.  From my understanding use of sigstore for this data would add an additional dependency to the toolchain at the time of verification.

one of our initial thoughts is to sign the link.metadata files with this spec:
https://theupdateframework.github.io/specification/latest/#file-formats-timestamp

@SantiagoTorres

**Comment by trishankatdatadog** [comment]
So I hate to be that guy, but I think a quick meeting may be in order to try to understand the problem better and see when and where we may be able to apply each tool? 🙂 One person representing each tool mentioned here should do.

**Comment by dlorenc** [comment]
I just opened https://github.com/tektoncd/chains/issues/87 over in Tekton to track other ideas on how to make some of this stuff easier directly in Tekton itself.

**Comment by dlorenc** [comment]
Found this too: https://youtu.be/4lFbdkB62QI :)

**Comment by lukehinds** [comment]
@anvega should be here too.

**Comment by anvega** [comment]
Thanks, @colek42 and @lukehinds. 

How is Tuesday 8 or 9 am US pacific time work for everyone to meet and discuss? 

Tagging @azdagron and @evan2645 here whose perspective will be relevant and beneficial.

**Comment by evan2645** [comment]
> Tagging @azdagron and @evan2645 here whose perspective will be relevant and beneficial to the conversation.

👋 

This week will be tough for me. I'd love to join a call if it's next week some time (Monday? Wednesday?), else I can review a recording or something to catch up and leave any relevant thoughts on this thread?

**Comment by colek42** [comment]
Next week will be better for Mikhail and myself as well.  I am good next
monday pretty much all day.

-Cole

**Comment by trishankatdatadog** [comment]
Next Monday WFM too

**Comment by azdagron** [comment]
Happy to join a call next monday.

**Comment by lumjjb** [comment]
@mikhailswift @colek42 if you'd like to use the CNCF Security Tag zoom, that is always open, just note that the call is always recorded.

**Comment by mnm678** [comment]
Next Monday works for me as well.

**Comment by colek42** [comment]
I have a meeting set for Monday 24 May at 11:00AM-12:00AM CST using Zoom.  Send me a message on Slack with your email if you would like and invite.  Otherwise meeting details will be in TAG-Secuirty meeting notes for 19May2021

**Comment by anvega** [comment]
Thanks, @colek42. I've forwarded the invitation to everyone who has commented on this issue.

**Comment by ultrasaurus** [comment]
Hi all -- Glad this discussion is moving forward!  I'd like to assign this issue to someone.  Who wants to volunteer to summarize whatever is learned from this in issue and either close it or turn it into a proposal/suggestion if it seems like some artifact in the repo or other action would be useful?  @colek42 @mikhailswift ?

**Comment by colek42** [comment]
Mikhail and I will take care of it.

**Comment by danpopSD** [comment]
@anvega  -- i would like to join this call if at all possible.

**Comment by lumjjb** [comment]
@danpopSD look in the #tag-security slack for the goodies :)

**Comment by TheFoxAtWork** [comment]
Checking in here - is there any outstanding action/project for the STAG or is this being handled out-of-band?

**Comment by trishankatdatadog** [comment]
Emily, I think the recommendations were:
1. TUF is not designed to do RFC-3161-style timestamping, despite the closely named `timestamp` role/metadata.
2. Best to use a RFC-3161 timestamping authority (TSA) like the one in SigStore.

**Comment by TheFoxAtWork** [comment]
Closing issue with the above recommendation for resolution from @trishankatdatadog
