### ISSUE TITLE
[Suggestion] Repo change master-> main links and references for the tag repo

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#631]
Description: What's your idea?

 change master-> main links and references for the tag repo

Impact: Describe your hopes for how this would reduce risk for the cloud native ecosystem. Who will this help? How will it help them?

Part of inclusion effort.

Scope: How much effort will this take? ok to provide a range of options if or "not yet determined" 

Probably about 15 minutes.

**Comment by himanshu007-creator** [comment]
I would like to work on this issue😄

**Comment by lumjjb** [comment]
Awesome! :D 

> can you specify which folder needs renaming? and to what again
Not any particular folder, I would start with these search results and work through them. Most likely it just warrants a repo wide `sed` script :) 

https://github.com/cncf/tag-security/search?q=%22sig-security%2F%22

**Comment by ultrasaurus** [comment]
@himanshu007-creator @lumjjb  this looks like this was done?  (default branch is now "main") -- was there a PR associated with it that we should note before closing?

**Comment by ultrasaurus** [comment]
fixed by https://github.com/cncf/tag-security/pull/644 -- thanks @himanshu007-creator
