### ISSUE TITLE
[Suggestion] Create listing of potential collaboration groups

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#638]
Description: There are a lot of security focused groups, communities, specs, standards that not everyone knows about.  These groups often look for additional contributors and collaborators to help drive robust documentation and design.  The Cloud Native community has a unique perspective and has the ability to positively impact the outcome of those groups.  

We should maintain a listing in our repo for members to refer to of additional groups and spaces for them to review, be aware of, or get involved with.

Impact: Provide broader community awareness of other efforts

Scope: Issue #21 has a start, and the group as discussed others in the past.  An initial README.md to create a list based off #21 in a folder `Partner Groups/` would be ideal.  A link or reference in the main README would direct visibility

Additional info:
- #21 
-

**Comment by PushkarJ** [comment]
+1

**Comment by magnologan** [comment]
+1
