### ISSUE TITLE
[Suggestion] Improve new member experience, allow easier involvement/induction

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#666]
Description: What's your idea?

Improve new member experience to allow members to be able to contribute faster, or get more comfortable with the contribution process. 

Impact: 

This will help strengthen the community by getting more members engaged. 

Scope: 

"not yet determined" 

Additional info:
- Current new members [page](https://github.com/cncf/tag-security/blob/main/NEWMEMBERS.md)

**Comment by TheFoxAtWork** [comment]
can we have a bot to message them when they join the channel with details about getting started "read this, create your first PR with us by tackling a good first issue"? and then in another post in a month to say "don't forget to introduce urself at a meeting and add urself to the repo"

**Comment by lumjjb** [comment]
It would be awesome if new members themselves to be involved with this so we can get feedback on what your questions are first when you joined the TAG!

**Comment by TheFoxAtWork** [comment]
i've also gotten questions about how to lead their first effort.  I've been sending them to the process page and linking the to paper process which has some details

**Comment by ultrasaurus** [comment]
regarding question of leading first effort, I would suggest that we direct them to our (hopefully well-groomed) backlog and to look for projects that already have a TL/chair sponsor but lack a project lead, and then chime in on issue that they are interested and willing to participate as project lead.

**Comment by sayantani11** [comment]
@lumjjb What can we do to contribute to this issue?

**Comment by lumjjb** [comment]
Hi @sayantani11 ! A perfect way for you to contribute to this is to provide some input about what you're experience is of a new member! And some suggestions, some problems you faced, what you think is lacking/we can do better. That would be super valuable! 

And maybe from that feedback we can determine if we can create a PR on the current process or even create a project from it!

**Comment by lumjjb** [comment]
Hi @sayantani11 ! Would you like to help out with this issue?

**Comment by sayantani11** [comment]
@lumjjb Guess I already made a PR for it!!!

**Comment by sayantani11** [comment]
https://github.com/cncf/tag-security/pull/798
cc @lumjjb

**Comment by anvega** [comment]
We've moved away from the static members file and how we onboard/engage with the community, understanding that the nature of the participation is fluid and members recognize each other for their active participation
