### ISSUE TITLE
Cloud Native Security Con at KubeCon+CloudNativeCon NA 2021

### ISSUE THREAD

**Issue by anvega** [cncf/tag-security#667]
**Description**:  
Planning and tracking for Cloud Native Security Con at the upcoming NA Kubecon/CloudNativeCon. Cloud Native Security Con is designed to foster collaboration, discussion, and knowledge sharing of discuss open source and cloud native security projects and how to best use these to address security challenges and opportunities.  

### Program committee

The responsibilities of the program committee include but are not limited to:
- Active involvement in CFP review, scoring, and schedule building process 
- PC Members should allocate 4-5 total hours to complete the CFP review during the review window
- Review of Diamond sponsor talk content + BoF proposals prior to approval
- (Where applicable) Support marketing efforts to drive registration
- Attend post-event debrief meeting

STAG Rep: @anvega 

Program Committee Members: @anvega @TheFoxAtWork @danpopSD 

CFP Reviewers: @anvega @TheFoxAtWork @danpopSD @ragashreeshekar @achetal01 @lumjjb @chasemp @ak-secops @nadgowdas

CTF: @sublimino  @denhamparry

### Logistics

**Slack channel:** #tag-security-events

**Dates:** Tuesday, Oct 12; 9:00a-5:00p PDT
Event spaces to be confirmed 30 days prior to the event

**Location:** Los Angeles Convention Center

**Attendees:** In-Person: TBD* / Virtual-Only: Unlimited

**Overall Timeline:**

May 26: Kick-Off Call
June 14-25:  Build CFP, Website, Sponsorship Prospectus
Week of June 28:  Launch website, CFP, Sponsorship Prospectus
July 25: CFP closes
July 26-Aug 8: PC CFP Review Window
PC Members should allocate 4-5 total hours to complete the CFP review during this time
July 29: Sponsorship Sales Close
Aug 9-19: PC & Event Lead meet 1-3 times to finalizing scoring and build event schedule
Aug 25: Schedule Announced (6.5 weeks of promotion)
Aug 26 - Event Day: Marketing + Outreach Support (as applicable)
Oct 1: Speaker Slides Due
October 11 or 12: Event Day

### To Do

- [X] Website: review past content and update as appropriate
- [] CFP prep
- [] CFP Review
- [] Security Day event schedule/planning
- [] "Day Of" Staff

**Comment by ragashreeshekar** [comment]
I’m interested to volunteer

**Comment by magnologan** [comment]
I'd like to be involved as well.

**Comment by ak-secops** [comment]
I'd like to be involved.

**Comment by lumjjb** [comment]
i'd like to help out with the CFP.

**Comment by ashutosh-narkar** [comment]
Happy to help review CFPs.

**Comment by nadgowdas** [comment]
I'd like to be involved.

**Comment by anvega** [comment]
We have several updates from CNCF Events to share with you that will impact the planning for Cloud Native Security Conference. Please see below for a health and safety update, sponsor sales launch, + confirmed event date & estimated room sizes. 

1. Proof of full COVID-19 vaccination will be required to attend KubeCon + CloudNativeCon North America 2021 & co-located events in person in Los Angeles. Anyone who is not fully vaccinated against COVID-19 will be able to participate in the event virtually. To learn more, please [click here](https://www.linuxfoundation.org/blog/adoption-of-a-covid-19-vaccine-required-approach-for-our-fall-2021-event-line-up/).
Questions you may have related to co-located events (please also see the [FAQ section of the announcement](FAQ section of the announcement)):

1. How will attendees and potential speakers be alerted about this requirement?

- Website FAQ to go live by the week of June 28
- Notification within the registration process
- Notification within the CFP process

2. What if I cannot/have opted not to receive the vaccine can I still participate in the Program Committee for this event?

- All engagements for the program committee prior to the event are conducted virtually.
- If a program committee member cannot be onsite there will be a role to play virtually during the event either in virtual sessions or slack to support the event and community.

2. Sponsorship sales are live!

- CNCF has launched [sponsorship sales](https://events.linuxfoundation.org/wp-content/uploads/2021/06/sponsor-cncf-2021.06.17.pdf) for all confirmed co-located events!
- Let us know if you have any questions + sponsorship leads to pursue.

3. Confirmed Event Date, Registration Fees, + Estimated Room Capacity:
**Event Date:** Tuesday, Oct 12
**Registration Fee Structure** [must register for KC+CNC NA and add-on the co-located event]:

- In-Person: $249 standard / $349 on-site [includes free virtual access]
- Virtual-Only: $20 

**Estimated In-Person Room Capacity:**  Room A: 300 Room B: 75 Room C: Smaller Room - Boardroom set for 12 Room D: Fixed Theater, 200

**Comment by achetal01** [comment]
I will like to help as well.
Thanks

**Comment by lumjjb** [comment]
@anvega shall we close out this issue 

Posting available publicly accessible data, and creating a PR to update the events page, and let's get a new issue created for EU 2022!

**Comment by TheFoxAtWork** [comment]
@anvega
