### ISSUE TITLE
[Suggestion] Supply Chain Security feedback

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#671]
Description: from twitter: https://twitter.com/clintgibler/status/1398046293340037121?s=19

1. The paper lists assurance/risk for each task. Would that be useful to add to the checklist?

* [ ] Map assurance levels to the [checklist we provided](https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/secure-supply-chain-assessment.md)

-------original-----

2. The paper includes a number useful references with more info. Would it be possible to make the guidance even *more* actionable / easy to follow? e.g.
* Template repos, scripts, ...

Impact: The paper is great, I'm just trying to think about it from a busy dev or sec engr perspective:

> OK I'm super busy and don't have time to look up much stuff, can you just give me the relevant code snippets/packages/settings/etc and I can get 80% there in a few days?

Scope: "not yet determined" 
CC: @jonmuk 

Additional info:
- Reference to supporting material
- Links to related site
- Feel free to delete this section if you don't have more info

**Comment by clintgibler** [comment]
Thanks @TheFoxAtWork! I've got a few things currently on my plate, but hopefully over the next few months, or at latest a quarter or two, I should have more detailed feedback, or at least things I would find super helpful.

Thank you everyone for the awesome work! 🙏 🎉

**Comment by anvega** [comment]
This is useful feedback. 

There are a number of planned companion resources to the paper. Of those companion resources, the first already published is the  [secure supply chain assessment document ](https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/secure-supply-chain-assessment.md).

The end goal of the workgroup behind the paper is to produce a framework of reusable common tools and templates. We're given plenty of consideration to discoverability and accessibility. One binary for all the assets and likely a github.io page to interactively navigate the different resources.

**Comment by TheFoxAtWork** [comment]
Reference architecture issue: https://github.com/cncf/tag-security/issues/679

Updating description to focus on assurance alignment in the checklist

**Comment by TheFoxAtWork** [comment]
@anvega are there other items to be done to close this out or bring up at a weekly meeting to determine appetite for completion?

**Comment by anandg112** [comment]
@TheFoxAtWork  I would like to contribute to this issue and come up with  actionable guidelines, relevant links for busy devs to make the checklist more robust. Please let me know how to proceed as this will be my first PR for this group.

**Comment by mlieberman85** [comment]
@anandg112 We have been working #679 which a first draft of is now getting finalized. See WG notes: https://docs.google.com/document/d/1MTM782nluFl4_ybG-fXHmRT2k4bPN18ifdzpUltQQCw/edit#heading=h.1tv8gumsrtbf

We will be looking for feedback soon on the draft. As far as next steps, we are still discussing those in the Thursday WG meetings which if you're interested we would love additional contribution to.

**Comment by anvega** [comment]
Several things here either slipped or fell out of scope. Worth revisiting if and when the best practices paper gets a second edition. Closing the issue for now.
