### ISSUE TITLE
Chaos Engineering Paper - App Delivery TAG looking for Security Contributors

### ISSUE THREAD

**Issue by achetal01** [cncf/tag-security#678]
Description: App delivery TAG is working on a Chaos Engineering White paper and will like to have contribution from tag Security. This will be exciting piece of work and integration with App Delivery TAG.

Initiative is just starting and details can be found at : https://docs.google.com/document/d/10l262yuX_Zj8ht1pqKlSZAk4-KxY1tc-PaVmbqIsoDw/edit

Impact: Chaos Engineering still needs to build security resiliency in their processes and ensure failures don't lead to security incidents and the apps/services can recover with security policies and controls in place, so its pertinent to build security into the Chaos engineering of apps/service

Scope:  "not yet determined" 

Additional info:
- Slack channel #chaoseng-cloudnative-whitepaper

**Comment by hyakuhei** [comment]
Hello, I'd like to offer to help in some capacity, whether it's writing on security impact/challenges or as a security editor later in the process, reading through the recommendations and looking for security challenges in described practices.

**Comment by pratiklotia** [comment]
I'd like to help as well.

**Comment by TheFoxAtWork** [comment]
@hyakuhei @pratiklotia Have you been hooked into this yet?  if so how is it going?

**Comment by achetal01** [comment]
Please Join the slack channel, so you can get the regular updates etc.

**Comment by lumjjb** [comment]
@achetal01 is this something that you're tracking, any update on this? if the paper is completed we can close this issue

**Comment by dutchshark** [comment]
The paper still appears to be a WIP as of today the current version is 1.0 and in status Draft and can be found [here](https://docs.google.com/document/d/10l262yuX_Zj8ht1pqKlSZAk4-KxY1tc-PaVmbqIsoDw/edit).

**Comment by achetal01** [comment]
yes I am tracking this, let me follow up with the group and will update the
issue.

Thank you

**Comment by anvega** [comment]
It looks like the app delivery tag didn't get around the paper's publication. At least I couldn't find it. Does look from the google doc link that a number of tag security folks chimed in with feedback. Given that round of comment was completed, I'll proceed with closing the issue for now.
