### ISSUE TITLE
[Suggestion]  Fix design README when new artwork is available

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#683]
Description: 

Due to change in artwork, we have updated the files in the repo (https://github.com/cncf/tag-security/pull/682). However, there is still some outstanding artwork that needs to be added to repo, thus there are current missing links, this needs to be fixed when artwork becomes available.

Impact:

Fix repo broken links.

Scope:'

Not much, just a simple PR once the artwork is ready.

**Comment by TheFoxAtWork** [comment]
@lumjjb are there specific links that are broken where the artwork should be?

**Comment by TheFoxAtWork** [comment]
related #717
