### ISSUE TITLE
[Suggestion] Cloud Native Security day should be reflected in the repo

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#695]
Description: 

Cloud Native Security day should be reflected in the repo with links to the respective events as well as those that were involved to help make it happen.

Impact: 

Allow those that are new to the group to gain visibility to activities that the group has done, and to get context and reach out to others if they are interested in a certain activity. As a subgoal to preserve knowledge in the repo.

Scope: 

Probably a couple hours of finding old issues and synthesizing them into a `.md` file.

**Comment by IAXES** [comment]
Is there a specific pattern to the issues we should be looking for and adding to the collection in the resulting `.md` file (i.e. issues containing `[ASSESSMENT]`, `RFC`, `Event` or something like that in the title)?

**Comment by lumjjb** [comment]
Probably easiest way is to look for past closed issues as well as the slack
channel #tag-security-events . I'd start with those. And also looking at
past kubecon colo listings within the past 2 years.

**Comment by sayantani11** [comment]
@lumjjb Can I do this?
But I would require a bit of help of where to start?

**Comment by lumjjb** [comment]
Hi @sayantani11 , a good starting point would be gathering together some of the issues and links to some of the past Cloud Native Security Days/Cons.
issue links: https://github.com/cncf/tag-security/issues/454, https://github.com/cncf/tag-security/issues/416, #305 , #209 

event links: (this is just the first one, they should be available somewhere in the CNCF site past event archives)
https://events19.linuxfoundation.org/events/cloud-native-security-day-2019/

We hope to have a page that says something along the lines of a `events/cloud-native-security-day.md`. Content would look something like below. If you feel comfortable, feel free to take a stab at it and create a PR. You can also reach out to cncf-tag-security-leads@lists.cncf.io, and one of us can coordinate a chat with you!:

One of the things we do as a community is Cloud Native Security day, this usually is held at ..., and usually involves activities like ....

Here are some references to some of the past events:
...

And here are some of the issues that detail the organization/planning of these events:
...

**Comment by sayantani11** [comment]
@lumjjb I think this PR should do it

**Comment by lumjjb** [comment]
resolved - thanks @sayantani11 ! Be sure to add yourself to the members list with a PR to the README.md

**Comment by sayantani11** [comment]
@lumjjb Can you please tell me which README.md file I should make the PR to?
