### ISSUE TITLE
[Security Review] Project Name

### ISSUE THREAD

**Issue by jnswindle** [cncf/tag-security#698]
Project Name: 

Github URL:

CNCF project stage and issue (NA if not applicable):

Security Provider: yes/no (e.g. Is the primary function of the project to support the security of an integrating system?)

- [ ] Identify team
   - [ ] Project security lead
   - [ ] Lead security reviewer
   - [ ] 1 or more additional reviewer(s)
   - [ ] Every reviewer has read [security reviewer guidelines](https://github.com/cncf/tag-security/blob/main/assessments/guide/security-reviewer.md) and stated declaration of conflict
   - [ ] Sign off by 2 chairs on reviewer conflicts
- [ ] Create slack channel (e.g. #sec-assess-projectname)
- [ ] Project lead provides draft document - see [outline](https://github.com/cncf/tag-security/blob/main/assessments/guide/joint-review.md)
- [ ] "Naive question phase" Lead Security Reviewer asks clarifying questions 
- [ ] Assign issue to security reviewers
- [ ] Initial review
- [ ] Presentation & discussion
- [ ] Share draft findings with project
- [ ] Assessment summary and doc checked into /assessments/projects/project-name (require at least 1 co-chair approval)
- [ ] CNCF TOC presentation (if requested by TOC)

**Comment by lumjjb** [comment]
Empty issue template. closing...
