### ISSUE TITLE
[Suggestion] SBOM Collaboration

### ISSUE THREAD

**Issue by fkautz** [cncf/tag-security#713]
Description: it will be good to work with other organizations to build consensus on CNCF SBOM guidelines and support tooling.

Will fill out more details here soon. (Currently mobile)

**Comment by lumjjb** [comment]
Great discussions on this today, I think a good next step is to have one of the weekly meetings be a presentation followed by a discussion, and we can advertise this discussion meeting a bit more broadly to other communities as well. If 1 or 2 folks want to volunteer to put together some slides that the discussion can be around, that would be perfect!

Tagging other participants on the call

@knewcomerRH @anvega @nadgowdas

**Comment by nadgowdas** [comment]
thanks @lumjjb that sounds good, I can volunteer to some slides together for discussion.

**Comment by nadgowdas** [comment]
I recently published a blog around this topic: https://nadgowdas.github.io/blog/2021/trust-sbom/
Welcome everyone's feedback:)

**Comment by lumjjb** [comment]
Time for a revisit? @fkautz

**Comment by anvega** [comment]
Plenty of collaboration has occurred in this space. Given that it is part of the active charter from the supply chain working group, we'll close the issue for now. Thanks for having raised this in the first place when you did so.
