### ISSUE TITLE
[Presentation] Shift-left Automatic Generation of Network Policies

### ISSUE THREAD

**Issue by fabolive** [cncf/tag-security#715]
Title:  Shift-left Automatic Generation of Network Policies

Speakers: Ziv Nevo (@zivnevo); Fabio Oliveira (@fabolive)

Description: This presentation looks at the problem of simplifying the experience of creating K8s NetworkPolicies for zero-trust environments. Recognizing how hard it is for users to create and manage K8s NetworkPolicies to enable just the right amount of connectivity (not more or less), we propose a solution to automating the generation of NetworkPolicies without having to run the applications' code. We will demo it. We would like to start a conversation to foster a community to join us in building an open ecosystem of tools.

Time: How long will the presentation take? 30 min

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page. Our **preferred date is Wednesday, July 14**. If July 14 cannot be accommodated, any Wednesday after that also works. 

TO DO
- [X] TAG Representative: @lumjjb 
- [X] Schedule Date: July 21st
- [x] By opening this issue, I, (@fabolive/Fabio Oliveira) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)
- [x] link to presentation: **netpol-cncf.pptx**

**Comment by TheFoxAtWork** [comment]
@fabolive if you have some slides would you slack/link them to me so i can review prior to the presentation?

**Comment by lumjjb** [comment]
Swapping with @TheFoxAtWork for other presentation TAG rep because of conflict with Kyverno presentation (https://github.com/cncf/tag-security/issues/716)

**Comment by lumjjb** [comment]
@fabolive due to scheduling, are you able to make the presentation on 21st July instead?

**Comment by lumjjb** [comment]
> @fabolive if you have some slides would you slack/link them to me so i can review prior to the presentation?

@TheFoxAtWork , @fabolive sent me the slides and I have reviewed slides for the presentation.

**Comment by fabolive** [comment]
Hi @lumjjb. Yes, July 21st works for us.

**Comment by fabolive** [comment]
@TheFoxAtWork: I will send you the slides shortly.

**Comment by fabolive** [comment]
@TheFoxAtWork: Here is the presentation.
[netpol-cncf.pptx](https://github.com/cncf/tag-security/files/7048274/netpol-cncf.pptx)

Additionally, we added the following link to the corresponding CNCF Security TAG Google doc:https://github.com/shift-left-netconfig/shift-left-netconfig.github.io/blob/master/presentations/cncf-sec-tag-07-21-2021.pptx

**Comment by TheFoxAtWork** [comment]
yep thanks so much!!
