### ISSUE TITLE
[Presentation] Kyverno Overview and Demo

### ISSUE THREAD

**Issue by JimBugwadia** [cncf/tag-security#716]
Title: **Kyverno Overview and Demo** ([slides](https://docs.google.com/presentation/d/1-s7r13Ko33JZKQrFtSdgAwV1I2HFTLIs/edit#slide=id.p1))

Speakers: @JimBugwadia

Description: 

An overview of Kyverno with a demonstration of key use cases it addresses. 

Time: How long will the presentation take? 

15-30 mins

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page.

- Wed Jun 30th 10:00 AM PST
- Wed Jul 7th 10:00 AM PST
- Wed Jul 14th 10:00 AM PST
- 

TO DO
- [x] TAG Representative @TheFoxAtWork 
- [x] Schedule date - July 7th
- [x] By opening this issue, I, (@JimBugwadia) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

cc: @jlk

**Comment by lumjjb** [comment]
Awesome Thanks @JimBugwadia , i've put you down for the 30th of June! Looking forward to this presentation!

**Comment by JimBugwadia** [comment]
@lumjjb apologies for the late notice, but can we please try for Jul 7th instead?

**Comment by lumjjb** [comment]
Yes, certainly, moving this to July 7th

**Comment by TheFoxAtWork** [comment]
So excited to see a project from the Security Pals effort present!

**Comment by TheFoxAtWork** [comment]
@JimBugwadia @jlk - reminder to post the link to the slides in the issue comments :)

**Comment by JimBugwadia** [comment]
Here are the slides: 

   https://docs.google.com/presentation/d/1-s7r13Ko33JZKQrFtSdgAwV1I2HFTLIs/edit#slide=id.p1

**Comment by jlk** [comment]
Looks good. I think emily's looking for that link in the GH issue for the
talk. :)

**Comment by lumjjb** [comment]
Closing this! Thanks for the presentation @JimBugwadia
