### ISSUE TITLE
[Suggestion] provide suggested fix for cSpell errors

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/tag-security#724]
Description: add helpful error message for spelling lint errors

Impact: speed up PR review/resolution by teaching contributors to fish!

Scope: I would expect it to take a few hours for someone with pretty good bash skills

Additional info:
- https://github.com/cncf/tag-security/issues/311

Suggestion:  suppose the linter caught "darkmode" and "foobar" then we could include a message like:

````
If the errors are names, external links, or unusual, but accurate technical words, 
then you should create an inline comment like:
<!-- cSpell:ignore darkmode foobar -->
of course, you should only include non-dictionary words that are correctly spelled!

If the error happens because of a common technical term or proper name that is likely
to appear many times, then please edit "ci/spelling-config.json"
```

**Comment by lumjjb** [comment]
Another instance to consider: https://github.com/cncf/tag-security/pull/717

**Comment by sayantani11** [comment]
Hey!! Can I be of any help?
