### ISSUE TITLE
[Suggestion] Improvements to CONTRIBUTING guide

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/tag-security#726]
Description: there are a number of ideas/needs scattered across different issues, let's look at this holistically and see what's needed

Impact: increase contributions by reducing friction get started for new contributors and help experienced contributors follow new processes

Scope: 4-12 hours spread across a few people (creating PRs, reviewing) which should happen over at least a week for appropriate group feedback and could happen over several weeks/months

TO DO:

- [x] https://github.com/cncf/tag-security/pull/722
- [ ] fix so Contribution Guide is linked from github insights tab (see note below)
- [ ] consider issues that contain work items to add to CONTRIBUTING (which motivated above refactor)
  - https://github.com/cncf/tag-security/issues/613
  - https://github.com/cncf/tag-security/issues/311
  - https://github.com/cncf/tag-security/issues/277
- [ ] TODO: search open issues to review other issues that may reference CONTRIBUTING

**Comment by TheFoxAtWork** [comment]
recommend linking to the copyright information from the CNCF:
https://github.com/cncf/foundation/blob/master/copyright-notices.md

**Comment by ultrasaurus** [comment]
FYI -- refactoring CONTRIBUTING.md into directory named CONTRIBUTING broke github auto-linking in Community page

![image](https://user-images.githubusercontent.com/41906/125712663-a4f91bc5-9182-4a48-b933-811baacb1e3c.png)

File naming options here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

I'm inclined to rename directory to all lower case  `/contributing` and make a pointer in .github/contributing.md and the root README.  I don't feel strongly, so dropping this note here in case other folks want to chime in.

cc @lumjjb

**Comment by lumjjb** [comment]
>I'm inclined to rename directory to all lower case /contributing and make a pointer in .github/contributing.md and the root README. I don't feel strongly, so dropping this note here in case other folks want to chime in.

I like this!

**Comment by anvega** [comment]
Contributing is now structured as 4 files.
