### ISSUE TITLE
Request Briefing from Mastercard

### ISSUE THREAD

**Issue by ckemper67** [cncf/tag-security#75]
At Kubecon Mastercard expressed interest in Google's thoughts on OPA and we assume that Mastercard may be interested in ABAC. I think it would be interesting to hear from them in the context of SAFE. 

@dshaw mentioned that he has contacts at Mastercard.

**Comment by lumjjb** [comment]
@dshaw any leads here or shall we close this in the meantime?

**Comment by lumjjb** [comment]
@dshaw any leads here or shall we close this in the meantime?

**Comment by lumjjb** [comment]
@dshaw shall we close this? and re-open if the conversation comes up again.

**Comment by TheFoxAtWork** [comment]
closing stale and likely OBE (overcome by events)
