### ISSUE TITLE
Fix spell/link in governance/related-groups/README.md

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#751]
There are some issues with the CI based which need to be fixed for the following file:

https://github.com/cncf/tag-security/blob/main/governance/related-groups/README.md

**Comment by ChetanVyas** [comment]
hey I am beginner, I want to work on this issue, but wont able to understand CI part can you please elaborate.

**Comment by lumjjb** [comment]
Hey @ChetanVyas . Awesome - so to provide some context of this, there are several issues with the linker checker and spell checker with this file.. The errors were exposed (but not caused) by this PR https://github.com/cncf/tag-security/pull/750. The main part of this issue is to resolve those CI errors by editing the file / CI config (I elaborate a bit more below on the specific errors for this particular file). 



## Spell check errors:
https://github.com/cncf/tag-security/runs/3306492222

You will see from the error messages that most of them are github IDs, and we have SLSA (which is one of the frameworks). The best way to probably handle this is before every line with the offending github ID, we can make a `cSpell` exception like:

`<!-- cSpell:ignore rficcaglia-->`

And for SLSA, we can add it to the cSpell configuration word exception list https://github.com/cncf/tag-security/blob/main/ci/spelling-config.json

## Link check error:
https://github.com/cncf/tag-security/runs/3306492266

For this, we could just remove the broken link - or fix it if there's an alternative.

## Testing it

If you open a PR, it should automatically run the CI and you should be able to view the results of your changes effect on the CI on github. If you like, you may also run this locally via the `make spelling` or `make links` command in your local cloned git repository. 

Hope this helps!

**Comment by ChetanVyas** [comment]
Got it, need to make changes like the bellow so it will ignore IDs :
  * Security TAG members: @justincormack , @lizrice

and in spelling-config.json :
 "words": [
        "justincormack",
        "lizrice",

And about the link check error, I won't able to find the working URL on " https://standards.ieee.org/ "  for : 
P1915.1 (COM/NetSoft-SC) 
Standard for Software Defined Networking and Network Function Virtualization Security 
(New PAR)

**Comment by lumjjb** [comment]
Yup exactly! For the link, you can just remove it for now.

**Comment by lumjjb** [comment]
Addressed by https://github.com/cncf/tag-security/pull/754! Closing.
