### ISSUE TITLE
[Presentation] Curiefense

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#758]
Title: What is the title of your presentation?

Curiefense

Speakers: Who will be presenting this? List names/github IDs of presenters.

Description: Describe in a short paragraph what the presentation is about.

Time: How long will the presentation take? (estimate)

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page.

TO DO
- [x] TAG Representative @lumjjb 
- [x] Schedule date - TBD
- [ ] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by lumjjb** [comment]
hi @jdorfman , could you tag the folks here. Looking forward to the presentation on Curiefense!

**Comment by jdorfman** [comment]
@lumjjb I talked to @tzuryby and he can do it Wed Sept 1st. Is that open?

**Comment by lumjjb** [comment]
Unfortunately we have another presentation scheduled for Sep 1st, will the following week work? Sep 8th?

As an aside, also can the presenter also acknowledge: 

"I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)"

**Comment by jdorfman** [comment]
@lumjjb Ok I'll ask him. I will have an answer by tomorrow (since he's 10 hours ahead)

**Comment by jdorfman** [comment]
@lumjjb lets put it down for the 8th and if we need to change it hopefully that won't be a problem.

**Comment by lumjjb** [comment]
Awesome i'll put that down then.. just need your acknowledgment of the adherence to presentation guidelines, and will be good if some slides can be shared beforehand.

"I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the presentation guidelines"

**Comment by jdorfman** [comment]
@lumjjb Tzury needs to reschedule to October and I don't have access to his calendly past September.

Do you want to close this issue or just keep it open until we can find a date?

Apologies for any inconvenience this has caused.

**Comment by lumjjb** [comment]
no worries we'll keep this open and schedule a date in october

**Comment by jdorfman** [comment]
You rock thanks @lumjjb!

**Comment by lumjjb** [comment]
Hey @jdorfman, the next likely date available will be towards the last week of October (due to kubecon scheduling)

**Comment by jdorfman** [comment]
@lumjjb sounds good, lets pick this up then.

**Comment by lumjjb** [comment]
Hi @jdorfman, shall we pick this up?

**Comment by lumjjb** [comment]
Closing out this issue for now
