### ISSUE TITLE
[Presentation] Cartografos Working Group Maturity Model

### ISSUE THREAD

**Issue by siforster** [cncf/tag-security#759]
Title: What is the title of your presentation? **Cartografos Working Group Maturity Model**

Speakers: Who will be presenting this?
Simon Forster (@siforster)
Danielle Cook (@daniellemcook)
John Forman (@Deep-Cyber)
Robert Glenn (@robertglenn)

Description: The [Cartografos Working Group](https://github.com/cncf/cartografos) has produced a five-level maturity model that includes four key areas of people, process, policy, and technology.  The model is intended to be of use to end-users cloud native technology, contributors to the CNCF, as well as projects and TAGs within the CNCF.
The presentation will identify why the model was produced and the needs it is intended to address; who it was created for; the current artefacts, and the roadmap for further development and iteration.
We will address how we wish to work together with TAGs and Projects to ensure effective and appropriate representation for their relevant topic and technology areas.
We view TAG Security as an important stakeholder as security is weaved through all four key areas of people, process, policy and technology and the model may serve as a useful vehicle for conveying this to end users.

Time: How long will the presentation take? **45 Minutes**

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page.
US: Weekly on **Wednesdays at 10:00am UTC-7 meeting** on the following dates: **22 or 29 September (29th preferred; we can consider other dates outside this range)**

TO DO
- [X] TAG Representative: @TheFoxAtWork 
- [X] October 6th
- [X] By opening this issue, I, Simon Forster (@siforster), acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by siforster** [comment]
@TheFoxAtWork Hi there, because one of our co-chairs and presenters is unable to make the 29th, we wanted to see if it would be possible to ove this to the 22nd of September.  Apologies for this late change.

**Comment by TheFoxAtWork** [comment]
@siforster We have a presentation already schedule for the 22nd.  The 15th is open as is October 6th. the 13th is cancelled for KubeCon, but the 20th and 27th of October are free. Do any of those work?

**Comment by siforster** [comment]
Thank you for the quick response Emily.  I have messaged the team with the dates and will confirm with you as soon as I can.

**Comment by siforster** [comment]
@TheFoxAtWork We would be very grateful if we could go with the 6th of October.  All four speakers are able to make this date.  Many thanks for your patience with this.

**Comment by TheFoxAtWork** [comment]
Done.

**Comment by siforster** [comment]
Thank you very much!

**Comment by siforster** [comment]
The slides are located here:

https://docs.google.com/presentation/d/180ZcX9KxQSUlQo5cDCJn8zN8oawi6x9DQ8xg1GLDkpA/edit

Slack is the best way to get hold of The Cartografos Working Group.  We are on CNCF Slack as `cartografos-wg`:
https://cloud-native.slack.com/archives/C026EQ8LU2Z

The spreadsheet we presented is located here.  It contains summarised baseline information that went into the model.  We woudl also appreciate any input from TAG-Security to help categorise projects at their most appropriate level from TAG-Security's perspective.

**Comment by TheFoxAtWork** [comment]
Fabulous!  

I would strongly recommend putting out a [call to action ](https://github.com/cncf/tag-security/blob/main/governance/communications/call-to-action.md) on this topic to our [mailing list](https://lists.cncf.io/g/cncf-tag-security/topics) with:
* a [link to the recording](https://www.youtube.com/watch?v=28NTegKt6yg)
* a link to the slack channel
* one or two SPECIFIC areas that need attention
* due dates or deliverable dates for items
* who specifically to contact directly (not everyone is comfortable posting in slack channels and DMs are a more approachable option for some folx.
