### ISSUE TITLE
[Suggestion] Trying to understand the criterion for tools in Security Assurance

### ISSUE THREAD

**Issue by JasonKeirstead** [cncf/tag-security#766]
I am trying to understand the criterion for the tools in these various pages.

I will focus on one example, Threat intelligence: ( https://github.com/cncf/tag-security/blob/cnsmap/content/threat-intelligence.md )

The page does not really describe in detail the threat intelligence space. The links are a bit of a grab bag of TIPs, sharing tools, and data feeds. Also,1 of the links is to something that is not open source, it is commercial (ThreatCrowd). Yes it is free, but there are a lot of other commercial providers that provide free threat intel that could be added here. Can/should they be? Also should this page go into more detail on how to use threat intelligence?

I am happy to contirbute to fleshing out this page more. Just trying to understand the goal first before stepping on toes with a gigantic PR.

I have similar feedback for all of the pages under the "Security Assurance" area (which is my balewick & why I am focusing on that one)

**Comment by lumjjb** [comment]
Hi @JasonKeirstead, how's it going on this issue!

**Comment by lumjjb** [comment]
Hey @JasonKeirstead! How's it going - just pinging back on this.

**Comment by anvega** [comment]
@JasonKeirstead, thanks for bringing attention to the issue. Agree with you that the substance in that section you point out needs to be improved. We'd appreciate it if you could still get around the PR to raise the integrity and relevance of the paper. For now, I'll close the issue and await the PR.
