### ISSUE TITLE
[Presentation] SPIFFE Tornjak: A control plane for workload identities

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#769]
Title:

SPIFFE Tornjak: A control plane for workload identities

Speakers: @lumjjb @mrsabath

Description: 

Tornjak aims to provide a management plane and capabilities for SPIFFE identities managed by SPIRE. The goals are to provide global visibility, auditability, and configuration and policy management for identities. This can be thought about as a central management plane for identities across SPIRE servers, with the aim for use by an administrator or CISO to govern an organization's workload identities.

We will also cover briefly about some usecases that Tornjak with SPIRE can help solve by moving workload identity from a cloud-specific concept to the cloud-agnostic platforms such as kubernetes.

Time: How long will the presentation take? (estimate) 30 mins

Availability: 2nd week of September onwards should be good

TO DO
- [X] TAG Representative @TheFoxAtWork 
- [X] Schedule date **Sept 22**
- [x] By opening this issue, I, @lumjjb  acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by lumjjb** [comment]
We'd like to request the 22nd September meeting slot (looks like there's no planned agenda yet)

**Comment by TheFoxAtWork** [comment]
@lumjjb please remember to link your slides to the issue! :)

**Comment by lumjjb** [comment]
[SecurityTAG.2021-09-v2.pdf](https://github.com/cncf/tag-security/files/7213741/SecurityTAG.2021-09-v2.pdf)
