### ISSUE TITLE
Unexpected error on CNSMap in chapter Containers

### ISSUE THREAD

**Issue by MMerzinger** [cncf/tag-security#771]
Hello everyone

Opening the [CNSMap](https://cnsmap.netlify.app/) and navigating to __Runtime -> Compute -> Containers__ I get an "An unexpected error has occurred." error:
<img width="1439" alt="Screenshot 2021-08-31 at 13 06 10" src="https://user-images.githubusercontent.com/18420443/131540095-343e9d61-2a5f-4ef7-a92a-b66797ffc9f1.png">

To reproduce checkout the cnsmap Branch and run via "npm run dev". Then navigate to __Runtime -> Compute -> Containers__. With Chrome I get the following error:
<img width="1439" alt="Screenshot 2021-08-31 at 13 04 17" src="https://user-images.githubusercontent.com/18420443/131540231-446b0848-f8d0-4ad4-9146-ef091a2944b3.png">

It looks like the containers.md file is missing.

**Comment by lumjjb** [comment]
Fixed by #772
