### ISSUE TITLE
[Suggestion] modify Security assessment process

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#788]
Description: Modify the Security Review process to:
* [ ] initiate a draft/WIP PR of the self-assessment and/or joint-review prior to the presentation to closeout the review
* [ ] clearly set the joint-readme and joint-review and/or self-assessment as required for the PR finalization in the process doc. 
* [ ] Modify co-chair requirements to verify the above items are complete and presentation has occurred prior to approving and merging.

**Comment by TheFoxAtWork** [comment]
If anyone is interested in working on this lightweight PR i'm more than happy to coach/mentor/walkthrough/explain!

**Comment by lumjjb** [comment]
@IAXES can you look into this issue since you're looking at making some PRs to assessment process.

**Comment by IAXES** [comment]
Assigning (to self).

**Comment by anvega** [comment]
Several updates were made to the assessment process since the filing of this issue. All modifications suggested here were made. If, for any reason there was anything outstanding, feel free to reopen or create a new issue.
