### ISSUE TITLE
[Presentation] Artifact References - storing graphs of artifacts in distribution spec based registries

### ISSUE THREAD

**Issue by SteveLasker** [cncf/tag-security#794]
Title: Artifact References - storing graphs of artifacts in distribution spec based registries

Speakers: @stevelasker, @sajayantony

Description: [OCI Artifacts](https://github.com/opencontainers/artifacts) generalized the ability to persist artifacts within an [OCI Distribution conformant](https://github.com/opencontainers/oci-conformance/tree/main/distribution-spec) registries enabling a wide range of *individual* artifacts. With a focus on adding new supply chain artifacts, existing registries can be leveraged to add these new capabilities, enabling users to promote their signed artifacts, SBoMs, security scan results and other content into their secured environments. 

Time: ~30 mins

Availability: September 29th 

TO DO
- [x] TAG Representative (@anvega)
- [x] Schedule date
- [x] By opening this issue, I, (@stevelasker) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by anvega** [comment]
Thanks for expressing interest to share your work with the community, @SteveLasker! 

There is currently a slot open for presentation Wednesday, September 29th, at 10 am pacific time. Do that time and date work for you?

If you're planning to use any slides during your presentation, please include the link to the content ahead of the presentation. You can add that here on this issue.

**Comment by SteveLasker** [comment]
Thanks @anvega 
Sept 29 @10 pacific will work just fine. For those that want to pre-read, I'll use [this deck](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fraw.githubusercontent.com%2FSteveLasker%2FPresentations%2Fmaster%2Foci-artifacts%2FArtifacts-SupplyChain.pptx&wdOrigin=BROWSELINK) as the baseline

I'll update as we get closer to next week.
Thanks,
Steve
