### ISSUE TITLE
Cloud Native Security Policy Draft Whitepaper - Presentation

### ISSUE THREAD

**Issue by achetal01** [cncf/tag-security#796]
Title: What is the title of your presentation?
Cloud Native Security Policy Whitepaper

Speakers: Who will be presenting this? List names/github IDs of presenters.
Jim Bugwadia, Robert, Jaya, Aradhna
Description: Describe in a short paragraph what the presentation is about.
It is about the Policy working group- They have been working on a policy whitepaper for cloud native technologies. 

Time: How long will the presentation take? (estimate)
30 minutes

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page.

TO DO
- [x] TAG Representative Aradhna Chetal
- [x] Schedule date 9/22
- [X] By opening this issue, I, (@achetal01 ) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by achetal01** [comment]
Thanks

**Comment by TheFoxAtWork** [comment]
call to action sent: https://lists.cncf.io/g/cncf-tag-security/message/70
