### ISSUE TITLE
[Suggestion] New Participant first contributions

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#797]
Description: 
Based on feedback from issue #666 , we'd like to make changes to the information we provide new participants/members to ensure their contributions and engagement with the group is successful, positive, and enduring.

Scope: 

- [ ] Create a new file in [CONTRIBUTING/](https://github.com/cncf/tag-security/tree/main/CONTRIBUTING) called "first-time-contributions"
- [ ] New file should include:
  - [ ] Where to find good-first-issues
  - [ ] who to contact (co-chairs & tech leads - link to who they are in the repo) and how to contact (slack DMs or channel #tag-security-governance or via email cncf-tag-security-leads@lists.cncf.io ) if there are any questions, comments, requests for help in contributing
  - [ ] Link to instructions on contributing to an open source project: https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution & https://docs.github.com/en/github/collaborating-with-pull-requests 
  - [ ] If the issue under good-first-issue isn't clear comment on it!  ask the submitter for more details or contact the co-chairs and tech leads, they are here to help!
  - [ ] let them know that contributing to open source can be scary, overwhelming, or can make them feel some doubt, its to be expected.  We are happy to have a one-on-one discussion, mentor them, and ensure their contribution is successful so they can keep it up.
- [ ] Update the [NEW-MEMBERS](https://github.com/cncf/tag-security/blob/main/NEW-MEMBERS.md) doc to link to a **new** file in [CONTRIBUTING/](https://github.com/cncf/tag-security/tree/main/CONTRIBUTING) called "first-time-contributions"

CC: @sayantani11

**Comment by sayantani11** [comment]
This is great 🎉

**Comment by sayantani11** [comment]
@TheFoxAtWork Can I make a PR for it?

**Comment by TheFoxAtWork** [comment]
YES. Please do and link to the issue!
