### ISSUE TITLE
[Suggestion] Cloud Native Security Stacks

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#807]
Description: Software Development has development stacks (MEAN, Spring, Metero, LAMP) which make getting up and running quick and easy.  This suggestion is to curate a series of Cloud Native Security stacks.

Impact: By developing or documenting Cloud Native Security Stacks, organizations and endusers can be confident in their implementations as interoperable, more secure, and easier it adopt

Scope: No idea.

Related to several items:
- Cloud Native Security Map @lumjjb @ashutosh-narkar 
- Cloud Native Security Defaults @PushkarJ

**Comment by ultrasaurus** [comment]
I suggest we take issues like this and add them to a doc of inactive suggestions at the root of the repo (or somewhere) then if someone wants to take them on, they can make an issue (which means they will be able to edit the description).

**Comment by lumjjb** [comment]
>I suggest we take issues like this and add them to a doc of inactive suggestions at the root of the repo (or somewhere) then if someone wants to take them on, they can make an issue (which means they will be able to edit the description).

This sounds like an idea to add on to the current planned microsite (#110). Microsite is going to be a priority for us upcoming next year.

**Comment by lumjjb** [comment]
@PushkarJ is this something that is of interest in adding to the CNSWPv2?

**Comment by PushkarJ** [comment]
@lumjjb IMO, We could do it as a follow up to #737

**Comment by anvega** [comment]
Given it's been a few years since the proposal didn't garner enough support to get started, we will be closing the issue. It can be revisited if there is renewed interest and commitment to work on it.
