### ISSUE TITLE
SecurityCon at KubeCon+CloudNativeCon EU 2022

### ISSUE THREAD

**Issue by anvega** [cncf/tag-security#811]
Now that SecurityCon events for 2021 are wrap its time to prepare and plan for next year. This issue will track activities related to TAG Security events for upcoming year.

SecurityCon is designed to create a focus space to foster collaboration, discussion, and knowledge sharing of OSS Security. 

Program committee
The responsibilities of the program committee include but are not limited to:
* Active involvement in CFP review, scoring, and schedule building process
* PC Members should allocate 4-5 total hours to complete the CFP review during the review window
* Review of Diamond sponsor talk content + BoF proposals prior to approval
* (Where applicable) Support marketing efforts to drive registration
* Attend post-event debrief meeting

STAG Rep: @anvega
Program Committee Members: 
CFP Reviewers:
CTF team: 
Logistics
Slack channel: #tag-security-events
Dates: 
Location:
Attendees:

Overall Timeline:
TBD

To Do
* 		Website: review past content and update as appropriate
* 		[] CFP prep
* 		[] CFP Review
* 		[] Security Day event schedule/planning
* 		[] "Day Of" Staff

**Comment by ragashreeshekar** [comment]
Im interested to join. Please add me

**Comment by sublimino** [comment]
Happy to join CTF and CFP review 🙏 /cc @denhamparry 

Will also be there on the day 🎉

**Comment by fkautz** [comment]
I would like to be involved.

**Comment by ashutosh-narkar** [comment]
I'm happy to be a CFP reviewer.

**Comment by ak-secops** [comment]
I would like to be involved.

**Comment by oxeye-ron** [comment]
I'd be happy to participate

**Comment by lumjjb** [comment]
Happy to participate as cfp reviewer

**Comment by nadgowdas** [comment]
I am happy to participate

**Comment by jlk** [comment]
Love to help out as needed - hoping to be there in person! Small chance I'll dream up a talk proposal, will bow out of CFP review if I do.

**Comment by pabloopez** [comment]
I would like to get involved in the CTF side of it and learn more about it.

**Comment by ragashreeshekar** [comment]
Hello @jlk @nadgowdas @oxeye-ron @ak-secops @ashutosh-narkar @fkautz @chasemp 
Please share your email IDs 1-1 to @anvega or me over slack, and we will add you to the contributors for the SecurityCon mailing list. Thanks

**Comment by pratiklotia** [comment]
I would like to be involved with the CTF and CFP review.

**Comment by lumjjb** [comment]
@anvega can we update the issue notes - would it help to create a separate issue for NA as well?

**Comment by lumjjb** [comment]
Created new tracking issue for NA https://github.com/cncf/tag-security/issues/939

**Comment by szh** [comment]
Should this be closed now that the event has passed?
