### ISSUE TITLE
[Presentation] Self Assessment for LitmusChaos

### ISSUE THREAD

**Issue by ksatchit** [cncf/tag-security#813]
Title: What is the title of your presentation?
Run through of the Self Assessment for LitmusChaos Project 

Speakers: Who will be presenting this? List names/github IDs of presenters.
Karthik Satchitanand (@ksatchit) , maintainer, LitmusChaos 

Description: Describe in a short paragraph what the presentation is about.
This presentation will introduce the CNCF sandbox project LitmusChaos, which provides a cloud-native platform for the practice of chaos engineering & run through the self-assessment created by the project team in accordance with the instructions [here](https://github.com/cncf/tag-security/tree/main/assessments/guide#security-review-package-steps).

Self-Assessment Document: https://bit.ly/3nwADqp

The LitmusChaos project has been proposed for incubation (https://github.com/cncf/toc/pull/569) -TOC Sponsor @dims 
DD Document: https://bit.ly/3Gmciw9

Time: How long will the presentation take? (estimate)
~35 minutes. 

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page.
~~Oct 27th (Was recommended by the STAG representative @PushkarJ to present on Oct 27th meeting)~~
Available to present in the next weekly meeting (3rd Nov) / when provided a timeslot by the TAG leads. 

TO DO
- [ ] TAG Representative
- [ ] Schedule date
- [ ] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by ashutosh-narkar** [comment]
LitmusChaos is an incubated project. See https://github.com/cncf/tag-security/issues/863 to track a future security assessment.
