### ISSUE TITLE
TAG-security calendar for meeting invites

### ISSUE THREAD

**Issue by savitharaghunathan** [cncf/tag-security#818]
Short version: Is there a tag-security calendar subscription available, asking mainly for automated invites. 

We had a discussion in the Cloud Native Security White Paper version 2 meeting regarding calendar invites. As of now there are few ways to get the TAG-security/related initiatives meeting invitations
1. Subscribe to CNCF calendar, that comes with every TAG meeting invites making it super noisy
2. Create your own calendar invite
Both of the above methods are hard to manage. Starting this thread here to discuss other possibilities that would make everyone's life a bit easier. Thanks :) 

cc: @lumjjb @anvega @PushkarJ

**Comment by lumjjb** [comment]
This is something that would be SUPER useful! If someone wants to take the lead on this, we could pair up a TL for help provide access.

**Comment by lumjjb** [comment]
Still relevant! Commenting to remove stale tag!

**Comment by dutchshark** [comment]
I would say very good idea (I hate the noisy CNCF ical subscription).

**Comment by amye** [comment]
(3) option: We have a Tockify link on http://calendar.cncf.io/, use that? That's just the calendar invite for TAG Security, not all of the CNCF calendar.

**Comment by lumjjb** [comment]
Pinning this issue, this is going to be a great QOL feature

**Comment by lumjjb** [comment]
@savitharaghunathan I think it wouldn't be too far-fetched to maintain our own copy of the calendar, since most of our meetings are recurring. Would you be able to create one as a sample - and we can figure out permissions. Is this something that you'd be willing to help out with?

**Comment by lumjjb** [comment]
First try: https://calendar.google.com/calendar/u/0?cid=MGI4dTVlbDh0YTRzOTN0MmNtNzJ0dXZoaGtAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by PushkarJ** [comment]
Closing as #951 is merged! @savitharaghunathan feel free to reopen if you have suggestions to make it better or if the proposed update does not suffice :)
