### ISSUE TITLE
Formalize Cloud Native Security Con with the repo

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/tag-security#824]
Description: We need a PR in the repo (maybe under an Events folder) that covers Cloud Native Security Con information from the perspective of the STAG running/coordinating it and defining specific roles and expectations.  
Potentially update and move: https://github.com/cncf/tag-security/blob/main/cloud_native_security.md

Impact: Reduce tribal knowledge loss as folks move on.

Scope: Talk to previous Cloud Native Security Day and Cloud Native Security Con co-chairs, program committee, CTF committee, etc. to capture how event planning was previously done.

CC: @danpopnyc @anvega @lumjjb

**Comment by lumjjb** [comment]
Some of this is now documented in https://github.com/cncf/tag-security/blob/main/cloud_native_security.md

However, still requires tribal knowledge preservation to be documented. @danpopnyc @anvega @lumjjb

**Comment by szh** [comment]
It seems from the discussions we've had at meetings that now that CloudNativeSecurityCon is being spun out as it's own event, the LF is taking more control over the planning. I wonder if in that case the way we planned in the past is less important to record. Perhaps this should be closed?

**Comment by anvega** [comment]
The "run of the event" is centralized by LF Events who work with the designated project lead from the TAG on point for events, which the program committee also gets access to.
