### ISSUE TITLE
[Proposal] "landing page" for new visitors

### ISSUE THREAD

**Issue by jlk** [cncf/tag-security#826]
Description: Currently if someone browses to the [TAG GH page](https://github.com/cncf/tag-security/), it's sort of a confusing thing. The top-level readme talks about meetings, membership, leadership, objective, and vision...but not really what we do. I guess there's an "ongoing projects" section, but it sorta gets lost in the noise...

e.g. there's no list of how we can help projects, how we engage with the community, what our topics of interest are, etc.

An idea of what might be useful to people, either on the main README or a link off to an About Us type page:

* Current research topics (supply chain, serverless, etc)
* Ways in which we can help CNCF projects (templates, security pals, bad jokes...)
* Recent whitepapers
* Upcoming events

Impact: This would provide members of other CNCF projects an idea of what topics the TAG can help them with.

Scope: Initial scope is manageable - either add a section to the README or link to a separate markdown page. Tricky part is ongoing maintenance, as topics/interests/needs change over time.

I'm not sure this needs the formal Proposal todos/signoff, but leaving below, for now. More looking for a discussion here or maybe on future TAG call.

TO DO
- [ ] Security TAG Leadership Representative:
- [ ] Project leader(s):
- [ ] Project Members:
- [ ] Scope 
- [ ] Deliverable(s)

**Comment by lumjjb** [comment]
+ @ragashreeshekar who is looking into community manager type role for the TAG, which could be relevant to helping to maintain some of these

**Comment by ragashreemc** [comment]
Thanks for raising this to us. 
This issue is addressed in https://github.com/cncf/tag-security/issues/1026 as well as our open issues hence closing it. 
Please feel free to reopen if you think otherwise.

**Comment by ragashreeshekar** [comment]
Thanks for raising this to us.
This issue is addressed in https://github.com/cncf/tag-security/issues/1026 as well as our open issues hence closing it.
Please feel free to reopen if you think otherwise.
