### ISSUE TITLE
[CNSWP v2] Landing page for all relevant TAG material

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#827]
**Description**: Create a publicly accessible page which references all the whitepapers and relevant supplementary TAG material:
    - #737 
    - #510  
    - #564  
    - #635 
    - #546  
    - #679
    - #606 
    - #471 

(Please suggest anything we missed)

**Impact**: This will allow us to decouple new relevant material from the whitepaper versioning lifecycle by just adding the link to this page in the published version of the paper. 

**Scope**: Following tasks need to be completed:
- [ ] Create a PR to add a `related-material.md` here: https://github.com/cncf/tag-security/tree/main/security-whitepaper
- [ ] Add a quick blurb about each of the linked reference material with a link to where the material exists. Any in-progress material can be skipped.
- [ ] Mirror the content of this markdown page in the whitepaper v2 (@PushkarJ to add the link to v2 paper when it is available)

**Additional info**:
In scope of #747

**Comment by captainarcher** [comment]
@PushkarJ I am volunteering to be the owner for this

**Comment by sayantani11** [comment]
hey @PushkarJ 
Is this issue open?

**Comment by lumjjb** [comment]
Hi Sayantani, We have a microsite issue related to this that will be a
priority for the tag, would this be something you'd be interested in? We
can chat more to share a bit about what ideas have been going around
several issues

**Comment by PushkarJ** [comment]
@sayantani11: This is the issue that @lumjjb mentioned: https://github.com/cncf/tag-security/issues/110 This is significantly more effort though but would be of incredible value to the group!

**Comment by sayantani11** [comment]
@lumjjb I would love to know more!!! Let me know when you'll be free to do so
@PushkarJ Let me see if I can add something to it!!

**Comment by PushkarJ** [comment]
This will be removed from scope of #747 in favor or adding it in scope of #110
