### ISSUE TITLE
[CNSWP v2] Add new content on ransomware threats and mitigations

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#828]
Description: Current version of whitepaper is missing content on how ransomware threats affects cloud native ecosystem and projects. Any corresponding mitigations real world or recommended are also missing. 

Impact: Adding this content, with recent high visibility into ransomware threats and known attacks, will make the CNSWP v2 richer than its predecessor. 

Scope: Following tasks are involved:
- [x] Identify the section where ransomware content should be added or if it should be a dedicated section of its own
- [x] Define a general skeleton and scope of what content needs to be added
- [x] Create a rough draft of this content and get it reviewed in future CNSWP meetings or via slack channel 

Additional info:
In scope of #747

**Comment by joelerbork** [comment]
I will be working on this.

**Comment by PushkarJ** [comment]
Thank you Joel!!

**Comment by PushkarJ** [comment]
Section has been added. So closing as no pending action exists
