### ISSUE TITLE
[CNSWP v2] Add new content related to Threat Matrix for Containers

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#829]
Description: Threat matrix for containers did not exist when CNSWP v1 was published. With its publication, it makes sense to understand and evaluate how we include this matrix in the CNSWP v2

Impact: This will allow folks coming to the CNSWP v2 after having read the threat matrix to get a better footing on the content described in the paper. In the same vein, folks who have not come across threat matrix for containers will get introduced to it while reading the CNSWP v2 

Scope: Following tasks are involved:
- [ ] Read and Understand the Threat matrix for containers: https://medium.com/mitre-engenuity/att-ck-for-containers-now-available-4c2359654bf1
- [ ] Compare this with the CNSWP v1 and find the intersection and complementary aspects between the two
- [ ] Identify sections where the threat matrix content being referenced would make sense
- [ ] Create a rough draft with edits and get it reviewed in future CNSWP meetings and/or slack channel : #tag-security-whitepaper 

Additional info:

In scope of #747 . Previously discussed in #513

**Comment by sayantani11** [comment]
Would like to help with this issue!!!

**Comment by PushkarJ** [comment]
New content was added so closing this now
