### ISSUE TITLE
[CNSWP v2] Revisit references / citations

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#830]
Description: Revisit references in the whitepaper v1 and add / edit them as needed

Impact: This will ensure we are referencing to the latest content outside of TAG's scope and allows us an opportunity to fix any broken links and add new references based on the new content added

Scope: Following tasks are involved:
- [x] Copy references from v1 to a google doc / hackmd doc
- [ ] Fix any broken links 
- [ ] Evaluate the scope of v2 and add / remove any links that make sense
- [ ] Look for new material published after v1 (Nov 2020) and evaluate adding them as a reference. e.g. https://us-cert.cisa.gov/ncas/current-activity/2021/08/02/cisa-and-nsa-release-kubernetes-hardening-guidance

Additional info:

In scope #747

**Comment by savitharaghunathan** [comment]
I can take this one

**Comment by PushkarJ** [comment]
References, Citations were added to v2. Thanks @savitharaghunathan for excellent work here!
