### ISSUE TITLE
[CNSWP v2] Add new content about securing financial institutions in EU

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#831]
**Description**: Add new content about things to consider when securing cloud native environment in a strictly regulated financial institution in European Union

**Impact**: This was missing in the v1 and adding this will give visibility and build awareness into this very important but niche user story / scenario for cloud native security

**Scope**: Mateusz Pruchniak has already written this blurb: https://docs.google.com/document/d/1uXaaL2noW3FAo-tnJSMVN9YGYWrX--s8eSjz0bZx86A/edit?usp=sharing . Next would be to review this in future whitepaper meetings and/or slack channel: #tag-security-whitepaper and identify where this content can land in the paper

Additional info:
In scope of #747

**Comment by mateuszpruchniak** [comment]
Please assign me to this issue.

**Comment by captainarcher** [comment]
I'm happy to help with this as well
