### ISSUE TITLE
[CNSWP v2] Apply feedback from Retrospective + Micro-survey

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#832]
Description: We did a retrospective on the whitepaper and found some really great ideas on how to improve. The v2 whitepaper should reflect these improvements

Impact: Gives a clear signal to readers that we listen to their feedback and improve our deliverables by letting them shape what we deliver

Scope: Following tasks are involved:

- [x] Add a link to a permanent survey or page  (could be a github issue) where readers can leave their feedback
- [x] Add a section talking about retrospective, survey, micro-survey and its results
- [x] Add relevant content like #734 as a link or built-in section in the paper

Additional info:
#734 #480 #753 are related to this content. Overall in scope of #747

**Comment by devadvocado** [comment]
@PushkarJ happy to take ownership for this issue

**Comment by PushkarJ** [comment]
Thanks @devadvocado 

I need to do some work on https://github.com/cncf/tag-security/issues/734. But you can start working on other items. I tagged you in the google doc for a placeholder location where we can add details.

**Comment by devadvocado** [comment]
Thanks @PushkarJ, I'll take a look on it this by EOW and start working on it.

**Comment by PushkarJ** [comment]
Closing as relevant updates are in place
