### ISSUE TITLE
[CNSWP v2] Verify and update references of SIG Security with Security TAG

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#833]
Description: #613 happened after v1 was published. So v1 needs an update to refer us as Security TAG instead of CNCF SIG Security

Impact: To keep up to date with now established convention of referring CNCF level groups as TAGs

Scope: Find references of SIG Security and replace them with Security TAG 

Additional info:
In scope of #747

**Comment by captainarcher** [comment]
I am volunteering to be the owner for this

**Comment by PushkarJ** [comment]
@captainarcher I have not found a mention of SIG Security on the working google doc  but please do a review from your side too. If you don't find anything too, let's close this one out

**Comment by PushkarJ** [comment]
No references were found. So closing this
