### ISSUE TITLE
[CNSWP v2] NIST SSDF (Secure Software Development Framework) Draft Guide mapping

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#834]
**Description**: Create a high level loosely coupled mapping of NIST SSDF with CNSWP v2

**Impact**: Allows folks who find both the guides/papers relevant to get a better understanding of the intersections and complementary aspects of each of them.

**Scope**: Unclear, but would be ideal to get someone from NIST SSDF team to collaborate on this. 

Additional info:

In scope of #747 . Links to NIST SSDF: https://csrc.nist.gov/Projects/ssdf

**Comment by faisalrazzak** [comment]
I'm interested in Ownership of this piece.

**Comment by captainarcher** [comment]
I can help with this as well

**Comment by PushkarJ** [comment]
Just sent out an email to our NIST SSDF contact person, to see if we can directly collaborate with them on this.

**Comment by faisalrazzak** [comment]
Yes, that's good news. It can help us streamline the final output. Can you
CC: me on the communication please ?

Thanks,

Faisal

*E-MAIL CONFIDENTIALITY CLAUSE:*
This e-mail and the information contained in it is confidential, may be
privileged and is intended for the exclusive use of the addressee(s). Any
other person is strictly prohibited from using, disclosing, distributing or
reproducing it. If you have received this communication in error, please
reply by e-mail to the sender and delete or destroy all copies of this
message.
CLAUSE DE CONFIDENTIALITÉ POUR LES ENVOIS PAR COURRIEL
Le présent courriel et les renseignements qu'il contient sont
confidentiels, peuvent être protégés par le secret professionnel et sont à
l'usage exclusif du (des) destinataire(s) susmentionné(s). Toute autre
personne est par les présentes avisée qu'illui est strictement interdit
d'en faire l'utilisation, la diffusion, la distribution ou la reproduction.
Si cette transmission vous est arrivée par erreur, veuillez en aviser
immédiatement l'expéditeur par courriel, puis effacer ou détruire toutes
les copiesdu présent message.

**Comment by achetal01** [comment]
I am interested in contributing to this initiative. I think we can reference controls mentioned in SSDF and include the feedback we had provided for SSDF. But I m not sure we can do justice to SSDF in the Cloud Native white paper and will like to discuss that during the next meeting.

I think mapping Cloud Native controls to SSDF should be a separate Initiative in addition.
Happy to Discuss.
Thank you.

**Comment by faisalrazzak** [comment]
I'm thinking about 2 different ways of presenting this information. 

1) If we can put numbering to different sections of v1 of whitepaper & then in each section or sub-section point to SSDF v1.1 Practice and/or Task number, it could help us link both initiatives. 

2) Add an Appendix showing SSDF practice/Task mapping to CNCF Security Whitepaper mapping.

**Comment by PushkarJ** [comment]
I think the work in scope of NIST SSDF is completed with drafted content in appendix. We should continue this more under: https://github.com/cncf/tag-security/issues/845
