### ISSUE TITLE
[CNSWP v2] Add a new section for Supply Chain Security

### ISSUE THREAD

**Issue by PushkarJ** [cncf/tag-security#844]
Description: Add a new section describing at high level the why, what, how of supply chain security

Impact: While we have a dedicated resources for supply chain security here: https://github.com/cncf/tag-security/tree/main/supply-chain-security, for completeness sake it would really help to add a short summary of supply chain security

Scope: 

- Write quick blurb on why it is needed, with one example of supply chain attacks: https://github.com/cncf/tag-security/tree/main/supply-chain-security/compromises
- Write quick blurb on what / how to secure supply chains, citing from #679 
- Write any other additional info that might be useful for someone consuming a cloud native product as an end user, to verify security of supply chains 

Parent issue: #747 

@fkautz @mnm678 @pratiklotia have shown interest in this, so far

**Comment by pratiklotia** [comment]
I'd like to help on this, thanks.

**Comment by mateuszpruchniak** [comment]
I will be happy to help with that too.

**Comment by fkautz** [comment]
I've written some initial material for this available at:

https://hackmd.io/m_7BWODDQKCOfkoqPzXl1w

If you log into hack.md you can edit it. Comments are globally open for everyone as well.

**Comment by PushkarJ** [comment]
@mnm678 I am unable to do a look up your github handle to assign the issue to you. Can you please add a comment here? 

That has resolved this issue in the past.

**Comment by mnm678** [comment]
> @mnm678 I am unable to do a look up your github handle to assign the issue to you. Can you please add a comment here?
> 
> That has resolved this issue in the past.

Sure!

**Comment by mateuszpruchniak** [comment]
Hi Folks, I have an idea that maybe we should explicitly mention the supply chain of infrastructure as code and GitOps practice because it need to be secured and reliable as the software and it becomes very popular. I have added the last paragraph as a suggestion for what I think about. Please feel free to leave feedback or edit.

**Comment by fkautz** [comment]
That's a fantastic point, infra as code and gitops style approaches are very important for this space. The system must be automated and changes observable.

**Comment by fkautz** [comment]
@PushkarJ, I think we're approaching a point where this paragraph would make sense to include. The current co-authors are at the bottom of the hackmd doc for inclusion in the paper. Let us know what you need from us to progress. :)

**Comment by PushkarJ** [comment]
Awesome !!! Let's add the content in the working doc here: https://docs.google.com/document/d/1fftLBt3XjDzyYQisEKH3TZXL1QnT_cHIbBnFtW98UOs/edit# I will be happy to review it along with all the other additions once we have it in place :) If you don't have access to the doc, shoot me a DM on CNCF slack

**Comment by PushkarJ** [comment]
use this link with the bookmark that will take you to the supply chain security section: https://docs.google.com/document/d/1fftLBt3XjDzyYQisEKH3TZXL1QnT_cHIbBnFtW98UOs/edit#bookmark=id.319y80a

**Comment by fkautz** [comment]
I've cleaned up the prose a bit and added it as a suggestion.

**Comment by PushkarJ** [comment]
Thank you @fkautz . If either of you have not had a chance to contribute to that section, please update directly in the working google doc under the supply chain security section here: https://docs.google.com/document/d/1fftLBt3XjDzyYQisEKH3TZXL1QnT_cHIbBnFtW98UOs/edit#bookmark=id.qmih3evwedgl

**Comment by PushkarJ** [comment]
Thank you all for the contributions. Closing this now as #747 is now in public comment stage
