### ISSUE TITLE
[Suggestion] Clean-up 47 branches

### ISSUE THREAD

**Issue by dutchshark** [cncf/tag-security#860]
Description: tag-security maintains a very large list of branches of which 47 older then 2 months old and they all have been merged into the main branch.

Impact: 
- Removing of old now current branches the only one that make sense currently are: main. 

Perhaps also put in some style guide for 'different' branches - Purpose oriented branching (like: [chair-removal](https://github.com/cncf/tag-security/tree/chair-removal) are fine but this one has been merged already).

Scope: *delete* clicking 47 times, ~ 5 minutes?

**Comment by lumjjb** [comment]
Agreed! That's something good to do! I've cleared up the branches leaving the ones with open PRs.

**Comment by lumjjb** [comment]
wait i realized there are more branches that are not classified active or inactive. will have to go through them

**Comment by lumjjb** [comment]
@dutchshark would you like to open a PR into `governance/github.md` to add something there about PRs should be done by forked branches, or deleted after merged?

**Comment by dutchshark** [comment]
I consider this a housekeeper chore hence the way how I address it.
