### ISSUE TITLE
[Assessment] LitmusChaos

### ISSUE THREAD

**Issue by ashutosh-narkar** [cncf/tag-security#863]
Project Name: LitmusChaos

Github URL: https://github.com/litmuschaos/litmus

CNCF project stage and issue (NA if not applicable): NA

Self Assessments:  https://bit.ly/3nwADqp

Security Provider: No

- [ ] Identify team
   - [ ] Project security lead
   - [ ] Lead security reviewer
   - [ ] 1 or more additional reviewer(s)
   - [ ] Every reviewer has read [security reviewer guidelines](https://github.com/cncf/tag-security/blob/main/assessments/guide/security-reviewer.md) and stated declaration of conflict
   - [ ] Sign off by 2 chairs on reviewer conflicts
- [ ] Create slack channel (e.g. #sec-assess-projectname)
- [ ] Project lead provides draft document - see [outline](https://github.com/cncf/tag-security/blob/main/assessments/guide/joint-review.md)
- [ ] "Naive question phase" Lead Security Reviewer asks clarifying questions
- [ ] Assign issue to security reviewers
- [ ] Initial review
- [ ] Presentation & discussion
- [ ] Share draft findings with project
- [ ] Assessment summary and doc checked into /assessments/projects/project-name (require at least 1 co-chair approval)
- [ ] CNCF TOC presentation (if requested by TOC)

**Comment by ksatchit** [comment]
Thanks for creating this issue @ashutosh-narkar !

**Comment by JustinCappos** [comment]
I'm picking up stale items in the security assessment queue to try to push them forward. Apologies for the delay on your assessment!

@ksatchit  Is a self-assessment available? I don't see it in the repo, etc. Once this happens, we can get a team together to do an assessment. Once it reaches the front of our queue, this will require back and forth with your team.

If a security assessment isn't desired anymore, please let us know and this issue can be closed.

**Comment by JustinCappos** [comment]
Closed due to lack of response.
