### ISSUE TITLE
Update CNS Map with details from Whitepaper v2

### ISSUE THREAD

**Issue by ashutosh-narkar** [cncf/tag-security#869]
The CN Whitepaper is being updated and a newer version will be released soon. More info on that in [this](https://github.com/cncf/tag-security/issues/747) issue. Following that release we should update the CN Security Map with the relevant findings and updates from the paper.

**Comment by lumjjb** [comment]
@chadmcrowell this will a be a good starting project!!

**Comment by ashutosh-narkar** [comment]
This is achieved as part of https://github.com/cncf/tag-security/issues/737.
