### ISSUE TITLE
[Suggestion] update supply chain security doc with new PEAR issue

### ISSUE THREAD

**Issue by lirantal** [cncf/tag-security#882]
PHP's PEAR package manager found vulnerable: https://blog.sonarsource.com/php-supply-chain-attack-on-pear

**Comment by PushkarJ** [comment]
@lirantal is this covered one or more of the PRs you created recently? If not would it make sense to create a PR to include this as well?

**Comment by lirantal** [comment]
It's not included. I need to set some time to shoot a new PR to document this one :-)
