### ISSUE TITLE
[Suggestion] Provide guidance on starting a region-specific subgroup

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#886]
Description: What's your idea?

Impact: 

With the removal of APAC timezone meeting, recommend providing a way for folks interested in setting up a region specific meeting to do so with the leadership team so we can support them. 

https://github.com/cncf/tag-security/pull/883#pullrequestreview-930720144

Scope: Writing up a page in `governance/` to describe reaching out to the mailing list. Mention some requirements for meetings - i.e. TL representative at each meeting. Meeting facilitator, etc.

**Comment by sayantani11** [comment]
@lumjjb I can try helping with that!!

**Comment by lumjjb** [comment]
Awesome @sayantani11 ! Let me know if you have any questions!

**Comment by lumjjb** [comment]
@sayantani11 how is this going? Just checking in.

**Comment by sayantani11** [comment]
Hey Brandon!!!
Sorry I was a bit caught up with my academics 😓 I made plans about it,
will update as soon as possible... Sorry for the delay

**Comment by sayantani11** [comment]
@lumjjb I have come up with a few ideas for it!!

**Comment by sayantani11** [comment]
Under the `governance/` folder we can add a file:
1. That mentions how to reach out to the mailing list.
2. We can also have active contributors of different timezones as representatives of a specific region
3. We can have monthly meetings for every region, and the representatives can report things discuss.
I guess contributors can volunteer to be representatives. 
The documents should mention the name of the representatives, the meeting link and the particular day at which the meeting occurs every month. As per meeting facilitator, I guess that can be decided later🤔
Also we should also be able to confirm a particular number of attendees in the meeting, that will save us time.
let me know your thoughts🤗

**Comment by anvega** [comment]
From the discussion with @lumjjb, for those seeking guidance on bootstrapping and sustaining a regional meeting, there is a good model to follow by what @sublimino and the EMEA team have done. There is a pattern to replicate should there be interest in restarting an APAC meeting. I'd encourage checking with them and taking note of their guidance.
