### ISSUE TITLE
[Presentation] SECURITY-INSIGHTS

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#891]
Title: Security-insights project

Speakers: @luigigubello

Description:https://github.com/luigigubello/security-insights-spec

This specification provides a mechanism for projects to report information about their security in a machine-processable way. It is formatted as a YAML file to make it easy to read and edit directly by people. It is expected that a first draft of the file would be created by automated tools, "wizards" that guide users through the answers, and linter tools that help users to check the YAML file schema. The file is then put under version control, provided to potential users, and updated as needed. The file's contents may then be extracted for a variety of different reasons (e.g., extracted into security evaluations, etc.).

This is an early version created by the OpenSSF Identifying Security Threats Working Group.

Time: How long will the presentation take? (estimate)

15 minutes + questions

TO DO
- [x] TAG Representative @lumjjb 
- [x] Schedule date 2022/04/13
- [x] By opening this issue, I, @lumjjb acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by luigigubello** [comment]
Here is the public link to the presentation: https://pitch.com/v/openssf-security-insights-67a8mm

**Comment by lumjjb** [comment]
Thanks for the presentation @luigigubello !
