### ISSUE TITLE
[Suggestion] Curate persistent list of CNCF asks (which can be funded)

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#893]
Description: 

Suggested by @ultrasaurus , we should keep track of the different activities that we think the CNCF can help with - i.e. design, website, development, help with uploading youtube videos, etc.

Examples of this today are:
- Help with uploading youtube videos
- Help with website development for microsite

Impact: 

This will help provide a check-in with CNCF/TOC liaison so that we have a list of requests whenever they ask on suggestions of how CNCF can support

Scope: not yet determined

**Comment by amye** [comment]
These examples are all servicedesk tickets, usually.
Is there something more to this?

**Comment by lumjjb** [comment]
Yea - some of the motivations here are to keep track of things that are not possible, but that stance may chance in the future - e.g. new vendor, policy/direction change.

Came out of discussion around moving to the new social platform/streaming service, which initially was the direction of the group, but may have changed over time over from feedback. We want to capture some of the asks, that we may not have a straightforward yes/no answer for, so that they don't get lost in the future, especially if there are multiple similar asks

**Comment by ultrasaurus** [comment]
thanks for creating this issue @lumjjb -- great place to collect shared knowledge!

FYI -- on microsite development, we had someone assigned who even built a prototype site, but stalled on lacking volunteers who were willing to write/edit words!  (I added that note to the issue recently)

**Comment by amye** [comment]
Ah! Take a look at https://github.com/cncf/servicedesk, in that this applies to TAGs as well - and if there's certain things that we should add for TAGs that don't apply for Projects.

**Comment by lumjjb** [comment]
Ahh this looks useful! Thanks!

**Comment by anvega** [comment]
Closing this out as the CNCF service desk is the one stop for all requests.
