### ISSUE TITLE
[Presentation] IBOM

### ISSUE THREAD

**Issue by JonZeolla** [cncf/tag-security#897]
Title: IBOM

Speakers: @schosterbarak

Description: Infrastructure Bill of Materials

Time: 40 minutes

Availability: July 13, 1pm ET

TO DO
- [x] TAG Representative: @PushkarJ 
- [x] Schedule date: July 13
- [X] By opening this issue, I, (@JonZeolla) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by lumjjb** [comment]
On the schedule! Thanks @JonZeolla

**Comment by schosterbarak** [comment]
Hey @lumjjb @JonZeolla something came up. Can we reschedule for July?

**Comment by JonZeolla** [comment]
@schosterbarak yup, here are the July openings:
- July 8, 1pm ET
- July 13, 1pm ET
- July 20, 1pm ET
- July 27, 1pm ET

**Comment by JonZeolla** [comment]
Related: https://github.com/cncf/tag-security/issues/713 and https://github.com/cncf/tag-security/issues/895

**Comment by JonZeolla** [comment]
Going with July 13, 1pm ET

**Comment by lumjjb** [comment]
@schosterbarak just a reminder - can you post the slides here?

**Comment by JonZeolla** [comment]
@lumjjb good if we consider this closed now?
