### ISSUE TITLE
[Presentation] Introducing Kubewarden: a policy engine for Kubernetes

### ISSUE THREAD

**Issue by flavio** [cncf/tag-security#899]
Title: Introducing Kubewarden

Speakers: @flavio, @ereslibre

Description:
The presentation will be an introduction to [Kubewarden](https://kubewarden.io/). Kubewarden is a Kubernetes Dynamic Admission Controller that leverages WebAssembly to write policies.
The project has been submitted for CNCF sandbox consideration.

Time: How long will the presentation take? 40 minutes

Availability: we are flexible, we can accommodate your schedule

TO DO
- [x] TAG Representative @lumjjb 
- [x] Schedule date June 8
- [x] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by lumjjb** [comment]
Hi @flavio @ereslibre, would the June 8th meeting time be good for you?

**Comment by lumjjb** [comment]
@flavio can you check acknowledge the presentation guidelines? Thanks!

**Comment by flavio** [comment]
> @flavio can you check acknowledge the presentation guidelines? Thanks!

Done! :heavy_check_mark:

**Comment by lumjjb** [comment]
Awesome! All set!

**Comment by lumjjb** [comment]
presentation link: https://drive.google.com/file/d/1JeC0GsDHP0X5dnTjhZTAL_Ruc1y12PJt/view?usp=sharing

**Comment by flavio** [comment]
Link to the recording of the meeting: https://www.youtube.com/watch?v=K-8Nepk7Zyc

Thanks again for the slot! :heart: :pray:
