### ISSUE TITLE
[Presentation] Open Fine-Grained Authorization (OpenFGA)

### ISSUE THREAD

**Issue by aaguiarz** [cncf/tag-security#902]
Title: Open Fine-Grained Authorization (OpenFGA)

Speakers:  @aaguiarz, @jon-whit, @elbuo8

Description: Auth0 has been building a fine grained authorization service inspired by [Google Zanzibar](https://research.google/pubs/pub48190/), and it’s now available in preview at [https://fga.dev/](https://fga.dev). We plan a generally available version by early 2023.

We’ll be open sourcing it in a few weeks and we plan to apply to CNCF Sandbox. We’d like to get early feedback from the Security TAG about the project itself and the approach the OpenFGA team plans to use.

Time: 30 mins

Availability: We can adjust to your requirements. We can’t do it from June 20 to June 24. .

TO DO
- [x] TAG Representative: @lumjjb 
- [x] Schedule date: June 1
- [x] By opening this issue, I, @aaguiarz acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by aaguiarz** [comment]
Yes, let's do it!

**Comment by lumjjb** [comment]
got you scheduled!! can you check the acknowledgement box in the issue for speaker guidelines?
