### ISSUE TITLE
[Presentation] Confidential Containers

### ISSUE THREAD

**Issue by sameo** [cncf/tag-security#912]
Title: Introduction to Confidential Containers

Speakers: Samuel Ortiz @sameo and James Magowan @magowan

Description:
[Confidential Containers](https://github.com/confidential-containers/) aims at providing and integrating all the software components to orchestrate and run cloud native workloads on top of Confidential Computing hardware (e.g. AMD SEV, Intel TDX, etc). By doing so, the project fulfills one of the key Confidential Computing promise and remove Cloud Provides out of the workloads TCB.
Although one of the project's goal is to be able to seamlessly run Kubernetes pods in their own dedicated enclaves, its scope expands to the attestation, key brokering and secure software supply chain spaces. As the project goals, scope and challenges align well with the TAG Security charter, we'd like to present it to this group.

Time: 30-40 minutes

Availability: TBD, but we're on european timezones. The 10am PT meeting time should work for us.

TO DO
- [x] TAG Representative @lumjjb 
- [x] Schedule date: June 29th, July 20th (stretch 2 sessions!)
- [x] By opening this issue, we, @sameo and @magowan acknowledge that the presentation topic and speakers will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by sameo** [comment]
@lumjjb Can I please add you as the TAG representative?

**Comment by lumjjb** [comment]
Is June 29th ok for you?

**Comment by sameo** [comment]
> Is June 29th ok for you?

Yes, it should work. Thanks.

**Comment by magowan** [comment]
Yes works for me. 
Are we looking at 10am PT? (18:00 UK time)

**Comment by lumjjb** [comment]
Yep 10am pt! Awesome. Thanks!

**Comment by svenkata9** [comment]
Will the session be recorded? 10 a.m. Pacific is late for us in GAR/APAC.

**Comment by lumjjb** [comment]
Yes it will be recorded, we will be doing a part 2 due to many questions asked. How does July 20th work? @sameo @magowan ?

**Comment by sameo** [comment]
> Yes it will be recorded, we will be doing a part 2 due to many questions asked. How does July 20th work? @sameo @magowan ?

It is fine by me, thanks @lumjjb

**Comment by svenkata9** [comment]
> 

Thanks @lumjjb. Do you mean to say July 20 APAC time?

**Comment by magowan** [comment]
Yes July 20th works for me too, thanks

**Comment by lumjjb** [comment]
@svenkata9 unfortunately we don't have APAC timezone run meetings right now. We had tried them in the past but they have fizzled out. We are though planning to create an EU timezone meeting which should alleviate the horrible timezone difference.

The recordings are on youtube though https://www.youtube.com/watch?v=_yvtk3IU1o8

**Comment by svenkata9** [comment]
> @svenkata9 unfortunately we don't have APAC timezone run meetings right now. We had tried them in the past but they have fizzled out. We are though planning to create an EU timezone meeting which should alleviate the horrible timezone difference.
> 
> The recordings are on youtube though https://www.youtube.com/watch?v=_yvtk3IU1o8

Thanks @lumjjb. Yes, I believe EU timezone that will work out better for everyone.

**Comment by sudo-bmitch** [comment]
The link in the description should be updated to https://github.com/confidential-containers/

**Comment by lumjjb** [comment]
Updated, thanks @sudo-bmitch

**Comment by anvega** [comment]
The presentation already took place.
