### ISSUE TITLE
Use Cases for Interoperability 

### ISSUE THREAD

**Issue by knowlengr** [cncf/tag-security#92]
In the security and "management" (i.e., Ops Intel) landscape, consider the concern over how to encourage telemetry from one tool to pub/sub streams from other tools. Mostly, this is a traditional interoperability issue, but security orchestration and automation presents additional important (sometimes mandatory) and nice-to-have capabilities. 

Once these requirements are in place, a DevOps pipeline suggests some test assurance to verify that interop has not been compromised and will fail over as intended. 

This issue needs associated specific use cases.  A few sloppily stated use cases to kick off the process follow:

1. Log significant events to common logging sinks (e.g., Splunk)
2. Raise high (see model remarks) alerts to a common SIEM 
3. Ingest and respond to messages from standard attack intelligence streams (e.g., STIX) 
4. Allow for orchestration using OpenControl
5. Utilize a common framework like ATT&CK for representing threat
6. Use a domain model through which automated reasoning and aggregation can be performed and maintained 
7. "Forward" and "Backward" (or "top down" and "bottom up") propagation of configuration management messaging

**Comment by TheFoxAtWork** [comment]
@knowlengr checking in on this - is this issue a suggestion for updates to our usecases/personas section of the repo?

**Comment by lumjjb** [comment]
Closing from triage review
