### ISSUE TITLE
TL Onboarding - Raga

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#931]
## Transfer

* [ ] Transfer Logistics
  * [x] #tag-security-chairs-and-tech-leads channel - add new TL(s)
  * [x] tag-leadership mailing list - add new TL(s)
  * [x] add TL to chairs/leads meeting
  * [x] tag-security repo PR:
    * [ ] Update codeowners, github settings, README (TOC Liaisons and chairs
      have admin access, tech leads have push access). - PRs created https://github.com/cncf/tag-security/pull/933
    * [x] Link to official vote email list message in PR descriptions
    * [x] Add STAG milestone to track STAG rep for TL
  * [ ] PR CREATED- [TOC Repo update](https://github.com/cncf/toc/blob/main/tags/security.md) https://github.com/cncf/toc/pull/851
  * [x] Verify new TLs have zoom credentials
  * [x] Introduce new TL selection, in the next steering committee meeting slide
  * [x] YouTube Channel
    * [x] invite new TLs (if needed)
    * [x] give "managers" permission

## Announce

* [x] Announce the vote
  * [x] #tag-security slack message
  * [x] email message to the tag-security list
  * [x] Security TAG meeting Announcement for each region

**Comment by anvega** [comment]
Completed onboarding with a meeting to cover expectations and responsibilities on 6/21.
