### ISSUE TITLE
[Formatting] Misformatted section security-whitepaper/v2/cloud-native-security-whitepaper.md#secrets-encryption

### ISSUE THREAD

**Issue by marcindulak** [cncf/tag-security#938]
The "Secrets encryption" section appears misformatted https://github.com/cncf/tag-security/blob/7074a07ea79b894f611c553b5d6a52a77650ea27/security-whitepaper/v2/cloud-native-security-whitepaper.md#secrets-encryption. The "Encryption fully managed by the orchestrator" and "No encryption" items should not appear as list items, but be placed on the same level as "Encryption with an external KMS".

![Screenshot from 2022-06-15 18-48-26](https://user-images.githubusercontent.com/3178318/173882652-ca833d98-ccfa-4597-bec3-78472decf0d8.png)

**Comment by PushkarJ** [comment]
@marcindulak this is great feedback! Would you mind opening a PR to fix this?

**Comment by PushkarJ** [comment]
Thank you for fixing this with a PR @marcindulak
