### ISSUE TITLE
SecurityCon at KubeCon+CloudNativeCon NA 2022 

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#939]
Now that SecurityCon events for EU 2022 are wrap its time to prepare and plan for NA! This issue will track activities related to TAG Security events for upcoming year.

SecurityCon is designed to create a focus space to foster collaboration, discussion, and knowledge sharing of OSS Security. 

Program committee
The responsibilities of the program committee include but are not limited to:
* Active involvement in CFP review, scoring, and schedule building process
* PC Members should allocate 4-5 total hours to complete the CFP review during the review window
* Review of Diamond sponsor talk content + BoF proposals prior to approval
* (Where applicable) Support marketing efforts to drive registration
* Attend post-event debrief meeting

STAG Rep: @mnm678 @ragashreeshekar (/co-lead)
Program Committee Members: @sublimino @chasemp @kevinWard @denhamparry @mythi @pratiklotia @rowanBaker @szh @nadgowdas
CFP Reviewers: @sublimino @chasemp @kevinWard @denhamparry @mythi @pratiklotia @rowanBaker @szh @nadgowdas @ericsmalling

Logistics
Slack channel: #tag-security-events
Dates: 24, 25 October 2022
Location: Detroit, MI, USA

To Do
* 		Website: review past content and update as appropriate
* 		[] CFP prep: DONE
* 		[] CFP Review: DONE
* 		[] Security Day event schedule/planning: DONE
* 		[] "Day Of" Staff: @pratiklotia @nadgowdas @ericsmalling @mnm678  @ragashreeshekar 

Retrospective
To Do

**Comment by ragashreeshekar** [comment]
I'd like to join. CFP reviewer/Event organizing, especially interested to join and learn the CTF efforts, please count me in!

**Comment by szh** [comment]
I'd like to participate as well.

**Comment by mythi** [comment]
me too

**Comment by JustinCappos** [comment]
Do we respond to this email or is there a better way to express interest?

Justin

**Comment by nadgowdas** [comment]
I would like to participate as well

**Comment by chasemp** [comment]
Please count me in :)

**Comment by aks-secops** [comment]
I'd like to join.

**Comment by sublimino** [comment]
Additionally, I'll be on the CTF efforts along with a few CP folks

**Comment by pratiklotia** [comment]
+1 CTF

**Comment by mlieberman85** [comment]
@sublimino I can help out with CTF too

**Comment by slashben** [comment]
+ review panel 
+ CTF
:)

**Comment by szh** [comment]
I think this can probably be closed now.
