### ISSUE TITLE
Hexa Policy Orchestration overview

### ISSUE THREAD

**Issue by ggebel** [cncf/tag-security#941]
Title: Hexa Policy Orchestration overview (referred to Security TAG by TOC after sandbox review)

Speakers: Gerry Gebel/@ggebel and Mark Callahan/@MDCinMT

Description: Hexa Policy Orchestration seeks to make managing distributed identity and access across multiple clouds and across the stack consistent, secure and scalable. Hexa Policy Orchestration is open-source software that manages access policy for applications and data running on multiple clouds and across your tech stack. Hexa translates and orchestrates Identity Query Language (IDQL) policies into the native policies for your application, platform, data, and network systems to unify access policy management. 

IDQL is a new Policy Orchestration format that defines access control policies in a declarative way. IDQL policies are distributed and orchestrated, via Hexa, across heterogeneous systems at the application, platform, data, and network planes. Use IDQL to abstract policy from the underlying access control system; (e.g. AWS Identity, GCP BeyondCorp Identity, Snowflake, Versa Networks, F5 Networks Volterra, Nginx and others).

Time: 30 minutes for presentation, demo and Q&A

Availability: Any Security TAG meeting from June 29 onward, but preferably before the next TOC sandbox review on July 26

TO DO
- [x] TAG Representative: @ashutosh-narkar 
- [x] Schedule date: July 6
- [x] By opening this issue, I, @ggebel, acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by ashutosh-narkar** [comment]
@ggebel just confirming that y'all will be presenting tomorrow at the Security TAG meeting.

**Comment by ggebel** [comment]
@ashutosh-narkar confirmed, see you on the call

**Comment by ggebel** [comment]
Hi @dims  - In case you haven't seen it already, here is the recording of our presentation/demo/Q&A 

https://youtu.be/N3rYDZNvipo

**Comment by anvega** [comment]
Presentation took place already.
