### ISSUE TITLE
[Suggestion] Best Practices for Namespace

### ISSUE THREAD

**Issue by knowlengr** [cncf/tag-security#942]
Consideration of best or suggested practices for namespace management.

**Possible Impact** 
- Additional layer of control for zero trust inspection / enforcement 
- Improved granularity for telemetry / observability for cloud workloads 
- Connect namespace to broader metadata objectives, including designations for PII, confidential computing, cost, semantic dependencies within applications
- Resilience when namespace is an attack target

**Additional Research**
Possibly relevant references.  (Personal research is ongoing.)
- I. -M. Stan, D. Rosner and Ş. -D. Ciocîrlan, "Enforce a Global Security Policy for User Access to Clustered Container Systems via User Namespace Sharing," 2020 19th RoEduNet Conference: Networking in Education and Research (RoEduNet), 2020, pp. 1-6, doi: 10.1109/RoEduNet51892.2020.9324866.
- C. L. Abad, H. Luu, N. Roberts, K. Lee, Y. Lu and R. H. Campbell, "Metadata Traces and Workload Models for Evaluating Big Storage Systems," 2012 IEEE Fifth International Conference on Utility and Cloud Computing, 2012, pp. 125-132, doi: 10.1109/UCC.2012.27.
- I. -M. Stan, D. Rosner and Ş. -D. Ciocîrlan, "Enforce a Global Security Policy for User Access to Clustered Container Systems via User Namespace Sharing," 2020 19th RoEduNet Conference: Networking in Education and Research (RoEduNet), 2020, pp. 1-6, doi: 10.1109/RoEduNet51892.2020.9324866.
 
**Related** 
- [Share a Cluster with Namespaces](https://kubernetes.io/docs/tasks/administer-cluster/namespaces/): This page shows how to view, work in, and delete namespaces. The page also shows how to use Kubernetes namespaces to subdivide your cluster 
- [Kubernetes best practices: Organizing with Namespaces](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-organizing-with-namespaces) 
- [Kubernetes Namespaces Demystified - How To Make The Most of Them](https://cloud.redhat.com/blog/kubernetes-namespaces-demystified-how-to-make-the-most-of-them)
-  [Palo Alto Prisma Cloud Microsegmentation Administrator's Guide: Microsegmentation namespaces](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-microsegmentation/concepts/namespaces)
- [How to Design and Implement an Effective Container Micro-Segmentation Strategy with Kubernetes (Illumio)](https://www.illumio.com/blog/container-microsegmentation-strategy)
- [Tanzu Kubernetes Grid Workload Isolation using NSX-T Micro Segmentation](https://developer.vmware.com/docs/12173/tanzu-kubernetes-grid-workload-isolation-using-nsx-t-micro-segmentation)  
- [KubeSlice Overview](https://avesha.io/documentation/kubeslice-overview/)  
- [Micro-Segmentation with Istio Authorization](https://istio.io/latest/blog/2018/istio-authorization/) 
- [Google Cloud Workload Identity with Kubernetes and Terraform](https://www.cobalt.io/blog/google-cloud-workload-identity-with-kubernetes-and-terraform): A tutorial on improving your security posture with Google Kubernetes Engine workloads
- [Vault namespace API locking](https://www.vaultproject.io/docs/concepts/namespace-api-lock)
- [Cross-namespace communication in Kubernetes](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-organizing-with-namespaces)
- [Security namespaces in Azure](https://docs.microsoft.com/en-us/azure/devops/organizations/security/namespace-reference?view=azure-devops)
- [Namespace in Google Chronicle](https://cloud.google.com/chronicle/docs/investigation/asset-namespaces) 
- [Onboarding namespaces in Open Service Mesh](https://release-v0-11.docs.openservicemesh.io/docs/guides/app_onboarding/namespaces/)

**Comment by lumjjb** [comment]
Sorry a bit of a lag here, but i think a few things i mentioned during the call were [openshift projects](https://docs.openshift.com/online/pro/architecture/core_concepts/projects_and_users.html) that tried to implement more defined security boundaries around k8s. 

Also the Flux multitenancy proposal may be a good data point as well - not sure if this is the best link: https://github.com/fluxcd/flux2-multi-tenancy

**Comment by JimBugwadia** [comment]
Relatively new entry in the K8s docs that discusses various isolation levels from a multi-tenancy perspective:

https://kubernetes.io/docs/concepts/security/multi-tenancy/

**Comment by anvega** [comment]
Closing as this has been inactive for a few years. Please feel free to reopen if there is renewed interest in pursuing this.
