### ISSUE TITLE
Minor corrections to V2 of "CLOUD NATIVE SECURITY WHITEPAPER"

### ISSUE THREAD

**Issue by D-Squared70** [cncf/tag-security#946]
On Pg. 38 and 39 there's a subsection labelled "Containment, Eradicate & Recovery", which seems to be almost identical outside of the last paragraph. I recommend deleting one, so they're not duplicates.

Pg. 47 under "Finance" there are two decimals after the word "detection". Recommend removing the duplicate.

I hope this is useful. :smile:

**Comment by PushkarJ** [comment]
HI @D-Squared70 this is excellent feedback! Would you mind opening a PR to edit the relevant sections in the markdown file here: https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/cloud-native-security-whitepaper.md

**Comment by D-Squared70** [comment]
Happy to. It looks like someone has already removed the duplicate section from the first point (see screenshot), but I'll adjust the two decimals. 

![Screenshot 2022-06-28 at 4 39 35 pm](https://user-images.githubusercontent.com/48914889/176282995-7054d14d-2476-475d-81fb-68ca771bd925.png)

**Comment by lumjjb** [comment]
Hi just checking back here if there is already a PR opened that addressed this?

**Comment by D-Squared70** [comment]
https://github.com/cncf/tag-security/pull/952

Indeed there is :point_up: - Sorry for the delay. I thought I merged my changes into the main branch, but I suppose I missed a step.
