### ISSUE TITLE
[Security Review] cert-manager

### ISSUE THREAD

**Issue by jahrlin** [cncf/tag-security#949]
Project Name: cert-manager

Github URL: https://github.com/cert-manager/cert-manager

CNCF project stage and issue (NA if not applicable): sandbox, working towards incubation

Security Provider: yes

- [ ] Identify team
   - [ ] Project security lead
   - [ ] Lead security reviewer
   - [ ] 1 or more additional reviewer(s)
   - [ ] Every reviewer has read [security reviewer guidelines](https://github.com/cncf/tag-security/blob/main/assessments/guide/security-reviewer.md) and stated declaration of conflict
   - [ ] Sign off by 2 chairs on reviewer conflicts
- [ ] Create slack channel (e.g. #sec-assess-projectname)
- [ ] Project lead provides draft document - see [outline](https://github.com/cncf/tag-security/blob/main/assessments/guide/joint-review.md)
- [ ] "Naive question phase" Lead Security Reviewer asks clarifying questions
- [ ] Assign issue to security reviewers
- [ ] Initial review
- [ ] Presentation & discussion
- [ ] Share draft findings with project
- [ ] Assessment summary and doc checked into /assessments/projects/project-name (require at least 1 co-chair approval)
- [ ] CNCF TOC presentation (if requested by TOC)

**Comment by lumjjb** [comment]
Hi @jahrlin , can you link the TOC issue for the incubation - i believe there is one? Just to clarify that this is not currently blocking incubation - we have given a recommendation for incubation DD already. Is that right?

**Comment by jahrlin** [comment]
Hi @lumjjb

Here's the TOC issue for incubation: https://github.com/cncf/toc/pull/786

> Just to clarify that this is not currently blocking incubation 

That's great!

> we have given a recommendation for incubation DD already. Is that right?

Yes, that's correct. I think the recommendation is awaiting review by two others though? as per: https://docs.google.com/document/d/1HCh3Q4LR6LFq1yHX2JIdGjp9_n82L22aEQDCMwCV5M0/edit?disco=AAAAcQ4O9LM

**Comment by JustinCappos** [comment]
I'm picking up stale items in the security assessment queue to try to push them forward.  Apologies for the delay on your assessment!

Is an updated self-assessment available?  I don't see it in the repo, etc.  Once this happens, we can get a team together to do an assessment.  Once it reaches the front of our queue, this will require back and forth with your team.

If a security assessment isn't desired anymore, please let us know and this issue can be closed.

**Comment by JustinCappos** [comment]
Closed due to lack of response.
