### ISSUE TITLE
[Suggestion] CI: compile papers to PDF and commit the repository after each commit

### ISSUE THREAD

**Issue by Dentrax** [cncf/tag-security#958]
Description: After each commit and changes to papers, PDF should be automatically generated and pushed to repo

Impact:

I was reading the [CNCF_cloud-native-security-whitepaper-May2022-v2.pdf](https://raw.githubusercontent.com/cncf/tag-security/main/security-whitepaper/v2/CNCF_cloud-native-security-whitepaper-May2022-v2.pdf) and noticed some sections are wrong and does not sync'ed to latest `.md` file. For example:

![Screen Shot 2022-07-18 at 13 20 55](https://user-images.githubusercontent.com/16493751/179492006-da40d320-fb0b-4d15-9c34-633e76953941.png)

Notice `Deploy` section have wrong image. But this is fixed in the [main](https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/cloud-native-security-whitepaper.md#deploy-1). This is just one solid example of the concern, keeping time-window long between PDF and MD files may lead PDFs out-of-date.

Any changes to:
* security-whitepaper/v1/: cnswp-images/ or cloud-native-security-whitepaper.md
* security-whitepaper/v2/: cnswp-images/ or cloud-native-security-whitepaper.md
* supply-chain-security/secure-software-factory/: images/ or secure-software-factory.md
* supply-chain-security/supply-chain-security-paper/: sscsp-images/ or fig* or sscsp.md
* ...etc

... should trigger the CI action to generate the related PDF and commit & push in the pipeline.

Scope: CI/CD

**Comment by PushkarJ** [comment]
@Dentrax I agree in theory with the idea. Unfortunately, the PDF generation magic is handled by our excellent CNCF Design team who spend a lot of time and effort that needs manual work and limited automation. 

So for minor changes we will continue to follow the guidelines on updating the papers mentioned here: https://github.com/cncf/tag-security/tree/main/security-whitepaper#versioning-and-publishing
