### ISSUE TITLE
[Suggestion] Analysis of SSCP on SLSA

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#960]
**Description:** 

Understand the coverage of Secure Supply Chain Best Practices Paper (SSCP) in SLSA, and make recommendations on improvements to either SSCP or SLSA, or provide guidance on coverage of controls outside SLSA.

**Impact:** Understand gaps in today's tools in Software Supply Chain and provide recommendations to bolster supply chain security efforts.

**Scope:** Probably a month of analysis and discussion and another month of discussing and writing guidance, and a month of review and wrap-up.

TO DO
- [ ] Security TAG Leadership Representative:
- [ ] Project leader(s):
- [ ] Project Members:
- [ ] _Fill in addition TODO items here so the project team and community can see progress!_
- [ ] Scope 
- [ ] Deliverable(s)
- [ ] Project Schedule
- [ ] Slack Channel (as needed)
- [ ] Meeting Time & Day:
- [ ] Meeting Notes (link)
- [ ] Meeting Details (zoom or hangouts link)
- [ ] Retrospective

**Comment by mlieberman85** [comment]
There is the SLSA positioning working group/stream that is spinning up.

**Comment by mnm678** [comment]
I started a spreadsheet to map the SSCP to SLSA and other tooling to lay out which pieces of the supply chain are addressed by different pieces of tooling: https://docs.google.com/spreadsheets/d/1LfAgoYesySfg7bkiUgihNWGDpyKsMNt6xTBi303IAcg/edit?usp=sharing

Feedback and collaboration is welcome!

**Comment by PushkarJ** [comment]
@mnm678 anything else we can help with Marina? Shared this in the working session today with group, fyi.

**Comment by mnm678** [comment]
> @mnm678 anything else we can help with Marina? Shared this in the working session today with group, fyi.

Thanks! I opened #984 to extend the scope of this project a bit to cover not just SLSA, but other open source tools. If anyone would like to contribute to the spreadsheet based on knowledge of any supply chain security open source project, that would be very helpful!

**Comment by anvega** [comment]
Closing the issue due to inactivity. Task subsumed by Supply Chain WG.
