### ISSUE TITLE
Proposed additions to supply chain security compromises list

### ISSUE THREAD

**Issue by kurtseifried** [cncf/tag-security#961]
for https://github.com/cncf/tag-security/blob/main/supply-chain-security/compromises/README.md

pypi ctx: 
https://python-security.readthedocs.io/pypi-vuln/index-2022-05-24-ctx-domain-takeover.html
https://blog.sonatype.com/pypi-package-ctx-compromised-are-you-at-risk

left-pad:
https://www.theregister.com/2016/03/23/npm_left_pad_chaos/

**Comment by PushkarJ** [comment]
@kurtseifried : Would you mind opening a PR to add these to the list? Apologies if you already did and I missed it

**Comment by sublimino** [comment]
@kurtseifried any chance you have a moment to raise a PR or two here? No problem if not :pray:

**Comment by Caze121** [comment]
This seems to be publishing infrastructure, similar to SolarWinds, does that sound about right?

Comm100:
https://www.securityweek.com/supply-chain-attack-targets-customer-engagement-firm-comm100?utm_medium=email&utm_source=Eloqua&ref=GBSNewsletterEmail

**Comment by szh** [comment]
Ctx is also mentioned in #914

**Comment by tahirraza** [comment]
Don't seem like @kurtseifried seeing your response.

**Comment by anvega** [comment]
Please file these as a PR if missing from the catalog.
