### ISSUE TITLE
[Presentation] Introducing Kubescape project to TAG Security 

### ISSUE THREAD

**Issue by slashben** [cncf/tag-security#962]
Title: Introducing Kubescape project to TAG Security 

Speakers: Ben Hirschberg (@slashben)

Description: We are the Kubescape project (https://github.com/armosec/kubescape). We want to become part of the CNCF familiy and contribute the project to CNCF. We have applied for sandboxing and we are looking to build close cooperation with TAG Security. In this presentation we would like to introduce the project to the audience, showing its philosophy, current status, roadmap and demo.

Time: 20-30 minutes

Availability: all wednesdays are working in August except the first (8/3/2022)

TO DO
- [x] TAG Representative @lumjjb 
- [x] Schedule date 24 Aug
- [x] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by lumjjb** [comment]
Hi @slashben How does 24 august work for you?

**Comment by slashben** [comment]
> Hi @slashben How does 24 august work for you?

Sounds good!

**Comment by lumjjb** [comment]
all set! looking forward to the presentation this week!

**Comment by slashben** [comment]
Here is the link to the project: https://github.com/kubescape/kubescape
Here are the presentation slides: https://docs.google.com/presentation/d/1QvCD2XLB03OWdCuVCnXHmn_fkHyz95HowiHMljtKHb8/edit?usp=sharing

**Comment by lumjjb** [comment]
Awesome - thanks for the presentation!
