### ISSUE TITLE
[Presentation] Trousseau - Kubernetes KMS Provider Plugin

### ISSUE THREAD

**Issue by romdalf** [cncf/tag-security#963]
Title: [Trousseau](https://github.com/ondat/trousseau) - Kubernetes KMS Provider Plugin

Speakers: @romdalf

Description: 
Following the Sandbox Inclusion Meeting feedback, we would like to share with you an overview of why, what, and how Trousseau addresses the Kubernetes Secret Management the native way.
The session will be a walkthrough demo about the design, current status, roadmap and getting the TAG Security advice to nurture the Trousseau project. 

Time: 45min including QA

Availability: 08/16, 08/24 or 09/01 @ 10AM PDT/UTC-7 

TO DO
- [x] TAG Representative @PushkarJ 
- [ ] Schedule date
- [x] By opening this issue, I, @romdalf acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by PushkarJ** [comment]
Hi @romdalf would 09/07 work for you?

**Comment by romdalf** [comment]
Perfect day. Will put that in our agenda. Thanks @PushkarJ

**Comment by romdalf** [comment]
@PushkarJ We will not be able to present due to an unforeseen change of schedule - last minute recording of our Open Source Summit 20222 sessions due to travel conflict. 
Thank you for your understanding.

**Comment by anvega** [comment]
Closing this issue as it has been inactive for over 6 months. If there is renewed interest in presenting Trousseau to TAG Security, please express so again in the slack channel or by commenting on this issue, and we will work on getting it on the schedule once again.
