### ISSUE TITLE
[Proposal] Tighten collaboration between CNCF TAG-Security and OpenSSF

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#969]
Description: There is a lot of overlap in terms of the goals of CNCF TAG-Security and OpenSSF. This results in quite a few overlapping deliverables and member participation. The goal of this issue is to figure out a way to consolidate efforts when appropriate.

Impact: This will help result in deduplication of efforts between groups and concentrate efforts to produce deliverables more quickly and of higher quality. It will also provide a way for members of the community interested in participating in both communities a way to engage cohesively.

Scope: 

Initial meeting between OpenSSF and CNCF TAG-Security representatives to explore ideas and based on that, document outcomes in the related groups section of the repo and create several issues to execute decisions.

Ideas for doing this include, but not limited to:

- Cross-listing CNCF supply chain wg on the OpenSSF calendar
- Having bi-weekly/monthly CNCF/OpenSSF joint working groups
- Have deliverables based in both groups and establish attribution between the two groups

TO DO
- [x] Security TAG Leadership Representative: @lumjjb 
- [ ] Project leader(s):
- [ ] Project Members:
- [ ] _Fill in addition TODO items here so the project team and community can see progress!_
- [ ] Scope 
- [ ] Deliverable(s)
- [ ] Project Schedule
- [ ] Slack Channel (as needed)
- [ ] Meeting Time & Day:
- [ ] Meeting Notes (link)
- [ ] Meeting Details (zoom or hangouts link)
- [ ] Retrospective

**Comment by TheFoxAtWork** [comment]
Related: https://github.com/cncf/toc/issues/889

**Comment by mkbhanda** [comment]
In this context   Mikko Yilen (Intel) is reaching out to CRob (OSSF/Intel) to jump start this effort. Shall update.

**Comment by mkbhanda** [comment]
They did chat, but other priorities on Mikko plate, in particular Confidential containers V0.1 and V0.2. Thank you for checking.

**Comment by anvega** [comment]
From discussion with @lumjjb, we have several individuals in the TAG leadership who are active participants in the OpenSSF and regular attendees of the different meetings, and their is a fluid communication between the two different organizations. 

Worth noting collaboration and knowledge exchange are part of the TAGs charter. Will be closing this issue as this is part of the role description by the TAG chairs and leads.
