### ISSUE TITLE
[Proposal] Resources for reviewers in security assessment working group

### ISSUE THREAD

**Issue by ragashreeshekar** [cncf/tag-security#983]
Description: 
Build resources to supplement up-and-coming reviewers in the security assessment working group. P.S: Thanks to @achetal01 for the idea

Impact: 
We have fantastic resources for the end-to-end process of both self-assessment and joint review (Ref: https://github.com/cncf/tag-security/tree/main/assessments/guide). 

However, it seems there are not enough resources currently to guide the security reviewer on what aspects to be reviewed in this process. It is up to the reviewer's discretion and the skill set they possess that drive the direction of the assessment. Providing a checklist of the key aspects to verify, and the methodology to do so, will not only enable a consistent review process but also reduce the amount of time to complete the review, ultimately benefitting both the reviewers and the projects. 

Scope: Not yet determined

TO DO
- [ ] Security TAG Leadership Representative:
- [ ] Project leader(s):
- [ ] Project Members:
- [ ] _Fill in additional TODO items here so the project team and community can see progress!_
- [ ] Scope 
- [ ] Deliverable(s)
- [ ] Project Schedule
- [ ] Slack Channel (as needed)
- [ ] Meeting Time & Day:
- [ ] Meeting Notes (link)
- [ ] Meeting Details (zoom or hangouts link)
- [ ] Retrospective

**Comment by lumjjb** [comment]
I think @IAXES @JustinCappos may be able to chime in on some background here! There are also quite a few new members in the EMEA meeting that are interested that may be interested to collaborate - i can bring it up in the next EMEA meeting.

**Comment by JustinCappos** [comment]
I've been out of the loop for a few years, but I seem to recall we have a template and a list of steps, etc.  Can you be clearer about where there are gaps that need to be filled?

**Comment by sublimino** [comment]
> However, it seems there are not enough resources currently to guide the security reviewer on what aspects to be reviewed in this process.

@ragashreeshekar we've made some progress on a set of lightweight threat modelling questions in https://github.com/cncf/tag-security/issues/903 that might play into this too

**Comment by ragashreeshekar** [comment]
@JustinCappos, we definitely have great resources on the process flow of reviews - both self-assessments, and joint-review, as well as templates to assist the project teams. I was looking more from the security reviewer point of view, as to what we need to review in the project. Currently, this section is the only guideline I see for the reviewer - https://github.com/cncf/tag-security/tree/main/assessments/guide#clarifying-questions-phase. I was looking to find/build resources based on our community expertise as well as prior experience in reviewing other projects. Hope this clarifies.

Thank you for sharing this @sublimino. I was looking for something on these lines, and that's the reason I shared in the our call as well. It's great that we are already working on this. I'll be happy to collaborate.

**Comment by anvega** [comment]
Historically we've required reviewers to have shadowed experienced reviewers in a prior assessment as a form of apprenticeship before they can participate in full capacity as a part of a review or to have been part of a project team that has been reviewed. Even now that there is a book, there is a big component of learning by listening in.

**Comment by JustinCappos** [comment]
This seems closed now that the book #999  exists...
