### ISSUE TITLE
[Presentation] Constellation - Confidential Kubernetes

### ISSUE THREAD

**Issue by m1ghtym0** [cncf/tag-security#985]
Title: [Constellation](https://github.com/edgelesssys/constellation) - Confidential Kubernetes

Speakers: @m1ghtym0

Description: We've recently released the first Confidential Kubernetes platform called [Constellation](https://github.com/edgelesssys/constellation).

We use the term Confidential Kubernetes to refer to the concept of using confidential-computing technology to shield entire Kubernetes clusters from the infrastructure. The three defining properties of this concept are:
* Workload shielding: the confidentiality and integrity of all workload-related data and code are enforced.
* Control plane shielding: the confidentiality and integrity of the cluster's control plane, state, and workload configuration are enforced.
* Attestation and verifiability: the two properties above can be verified remotely based on hardware-rooted cryptographic certificates.

From a security perspective, Constellation is designed to keep all data always encrypted and to prevent any access from the underlying (cloud) infrastructure. This includes access from datacenter employees, privileged cloud admins, and attackers coming through the infrastructure. Such attackers could be malicious co-tenants escalating their privileges or hackers who managed to compromise a cloud server.

I would like to share the knowledge about the idea of Confidential Kubernetes with the CNCF and Kubernetes security community to spark discussions and retrieve feedback on the concepts and implementation.
@ragashreeshekar pointed me here and I would be happy to take the opportunity.
Please let me know what you think:-)

Time: 30 min including QA

Availability: 10/12 @ 1pm BST , 10/19 @ 10am PDT, 11/02 @ 10am PDT

TO DO
- [ ] TAG Representative
- [ ] Schedule date
- [ ] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by lumjjb** [comment]
This is a pretty cool project related to the confidential containers project @sameo ++. 

You would mind sharing some of the open source plans the project has (e.g. are you thinking about joining CNCF, license changes, etc.)

**Comment by m1ghtym0** [comment]
Thanks! It's related to confidential containers but with a slightly different approach on how it applies CC to Kubernetes.
Confidential Containers => On a Pod-level
Constellation => On a Node-level

Regarding your questions:
Currently, we are not planning to join the CNCF with that project or change the licenses.
We are very much interested to integrate with CNCF projects and find synergies to progress the integration of confidential computing and the cloud-native world. We definitely don't want to reinvent the wheel and use as much of the existing stack as possible. CC brings its own features and capabilities that could be beneficial even on a higher level than currently applied in Constellation. Thinking about workloads attestation, source of identity, key release/management, etc.
Would love to spark discussions and hear where people see potential and fit.

**Comment by lumjjb** [comment]
Ahh thanks for the context @m1ghtym0 , and @ragashreeshekar had filled me in with more information as well! As project presentations are more for CNCF projects (or projects aiming to be part of the CNCF), we can't have a dedicated presentation slot for you. However, if there is enough discussion around the issue on discussing the issue of confidential container implementations, then we can schedule some time on the agenda to talk about the broader problem. Based on the last sessions with confidential-containers, there was a lot of interest... 

We will leave this issue open for comment and see where it goes!

**Comment by m1ghtym0** [comment]
Alright, thanks @lumjjb for the update!
Looking forward to some comments on the concept:-)

**Comment by anvega** [comment]
Presentation already took place.
