### ISSUE TITLE
Supply chains security Expectations vs Reality

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#987]
Description: We ask for supply chain best practices, SLSA, SBOMs, all that information.. so as to ask the question - does my software have a secure supply chain? But is that question just a pipe dream? Or can we break it down to tangible questions that we can tackle.

Impact: Being able to provide direction on what policies we want to create will help inform the data we need to produce and inform the models of attestation in the supply chain ecosystems.

Scope: Probably a month's work collecting ideas and writing them down.

Working Doc: https://docs.google.com/document/d/1_7ZDL1TtFEA4dfR3oaaVRLoWNcqthNN5h-G84y4ITkA/edit

Additional info:
- Reference to supporting material
- Links to related site
- Feel free to delete this section if you don't have more info

**Comment by JustinCappos** [comment]
Happy to contribute here.

**Comment by Caze121** [comment]
Happy to contribute here as well.  We are currently doing this for our organisation as with capability milestones and deliverables along the secure supply chain best practices path.

**Comment by PushkarJ** [comment]
+1

**Comment by mlieberman85** [comment]
+1

**Comment by spiffcs** [comment]
Happy to contribute for when we find a leader or organizer for this

**Comment by nadgowdas** [comment]
+1

**Comment by jkjell** [comment]
I'd be glad to try and organize efforts around this. I've worked with quite a few folks in the thread in the Supply Chain Security working group.

**Comment by aks-secops** [comment]
I would like to contribute here.

**Comment by jkjell** [comment]
## Project Schedule
| TODO | Milestone | Estimated time | Actual date
| -- | -- | -- |--|
|  | Audience, Goals, & broad scope | 1 week | 
|  | Brainstorming & Refining Scope - Table Of Contents | 2 weeks | 
|  | Tasking Assignment | 1 week |
|  | Content Rough-in | 2-3 weeks | 
|  | Collaborative Review | 2 weeks | 
|  | Executive Summary and content wrap up | 2 weeks | 
|  | Narrative Voice | 1-2 weeks | 
|  | Final Group Review | 1 week | 
|  | Community Review / Public comment adjudication  | 2-3 weeks | 
|  | CNCF publishing engagement | ~2-3 weeks | 
|  | Addition to the repo | 1 week | 
| | Blog post and publishing coordination | 2-3 weeks |

**Comment by jkjell** [comment]
Hello all,

  On Thursday, February 16th, we're going to kick off the work for this issue during the CNCF TAG Security - Supply Chain WG meeting (11 am Eastern).  The first step will be deciding on the Audience, Goals, & Broad scope.  Then we will focus in on establishing the outline before distributing and working through the content sections.  

If you have any questions, feel free to comment on the issue, or reach out in the CNCF Slack [#tag-security-supply-chain-wg](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud-native.slack.com%2Farchives%2FC01KL0B4LKC&data=05%7C01%7Ckjelljo%40vmware.com%7C28a9c3fb505647daf7a708db0ddb9e54%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638119009147781163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gOaV8cMz8Y0dyozpifcFI8vuBXMoMTakDahtLOfOlfY%3D&reserved=0) channel.

I hope you can join us! 

[https://github.com/cncf/tag-security/issues/987](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcncf%2Ftag-security%2Fissues%2F987&data=05%7C01%7Ckjelljo%40vmware.com%7C28a9c3fb505647daf7a708db0ddb9e54%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638119009147781163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XykhiwWGbVXzewb6lfVk1%2BtwRRIkji%2FtCciMVjPLA1s%3D&reserved=0)

Also sent to [TAG Security email list](https://lists.cncf.io/g/cncf-tag-security/message/115).

**Comment by faisalrazzak** [comment]
+1

**Comment by yuji-watanabe-jp** [comment]
I would like to contribute to this topic.

**Comment by achetal01** [comment]
Will like to join this initiative, interesting work

**Comment by anvega** [comment]
This is tracked by the Supply Chain WG as regular business during their bi-weekly call. For status, see the WG meeting notes.
