### ISSUE TITLE
[Supply Chain Security incident] Sonar's PHP Packagist compromise

### ISSUE THREAD

**Issue by lirantal** [cncf/tag-security#988]
Add this to our incidents list: https://blog.sonarsource.com/securing-developer-tools-a-new-supply-chain-attack-on-php/

**Comment by anvega** [comment]
Thanks @lirantal. Please file the PR if this is still missing from the catalog directory.

**Comment by lirantal** [comment]
We have that one covered [here](https://github.com/cncf/tag-security/blob/main/supply-chain-security/compromises/2022/php-pear-compromise.md). Thank you @anvega 🙏🏼
