### ISSUE TITLE
[Presentation] Security prioritization based on Kubescape controls

### ISSUE THREAD

**Issue by slashben** [cncf/tag-security#996]
Title: Security prioritization based on Kubescape controls

Speakers: Ben Hirschberg @slashben 
Description: How to prioritize different potential security issues? Is a `privileged` container a security issue? Kubescape team has a new approach to tackle these questions. We implemented a category graph-driven approach to construct potential attack chains based on data from Kubernetes API and vulnerability scanning. This enables us to identify the most vulnerable workloads in the cluster. We would like to present this idea in TAG Security to get feedback on our results.

Time: 30 minutes

Availability: We can present from 16th of November and on

CC: @anvega 

TO DO
- [ ] TAG Representative
- [ ] Schedule date
- [ ] By opening this issue, I, (Insert Github Handle/Name) acknowledge that the presentation topic and speaker will follow the [presentation guidelines](https://github.com/cncf/tag-security/blob/main/governance/presentations.md)

**Comment by szh** [comment]
@slashben This sounds really interesting. Can you please suggest a couple of dates (Wednesdays) that would work for you and we can try and get this on the schedule?

**Comment by slashben** [comment]
16, 23 and 30 all good!

**Comment by szh** [comment]
> 16, 23 and 30 all good!

FWIW I can't do the 16th but don't hold it up because of me - I can watch the recording

**Comment by slashben** [comment]
> > 16, 23 and 30 all good!
> 
> FWIW I can't do the 16th but don't hold it up because of me - I can watch the recording.
> 
> @lumjjb mentioned he can be the TAG representative.

So is it 16?

**Comment by slashben** [comment]
@lumjjb , could we do this on the 23rd? This week is chaotic :(

**Comment by szh** [comment]
23rd meeting was cancelled to do US holidays. Probably too late for this week. How about next week, Dec.  7?

**Comment by slashben** [comment]
Should work. Confirmed?

**Comment by lumjjb** [comment]
sorry for the late response @slashben , slipped through the cracks... - what does your schedule like in the coming weeks?
