### ISSUE TITLE
[Suggestion] Should we write a Linux Foundation guide / course on how to do a security assessment?

### ISSUE THREAD

**Issue by JustinCappos** [cncf/tag-security#999]
Description: I think it could be helpful to outline our thoughts about how to do a security assessment in a form others can review.  This could also include what the assessments are and are not good for, how it differs from an audit, how to use a security assessment, and so on.

Impact: I think this could help us to train new security assessors and also help projects understand how to do a self assessment.  In general, it may be applicable to a wide range of domains and participants.

Scope: This amount of effort depends on the work product we want.  I would imagine a ~50 page book would not be too difficult.  We could also format it as a video, etc.  I'd love to have this be something where we get a lot of different security experts from our group to weigh in at points and share different perspectives.  I'm not sure the right format for that, but we would discuss with Tom Serewicz and his team to leverage their expertise.  

TO DO
- [ ] Security TAG Leadership Representative: @sublimino 
- [ ] Project leader(s): @JustinCappos @ragashreeshekar 
- [ ] Project Members:
- [ ] _Fill in addition TODO items here so the project team and community can see progress!_
- [ ] Scope 
- [ ] Deliverable(s): Security assessment runbook, accompanied by a possible training
- [ ] Project Schedule: First draft - Jan 2023; Estimated release - April 2023
- [ ] Slack Channel (as needed): TBD
- [ ] Meeting Time & Day: TBD
- [ ] Meeting Notes (link): TBD
- [ ] Meeting Details (zoom or hangouts link): TBD
- [ ] Retrospective

**Comment by PushkarJ** [comment]
+1 this was one of the feedback items, I received that for folks who want to get started how can they learn more about threat modeling. Such course would be exactly what the doctor ordered :)

**Comment by ragashreeshekar** [comment]
Absolutely!
In fact, @sublimino and I raised similar issues in the past to help with our security assessments, and this being the underlying gap will surely help formalise the process for us and for the community as well.

**Comment by sublimino** [comment]
Agreed, great call. It could be instructive to run a short retrospective with projects that have been through the process for an external consumer perspective.

**Comment by lumjjb** [comment]
Tagging this current open issue: https://github.com/cncf/tag-security/issues/983

Should we pick one and go with it so we don't duplicate?

**Comment by JustinCappos** [comment]
My sense is that #983 is a subset of what we're trying to do here.  So, I'd
prefer we keep #999.

I'd also like to encourage Raga to participate so she can help to ensure we
do fully close #983 with this effort.

**Comment by ragashreeshekar** [comment]
I'm interested to join hands with this effort.

**Comment by lumjjb** [comment]
Ok - let's weave #983 into this and since it looks like we have momentum of this now, let's try and flesh out a project plan and present it and get folks on board. @JustinCappos @ragashreeshekar maybe you can work together on a schedule and present it at the next TAG meeting - we should have an influx of new members from Kubecon!

**Comment by rowan-baker** [comment]
I'd be interested in helping this effort as well

**Comment by JonZeolla** [comment]
I'm interested in joining in here as well

**Comment by JustinCappos** [comment]
My plan is to add the initial content and framing in the next 2 months or so.  Then I will loop in others to give suggestions, add perspectives on how they think about different issues that arise, etc.  We would have a more regular schedule after this.

**Comment by callen-raft** [comment]
I would be interested in joining too!

**Comment by brandtkeller** [comment]
Interested in being involved. Training was identified as an action-item for cyber by multiple CISO's within regulated spaces. 

I understand this may or may not be directly applicable- but establishing training and process against cloud native projects will translate well to those who deploy/operate/validate environments leveraging those technologies.

**Comment by lumjjb** [comment]
It would be helpful to have the project have a timeline of events (see https://github.com/cncf/tag-security/issues/975), we've found success in projects that do this!

**Comment by szh** [comment]
I don't think I'm qualified to write much of this, but I can definitely review from a consumer perspective.

**Comment by JustinCappos** [comment]
We need to loop in tim@serewicz.com as well as he will handle from the LF side.

**Comment by JustinCappos** [comment]
> It would be helpful to have the proposal have a timeline of events (see #975), we've found success in projects that do this!

Timeline:

I'm expecting around Jan 1st, 2023 to have an initial draft.  I may or may not have text for all sections, but will at least have some of it down.  I will start soliciting feedback at this point.

Following this, those who are contributing extensive viewpoints / perspectives should have the structure they need to do so.  I would expect 5-10 hours of writing effort from them to draft their parts.  I would hope to get drafts of these within a 2-3 weeks of solicitation.

At this point, as a group we can assess what we are missing, what should be added, what needs work, etc. and figure out the next steps.  

My hope is to have a completed version we feel is ready to publish in March or April of 2023

**Comment by tahirraza** [comment]
I'd be interested to partner. We have been building our own little assessment playbook for 5 areas:
- source
- materials
- build-systems
- software factory
- runtime env

**Optional:** I would love to see is how the assessments can tie to various assurances driven by [SLSA](https://slsa.dev/spec/v0.1/levels) levels.

**Comment by JustinCappos** [comment]
@lumjjb Can you please add a discussion of this to the next meeting agenda?

@ragashreeshekar

**Comment by JustinCappos** [comment]
After a lot of work by myself and Raga, a first draft of the main content for the TAG Security Assessment Book is available.   The core idea was to write out effectively a complete rough draft of the book and then iterate in TAG-Security.  However, before we start to iterate, we wanted to discuss how to do this in a productive way moving forward.

My suggestions are that we do the following.

First, perhaps the biggest risk for this project going off the rails at this point is due to [bikeshedding](https://www.techtarget.com/whatis/definition/Parkinsons-law-of-triviality-bikeshedding).  We plan to try to avoid this by mostly soliciting high level feedback about serious omissions / problems.  We will avoid getting into minor wordsmithing discussions in committee.  I am volunteering to take the heat for ignoring feedback about wordsmithing issues.  So, please be kind to us and others and set your expectations that you will like 95% of the document (at most).

Second, we absolutely want polite-but-opinionated takes from experts in the community who have relevant expertise.  You can see many examples of this throughout the current draft.  While we may propose edits to suggestions from others a little bit for brevity / clarity / tone, we want the voices of the community to come out in appropriate places.  So, please give us your commentary in appropriate places so we can improve the book!
Third, for text suggestions in the main part of the book (not commentary from community experts), we will go over the content, style, etc. of proposed changes to make it more uniform with the rest of the text.  So feel free to propose a few paragraphs to be added to the draft, but do not be surprised (or offended) if the text added is re-written.

I plan to discuss this plan for iteration more in the upcoming meeting on January 18th and see if we have consensus there.  Please comment on this this github issue or attend that meeting if you have thoughts on this.

And, as was teased above, here is a link to [the draft itself](https://docs.google.com/document/d/1L6AAbzkVHkd2ODGv31Y-UJVKOjq2a0qxdZ5IIOQBcYo/edit?usp=sharing).

**Comment by sublimino** [comment]
From [today's call](https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/edit#heading=h.5i8257ju7gqn):

- We're looking for high level feedback on [the draft](https://docs.google.com/document/d/1L6AAbzkVHkd2ODGv31Y-UJVKOjq2a0qxdZ5IIOQBcYo/edit?usp=sharing): 
  - What’s missing? What’s too short/long? Substantial contributions/issues welcome, word-corrections not so much
  - Comments aren't open on the doc so please bring suggestions and issues via [slack](https://app.slack.com/client/T08PSQ7BQ/C04K8HKJN7Q)
- Anybody that would like to contribute opinions in the callout-style are welcome, potential “Experts disagree, here’s two perspectives”
- We'll convene a working group on EMEA time next week for interested parties to discuss contributions, and there's a CNSecCon Presentation in two weeks in Seattle (🦝 A Sneak Peak Into Security Reviews with the Community - Ragashree MC, Carnegie Mellon University, https://sched.co/1FUzs)

**Comment by aladewberry** [comment]
> Agreed, great call. It could be instructive to run a short retrospective with projects that have been through the process for an external consumer perspective.

https://kubernetes.slack.com/archives/C022K4F2W4W/p1667582978251009

^ link to the Kubernetes CAPI SElf Assessment retro I did with Pushkar and the rest of the team who did that self assessment!

**Comment by JustinCappos** [comment]
> > Agreed, great call. It could be instructive to run a short retrospective with projects that have been through the process for an external consumer perspective.
> 
> https://kubernetes.slack.com/archives/C022K4F2W4W/p1667582978251009
> 
> ^ link to the Kubernetes CAPI SElf Assessment retro I did with Pushkar and the rest of the team who did that self assessment!

Great idea!  I think this would be a great addition.  I added a note in the doc.  Would you be willing to draft copy so we can include your perspective?

We also should get 1-2 other projects to talk about it from their side too.  

I'm not sure how long these will need to be because I don't have a sense yet how duplicative they will be with the existing text and each other.  My intuition is 2-3 paragraphs is about right for this stage.

**Comment by anvega** [comment]
While I did find the word submarine mentioned once in the draft, it wasn't exactly what I had hoped for. I came here hoping to find @JustinCappos famed _selling a submarine to the government, torpedos, and threat modeling the breach of a hull_ analogy that was imparted as framing in early assessments. 😞 

> Great idea! I think this would be a great addition. I added a note in the doc. Would you be willing to draft copy so we can include your perspective?

I'm happy to contribute a few paragraphs relating my perspective both assessee with spiffe and spire. Let me know if there is a particular sense you'd like me to convey. Happy to write about shifting that perspective to assuming the role of lead assessor as I did with harbor and buildpacks.

**Comment by JustinCappos** [comment]
> While I did find the word submarine mentioned once in the draft, it wasn't exactly what I had hoped for. I came here hoping to find @JustinCappos famed _selling a submarine to the government, torpedos, and assuming the breach of the hull_ analogy that was imparted as framing in early assessments. 😞
> 
> > Great idea! I think this would be a great addition. I added a note in the doc. Would you be willing to draft copy so we can include your perspective?
> 
> I'm happy to contribute a few paragraphs relating my perspective both assessee with spiffe and spire. Let me know if there is a particular sense you'd like me to convey. Happy to write about shifting that perspective to assuming the role of lead assessor as I did with harbor and buildpacks.

Looking forward to it!

**Comment by aks-alokraj** [comment]
I'd would like to contribute to this.

**Comment by andrewkrug** [comment]
I would love to help author some of this.  We could bring rapid risk assessment and the methodology behind it into at least "a" chapter.  It would also be great to do some post deployment metrics to know if your security assessments are moving the right needles.

**Comment by includesec-erik** [comment]
@JustinCappos what is the scope of this project? Nothing in this thread so far answers:

1) What type of security assessments are we describing? (Is this only for k8s assessments, application assessments, net pents of CNCF heavy use environments?) 
2) How in-depth are we covering the topic of "security assessments"? Only technical methodologies? General process and project management? Biz side of things like pricing and vendor selection? Any specific reporting formats or techniques covered?
3) Are we covering post-assessment risk analysis and remediation work?


Thanks for helping to explicitly refine the topics and scope of this work. An industry guide to improving security assessments haws been on my mind for a while. The grand majority of companies (yes even big silicon valley companies), do security assessments badly, or even harmfully.

See you around NYC @JustinCappos! twitter.com/NYSECSEC

**Comment by JustinCappos** [comment]
> @JustinCappos what is the scope of this project? Nothing in this thread so far answers:
> 
> 1. What type of security assessments are we describing? (Is this only for k8s assessments, application assessments, net pents of CNCF heavy use environments?)
> 2. How in-depth are we covering the topic of "security assessments"? Only technical methodologies? General process and project management? Biz side of things like pricing and vendor selection? Any specific reporting formats or techniques covered?
> 3. Are we covering post-assessment risk analysis and remediation work?
> 
> Thanks for helping to explicitly refine the topics and scope of this work. An industry guide to improving security assessments haws been on my mind for a while. The grand majority of companies (yes even big silicon valley companies), do security assessments badly, or even harmfully.

We're focused on the (security assessments)[https://github.com/cncf/tag-security/tree/main/assessments] and process we use in the CNCF.  I'm certainly okay with talking about other, related assessment goals, uses, etc. but the focus is to help people contribute to the assessments we do for projects as they move from incubating to graduation, etc.

**Comment by JustinCappos** [comment]
> I would love to help author some of this. We could bring rapid risk assessment and the methodology behind it into at least "a" chapter. It would also be great to do some post deployment metrics to know if your security assessments are moving the right needles.

Sounds good.  I would say that risk assessment and metrics are not mentioned in the depth I would like.  I don't know the state of the art, and the (much) older things I am aware of are not all that useful in practice.  Looking forward to some help here!

**Comment by includesec-erik** [comment]
> We're focused on the (security assessments)[https://github.com/cncf/tag-security/tree/main/assessments] and process we use in the CNCF. I'm certainly okay with talking about other, related assessment goals, uses, etc. but the focus is to help people contribute to the assessments we do for projects as they move from incubating to graduation, etc.

Got it, so it is a tightly coupled CNCF concept and not the general concept(s) that others use when they say "Security Assessment", that answers a big question! Thank you.

A suggestion to minimize confusion for those who aren't tightly involved in the CNCF verbiage. Perhaps qualifying the difference between the two by putting the link you dropped in the description of this issue and mentioning something more aligned with the actual output such as "CNCF Project Security Assessment" might be beneficial to those reading this issue and other related discussions.

I'll explore the concept I mentioned "A guide for 3rd party security assessments" elsewhere outside of this issue/CNCF. Thanks again!

**Comment by achetal01** [comment]
I will like to contribute as well. Security assessment in the pipeline and post deployment as well or what is the precise scope? Or assessment of CNCF projects /products which are open source?

**Comment by nyrahul** [comment]
Great Initiative. Would love to be part of it. I couldn't find a way to add comments in the document.

**Comment by JustinCappos** [comment]
> I will like to contribute as well. Security assessment in the pipeline and post deployment as well or what is the precise scope? Or assessment of CNCF projects /products which are open source?

We're focused on the assessment process for projects in the CNCF, which will be open source.  This is distinct from a security audit (which is also performed later).  The book draft has a description of the differences inside, which I hope helps to answer.  If not, please let me know how I can better clarify.

**Comment by JustinCappos** [comment]
> Great Initiative. Would love to be part of it. I couldn't find a way to add comments in the document.

Sounds good!  Right now we're looking for high level comments or offers to add text like the commentary blocks in the document.  [See above](https://github.com/cncf/tag-security/issues/999#issuecomment-1387138686)!

Feel free to drop more detailed commentary in slack.  We'll likely open it to smaller edits later but want to try to avoid bikeshedding / drive-by comment bombing, so have commenting off for now.  Sorry!

**Comment by vincentgoat** [comment]
One small suggestion: Can we add a section on at what stage a project should do a security assessment?

**Comment by JustinCappos** [comment]
For all who have expressed interest, please be sure to join the #security-assessment-book channel on slack!
